# Generated by Django 4.2.28 on 2026-05-28 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('boilerplate', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('distributed', 'Distributed')], default='draft', max_length=15)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressrelease_set', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('news', 'News'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('review', 'Review'), ('blog', 'Blog'), ('forum', 'Forum')], max_length=10)),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('snippet', models.TextField()),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('crisis', 'Crisis')], max_length=10)),
                ('ai_summary', models.TextField(blank=True)),
                ('response_draft', models.TextField(blank=True)),
                ('responded', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandmention_set', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
