# Generated by Django 4.2.28 on 2026-05-06 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_tooling',
            field=models.BooleanField(default=False, help_text='Is this a consumable tooling asset (e.g., Mold, Die)?'),
        ),
        migrations.AddField(
            model_name='asset',
            name='lifespan_capacity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total expected capacity (e.g., 100,000 shots)', max_digits=14),
        ),
        migrations.AddField(
            model_name='asset',
            name='lifespan_consumed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of capacity used so far', max_digits=14),
        ),
        migrations.CreateModel(
            name='AssetUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, help_text='Order or batch reference for this usage', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='asset_management.asset')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
