# Generated by Django 4.2.28 on 2026-04-30 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0010_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('channel_type', models.CharField(choices=[('ota', 'OTA'), ('gds', 'GDS'), ('direct', 'Direct'), ('wholesaler', 'Wholesaler'), ('metasearch', 'Metasearch')], default='ota', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('api_endpoint', models.CharField(blank=True, max_length=500)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('meal_plan', models.CharField(choices=[('ro', 'Room Only'), ('bb', 'Bed & Breakfast'), ('hb', 'Half Board'), ('fb', 'Full Board'), ('ai', 'All Inclusive')], default='ro', max_length=5)),
                ('is_refundable', models.BooleanField(default=True)),
                ('min_stay', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('rates', 'Rates'), ('availability', 'Availability'), ('reservations', 'Reservations'), ('full', 'Full Sync')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='success', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('records_synced', models.IntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_sync_logs', to='bredbound.businessinstance')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_sync_log_entries', to='channel_manager.channel')),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_name', models.CharField(max_length=200)),
                ('rate_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_rates', to='channel_manager.channel')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_rates', to='channel_manager.rateplan')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('available_rooms', models.IntegerField(default=0)),
                ('sold_rooms', models.IntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['date', 'room_type_name'],
                'unique_together': {('business', 'room_type_name', 'date')},
            },
        ),
    ]
