# Generated by Django 5.0.14 on 2026-06-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0014_businesssubscription_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('legal', 'Legal'), ('ethics', 'Ethics & Discrimination'), ('cybersecurity', 'Cybersecurity'), ('privacy', 'Data Privacy'), ('scope', 'Scope Authorization'), ('harm', 'Harm Prevention'), ('ai_ethics', 'AI Ethics')], max_length=20)),
                ('standard_ref', models.CharField(max_length=200)),
                ('jurisdiction', models.CharField(max_length=200)),
                ('applies_to_agents', models.JSONField(default=list)),
                ('rule_description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('review_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50)),
                ('client_country', models.CharField(max_length=10)),
                ('end_user_country', models.CharField(blank=True, max_length=10)),
                ('action_type', models.CharField(max_length=100)),
                ('action_payload', models.JSONField()),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('blocked', 'Blocked'), ('escalated', 'Escalated to Human'), ('auto_rejected', 'Auto-Rejected')], max_length=20)),
                ('failed_check', models.CharField(blank=True, max_length=50)),
                ('failed_standard', models.CharField(blank=True, max_length=200)),
                ('ai_reasoning', models.TextField()),
                ('confidence', models.FloatField()),
                ('log_hash', models.CharField(blank=True, max_length=64)),
                ('prev_hash', models.CharField(blank=True, max_length=64)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checks', to='bredbound.businessinstance')),
                ('rules_applied', models.ManyToManyField(to='inspector.compliancerule')),
            ],
            options={
                'permissions': [('cannot_delete_log', 'Cannot delete compliance log')],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('contained', 'Contained'), ('notifying', 'Notifying Regulators'), ('resolved', 'Resolved'), ('post_incident_review', 'Post-Incident Review')], default='open', max_length=30)),
                ('affected_records', models.IntegerField(blank=True, null=True)),
                ('regulatory_breach', models.BooleanField(default=False)),
                ('regulations_triggered', models.JSONField(default=list)),
                ('notification_draft', models.TextField(blank=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compliance_check', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='incident', to='inspector.compliancecheck')),
            ],
        ),
    ]
