# Generated by Django 4.2.28 on 2026-05-28 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('meeting_url', models.URLField(blank=True)),
                ('bot_id', models.CharField(blank=True, max_length=100)),
                ('platform', models.CharField(default='zoom', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('raw_transcript', models.TextField(blank=True, help_text='Diarized transcript from the video provider')),
                ('executive_summary', models.TextField(blank=True)),
                ('sentiment', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('recording', 'Recording'), ('processing', 'Processing Transcript'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scribe_meetings', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee_name', models.CharField(blank=True, max_length=100)),
                ('task_description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='scribe.meeting')),
            ],
            options={
                'ordering': ['extracted_at'],
            },
        ),
    ]
