# Generated by Django 5.0.14 on 2026-06-02 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0014_businesssubscription_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('payload', models.JSONField(help_text='Full JSON payload from Stripe')),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to='bredbound.businessinstance')),
            ],
        ),
    ]
