# Generated by Django 4.2.28 on 2026-03-05 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace_admin', '0002_usernotification_order_affiliate'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiemployeetier',
            name='monthly_price_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly price in USD. 0 = Free tier.', max_digits=8),
        ),
        migrations.AddField(
            model_name='aiemployeetier',
            name='n8n_workflow_json',
            field=models.JSONField(blank=True, help_text='n8n workflow configuration JSON for this tier', null=True),
        ),
        migrations.AddField(
            model_name='aiemployeetier',
            name='role',
            field=models.CharField(choices=[('social_media_moderator', 'Social Media Moderator'), ('support_agent', 'Support Agent'), ('content_writer', 'Content Writer'), ('data_analyst', 'Data Analyst'), ('sales_assistant', 'Sales Assistant'), ('general', 'General Purpose')], default='general', help_text='Primary function of this AI Employee tier', max_length=50),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowpayments_order_id', models.CharField(blank=True, help_text='NowPayments payment ID', max_length=255, null=True)),
                ('nowpayments_invoice_url', models.URLField(blank=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('trialing', 'Trialing')], default='trialing', max_length=20)),
                ('amount_paid_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('next_renewal_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('hired_ai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='workspace_admin.hiredaiemployee')),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace_admin.aiemployeetier')),
            ],
        ),
    ]
