# Generated by Django 4.2.29 on 2026-03-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_admin', '0003_phase3_schema_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiemployeetier',
            name='token_limit',
            field=models.IntegerField(default=1000000, help_text='Tokens per month, 0 for unlimited'),
        ),
    ]
