# Generated by Django 4.2.28 on 2026-04-28 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0003_hubplanconfig_storageincreaserequest_and_more'),
        ('workspace_admin', '0005_project_task_financerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=50, unique=True)),
                ('module_name', models.CharField(blank=True, max_length=100)),
                ('monthly_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('annual_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['module_name'],
            },
        ),
        migrations.CreateModel(
            name='AdvancePlanQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_modules', models.JSONField(default=list, help_text='List of module_ids')),
                ('requested_storage_gb', models.FloatField(default=100)),
                ('installation_types', models.JSONField(default=list, help_text="e.g. ['cloud','ip_locked']")),
                ('notes', models.TextField(blank=True)),
                ('base_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('sent', 'Quote Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_quotes', to='bredbound.businessinstance')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
