# Generated by Django 4.2.28 on 2026-05-27 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('workspace_admin', '0006_modulepricingconfig_advanceplanquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredaiemployee',
            name='agent_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hired_instances', to='agents.agentcatalog'),
        ),
    ]
