# Generated by Django 5.0.14 on 2026-06-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_admin', '0007_hiredaiemployee_agent_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='nowpayments_invoice_url',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='nowpayments_order_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID', max_length=255, null=True),
        ),
    ]
