# Generated by Django 4.2.28 on 2026-05-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('role', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('system_prompt', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('tier_required', models.CharField(default='entry', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
