# Generated by Django 4.2.28 on 2026-05-28 03:59

import agents.encryption
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
        ('workspace_admin', '0007_hiredaiemployee_agent_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('working', 'Working'), ('waiting', 'Waiting Approval'), ('offline', 'Offline')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('tokens_used_this_month', models.IntegerField(default=0)),
                ('token_limit_override', models.IntegerField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_instances', to='bredbound.businessinstance')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agents.agentcatalog')),
                ('hired_employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace_admin.hiredaiemployee')),
            ],
            options={
                'unique_together': {('business', 'catalog')},
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=200)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('escalated', 'Escalated'), ('pending', 'Pending')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('tokens', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agents.agentinstance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalAgentInstance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('working', 'Working'), ('waiting', 'Waiting Approval'), ('offline', 'Offline')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('tokens_used_this_month', models.IntegerField(default=0)),
                ('token_limit_override', models.IntegerField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('business', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bredbound.businessinstance')),
                ('catalog', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agents.agentcatalog')),
                ('hired_employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workspace_admin.hiredaiemployee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical agent instance',
                'verbose_name_plural': 'historical agent instances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AgentWebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=100)),
                ('url_token', models.CharField(max_length=64, unique=True)),
                ('secret', models.CharField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('event_count', models.IntegerField(default=0)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='agents.agentinstance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentPermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField(blank=True)),
                ('decision', models.CharField(blank=True, choices=[('approved', 'Approved'), ('denied', 'Denied')], max_length=20, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('executed', models.BooleanField(default=False)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='agents.agentinstance')),
                ('log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentlog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=300)),
                ('memory_type', models.CharField(choices=[('entity', 'Entity'), ('instruction', 'Instruction'), ('context', 'Context'), ('outcome', 'Outcome')], max_length=20)),
                ('content', models.TextField()),
                ('importance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='agents.agentinstance')),
            ],
            options={
                'ordering': ['-importance', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('credential', agents.encryption.EncryptedTextField()),
                ('config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('error', 'Error'), ('expired', 'Expired')], default='connected', max_length=20)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='agents.agentinstance')),
            ],
            options={
                'unique_together': {('instance', 'platform', 'label')},
            },
        ),
    ]
