# Generated by Django 4.2.28 on 2026-05-28 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField()),
                ('cms', models.CharField(blank=True, max_length=50)),
                ('last_crawled', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_set', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('missing_meta', 'Missing Meta'), ('broken_link', 'Broken Link'), ('duplicate_content', 'Duplicate Content'), ('slow_page', 'Slow Page'), ('missing_schema', 'Missing Schema'), ('mobile_issue', 'Mobile Issue'), ('missing_alt', 'Missing Alt')], max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=10)),
                ('page_url', models.URLField()),
                ('description', models.TextField()),
                ('fix_suggestion', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fixed', 'Fixed'), ('ignored', 'Ignored')], default='open', max_length=10)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seoissue_set', to='bredbound.businessinstance')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='oracle.website')),
            ],
            options={
                'ordering': ['-found_at'],
            },
        ),
    ]
