# Generated by Django 4.2.28 on 2026-04-30 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0009_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_email', models.EmailField(max_length=254)),
                ('deal_reference', models.CharField(blank=True, help_text='Property address or deal reference', max_length=200)),
                ('token', models.CharField(blank=True, max_length=64, unique=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('welcome_message', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_portal_accesses', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_portal_accesses', to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('id', 'ID / Passport'), ('financial', 'Financial / Bank Statement'), ('contract', 'Contract / Agreement'), ('disclosure', 'Disclosure'), ('inspection', 'Inspection Report'), ('mortgage', 'Mortgage / Loan Docs'), ('other', 'Other')], default='other', max_length=12)),
                ('source', models.CharField(choices=[('agent', 'Shared by Agent'), ('client', 'Uploaded by Client')], default='agent', max_length=8)),
                ('file_url', models.URLField(blank=True, help_text='Link to document (Drive, Dropbox, etc.)')),
                ('notes', models.TextField(blank=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='re_client_portal.clientportalaccess')),
            ],
            options={
                'ordering': ['doc_type', 'document_name'],
            },
        ),
    ]
