# Generated by Django 4.2.28 on 2026-04-30 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0010_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfp_number', models.CharField(blank=True, max_length=20)),
                ('group_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('wedding', 'Wedding'), ('corporate', 'Corporate'), ('leisure', 'Leisure'), ('sports', 'Sports'), ('other', 'Other')], default='conference', max_length=20)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('rooms_required', models.IntegerField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='inquiry', max_length=20)),
                ('special_requirements', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rfps', to='bredbound.businessemployee')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_rfps', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomingListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('room_type_name', models.CharField(blank=True, max_length=150)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('special_requests', models.TextField(blank=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooming_list', to='group_bookings.grouprfp')),
            ],
            options={
                'ordering': ['guest_name'],
            },
        ),
        migrations.CreateModel(
            name='GroupContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_due_date', models.DateField(blank=True, null=True)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('attrition_pct', models.IntegerField(default=20)),
                ('signed', models.BooleanField(default=False)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rfp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='group_bookings.grouprfp')),
            ],
        ),
        migrations.CreateModel(
            name='GroupBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_name', models.CharField(max_length=150)),
                ('rooms_blocked', models.IntegerField()),
                ('rate_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='group_bookings.grouprfp')),
            ],
            options={
                'ordering': ['room_type_name'],
            },
        ),
    ]
