# Generated by Django 4.2.28 on 2026-04-28 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0003_hubplanconfig_storageincreaserequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Presentation', max_length=300)),
                ('theme', models.CharField(default='dark', max_length=30)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_presentations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HubSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('layout', models.CharField(choices=[('title', 'Title Slide'), ('content', 'Title + Content'), ('two_col', 'Two Columns'), ('blank', 'Blank'), ('image', 'Image Focus')], default='content', max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True, help_text='Main slide content / bullet points')),
                ('notes', models.TextField(blank=True, help_text='Speaker notes')),
                ('background_color', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/images/')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='slides.hubpresentation')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
