# Generated by Django 4.2.28 on 2026-05-28 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('session_type', models.CharField(choices=[('support', 'Customer Support'), ('onboarding', 'Client Onboarding'), ('sales', 'Sales Qualification')], default='support', max_length=50)),
                ('session_id', models.CharField(help_text='HeyGen/D-ID Session ID', max_length=150, unique=True)),
                ('webrtc_sdp', models.TextField(blank=True, help_text='Session Description Protocol payload')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('resolution_status', models.CharField(choices=[('resolved', 'Resolved'), ('escalated', 'Escalated to Human'), ('pending', 'Pending Follow-up')], default='resolved', max_length=50)),
                ('transcript', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_sessions', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
