from django.db import models
from accounts.models import User


class ManufacturingOrder(models.Model):
    STATUS = [('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')]
    PRIORITY = [('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')]

    business = models.ForeignKey('bredbound.BusinessInstance', on_delete=models.CASCADE, related_name='manufacturing_orders')
    mo_number = models.CharField(max_length=30)
    product = models.ForeignKey('inventory.Product', on_delete=models.PROTECT, related_name='manufacturing_orders')
    output_lot = models.ForeignKey('inventory.ProductLot', on_delete=models.SET_NULL, null=True, blank=True, related_name='produced_by_mos', help_text="The batch/lot number generated by this order")
    bom = models.ForeignKey('bom.BillOfMaterials', on_delete=models.SET_NULL, null=True, blank=True)
    quantity_to_produce = models.DecimalField(max_digits=10, decimal_places=2)
    quantity_produced = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    status = models.CharField(max_length=20, choices=STATUS, default='draft')
    priority = models.CharField(max_length=10, choices=PRIORITY, default='normal')
    scheduled_start = models.DateField(null=True, blank=True)
    scheduled_end = models.DateField(null=True, blank=True)
    actual_start = models.DateTimeField(null=True, blank=True)
    actual_end = models.DateTimeField(null=True, blank=True)
    responsible = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='manufacturing_orders')
    warehouse = models.ForeignKey('inventory.Warehouse', on_delete=models.SET_NULL, null=True, blank=True)
    notes = models.TextField(blank=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='created_mos')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"MO-{self.mo_number}: {self.product}"

    @property
    def completion_pct(self):
        if not self.quantity_to_produce:
            return 0
        return round(float(self.quantity_produced) / float(self.quantity_to_produce) * 100)


class WorkOrderOperation(models.Model):
    STATUS = [('pending', 'Pending'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked')]
    manufacturing_order = models.ForeignKey(ManufacturingOrder, on_delete=models.CASCADE, related_name='operations')
    bom_operation = models.ForeignKey('bom.BOMOperation', on_delete=models.SET_NULL, null=True, blank=True)
    work_center = models.ForeignKey('bom.WorkCenter', on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=100)
    sequence = models.IntegerField(default=10)
    planned_duration = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    actual_duration = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    status = models.CharField(max_length=20, choices=STATUS, default='pending')
    worker = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    notes = models.TextField(blank=True)

    class Meta:
        ordering = ['sequence']

    def __str__(self):
        return f"{self.name} — {self.manufacturing_order}"


class MaterialConsumption(models.Model):
    manufacturing_order = models.ForeignKey(ManufacturingOrder, on_delete=models.CASCADE, related_name='material_consumptions')
    product = models.ForeignKey('inventory.Product', on_delete=models.CASCADE)
    consumed_lot = models.ForeignKey('inventory.ProductLot', on_delete=models.SET_NULL, null=True, blank=True, related_name='consumed_in_productions')
    planned_qty = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    consumed_qty = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    actual_scrap_qty = models.DecimalField(max_digits=10, decimal_places=2, default=0, help_text="Amount of material scrapped during production")
    actual_yield_pct = models.DecimalField(max_digits=5, decimal_places=2, default=100, help_text="Actual material yield percentage achieved")
    is_tooling_consumption = models.BooleanField(default=False, help_text="Indicates if this consumption record is for a tooling asset (e.g. Mold shots)")
    uom = models.CharField(max_length=20, blank=True)
    recorded_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    recorded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.product}: {self.consumed_qty}/{self.planned_qty}"


# ── Shoe Factory KPI Framework ────────────────────────────────────────────────

class ProductionKPISnapshot(models.Model):
    """Daily or weekly KPI snapshot aligned with the shoe factory KPI framework:
    OTD, RFT, Defect Rate, Pairs/Labour Hour, WIP Aging, Cost per Pair, etc."""
    PERIOD = [('daily', 'Daily'), ('weekly', 'Weekly')]

    business = models.ForeignKey('bredbound.BusinessInstance', on_delete=models.CASCADE, related_name='production_kpi_snapshots')
    snapshot_date = models.DateField()
    period = models.CharField(max_length=10, choices=PERIOD, default='daily')

    # On-Time Delivery
    orders_due = models.PositiveIntegerField(default=0)
    orders_on_time = models.PositiveIntegerField(default=0)

    # Right First Time
    pairs_to_final_qc = models.PositiveIntegerField(default=0)
    pairs_passed_first = models.PositiveIntegerField(default=0)

    # Defect Rate
    pairs_produced = models.PositiveIntegerField(default=0)
    pairs_rejected_reworked = models.PositiveIntegerField(default=0)

    # Productivity
    total_labour_hours = models.DecimalField(max_digits=8, decimal_places=2, default=0)

    # WIP Aging (pairs stuck at lasting stage)
    wip_pairs_at_lasting = models.PositiveIntegerField(default=0)

    # Cost
    total_production_cost = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)

    notes = models.TextField(blank=True)
    recorded_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='kpi_snapshots_recorded')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [('business', 'snapshot_date', 'period')]
        ordering = ['-snapshot_date']

    def __str__(self):
        return f"KPI {self.snapshot_date} ({self.period})"

    @property
    def otd_pct(self):
        return round(self.orders_on_time / self.orders_due * 100, 1) if self.orders_due else 0

    @property
    def rft_pct(self):
        return round(self.pairs_passed_first / self.pairs_to_final_qc * 100, 1) if self.pairs_to_final_qc else 0

    @property
    def defect_rate_per_100(self):
        return round(self.pairs_rejected_reworked / self.pairs_produced * 100, 1) if self.pairs_produced else 0

    @property
    def pairs_per_labour_hour(self):
        return round(self.pairs_produced / float(self.total_labour_hours), 2) if self.total_labour_hours else 0

    @property
    def cost_per_pair(self):
        if self.total_production_cost and self.pairs_produced:
            return round(float(self.total_production_cost) / self.pairs_produced, 2)
        return 0
