# Generated by Django 4.2.28 on 2026-05-28 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('specialty', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('slot_duration', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_set', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=300)),
                ('patient_phone', models.CharField(max_length=30)),
                ('patient_email', models.EmailField(blank=True, max_length=254)),
                ('scheduled_at', models.DateTimeField()),
                ('duration', models.IntegerField(default=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='booked', max_length=15)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('ai_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_set', to='bredbound.businessinstance')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='medibook.doctor')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
