# Generated by Django 5.0.14 on 2026-06-04 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_legal_name', models.CharField(max_length=500)),
                ('registration_number', models.CharField(max_length=200)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('registered_address', models.TextField()),
                ('incorporation_date', models.DateField(null=True)),
                ('business_type', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('vat_number', models.CharField(blank=True, max_length=100)),
                ('director_name', models.CharField(max_length=300)),
                ('director_email', models.EmailField(max_length=254)),
                ('director_phone', models.CharField(max_length=30)),
                ('registry_verified', models.BooleanField(null=True)),
                ('sanctions_clear', models.BooleanField(null=True)),
                ('aml_clear', models.BooleanField(null=True)),
                ('documents_verified', models.BooleanField(null=True)),
                ('risk_score', models.IntegerField(null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], max_length=10)),
                ('gemini_risk_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('documents_pending', 'Documents Pending'), ('under_review', 'Under Review — Automated'), ('human_review', 'Human Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='submitted', max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(null=True)),
                ('rejected_at', models.DateTimeField(null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('next_review_date', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('tos', 'Terms of Service'), ('dpa', 'Data Processing Agreement'), ('aup', 'Acceptable Use Policy'), ('ai_ethics', 'AI Ethics Acknowledgement')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('signature_hash', models.CharField(max_length=64)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veritas.clientapplication')),
            ],
        ),
        migrations.CreateModel(
            name='KYBDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('incorporation', 'Certificate of Incorporation'), ('trade_license', 'Trade License'), ('vat_cert', 'VAT/Tax Certificate'), ('proof_address', 'Proof of Business Address'), ('director_passport', 'Director Passport'), ('director_id', 'Director National ID'), ('bank_statement', 'Bank Statement Header')], max_length=30)),
                ('file', models.FileField(upload_to='kyb/documents/')),
                ('ocr_extracted_data', models.JSONField(default=dict)),
                ('ai_verification', models.BooleanField(null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veritas.clientapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SanctionsCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_entity', models.CharField(max_length=500)),
                ('list_checked', models.CharField(max_length=100)),
                ('match_found', models.BooleanField(default=False)),
                ('match_score', models.FloatField(null=True)),
                ('match_detail', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veritas.clientapplication')),
            ],
        ),
    ]
