# Generated by Django 4.2.28 on 2026-04-29 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0006_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('chart_type', models.CharField(choices=[('table', 'Data Table'), ('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie / Donut Chart'), ('scatter', 'Scatter Plot'), ('area', 'Area Chart'), ('pivot', 'Pivot Summary')], default='table', max_length=10)),
                ('x_column', models.CharField(blank=True, max_length=100)),
                ('y_column', models.CharField(blank=True, max_length=100)),
                ('group_column', models.CharField(blank=True, max_length=100)),
                ('filter_config', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_charts', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataStudioReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_reports', to='bredbound.businessinstance')),
                ('charts', models.ManyToManyField(blank=True, related_name='reports', to='data_studio.analyticschart')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('csv', 'CSV Import'), ('json', 'JSON Import')], default='manual', max_length=10)),
                ('columns', models.JSONField(default=list)),
                ('rows', models.JSONField(default=list)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.AddField(
            model_name='analyticschart',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='data_studio.dataset'),
        ),
    ]
