# Generated by Django 4.2.28 on 2026-04-30 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0008_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanogramSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('store_location', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_layouts', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_layouts', to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanogramSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('shelf_number', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(blank=True, help_text='e.g. Left, Centre, Right or slot number', max_length=20)),
                ('facings', models.PositiveIntegerField(default=1)),
                ('min_stock', models.IntegerField(blank=True, null=True)),
                ('current_stock', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='planogram.planogramsection')),
            ],
            options={
                'ordering': ['shelf_number', 'position'],
            },
        ),
        migrations.AddField(
            model_name='planogramsection',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='planogram.storelayout'),
        ),
    ]
