# Generated by Django 4.2.28 on 2026-04-30 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0009_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_address', models.TextField()),
                ('client_name', models.CharField(max_length=150)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('deal_type', models.CharField(choices=[('purchase', 'Purchase / Buy Side'), ('sale', 'Sale / List Side'), ('lease', 'Lease / Rental'), ('referral', 'Referral'), ('dual', 'Dual Agency')], default='purchase', max_length=10)),
                ('stage', models.CharField(choices=[('prospect', 'Prospect'), ('offer', 'Offer Made'), ('under_contract', 'Under Contract'), ('inspection', 'Inspection'), ('appraisal', 'Appraisal'), ('financing', 'Financing / Mortgage'), ('closing', 'Closing'), ('closed', 'Closed / Won'), ('dead', 'Dead / Lost')], default='prospect', max_length=20)),
                ('listing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('commission_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Commission %')),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('broker_approved', models.BooleanField(default=False)),
                ('broker_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to='bredbound.businessemployee')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DealNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_notes', to='bredbound.businessemployee')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_notes', to='deal_flow.deal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='deal_flow.deal')),
            ],
            options={
                'ordering': ['is_done', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='DealDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploaded', 'Uploaded'), ('approved', 'Approved'), ('rejected', 'Rejected / Needs Revision')], default='pending', max_length=10)),
                ('file_url', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='deal_flow.deal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_deal_docs', to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['is_required', 'document_name'],
            },
        ),
    ]
