# Generated by Django 4.2.28 on 2026-04-29 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0006_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_maps', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_processes', to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('step_type', models.CharField(choices=[('start', 'Start Event'), ('end', 'End Event'), ('task', 'Task / Activity'), ('decision', 'Decision / Gateway'), ('subprocess', 'Sub-process'), ('delay', 'Delay / Wait'), ('approval', 'Approval Gate'), ('notification', 'Notification'), ('system', 'System / Automated Step')], default='task', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('responsible_role', models.CharField(blank=True, max_length=100)),
                ('duration_estimate', models.CharField(blank=True, max_length=50)),
                ('inputs', models.TextField(blank=True)),
                ('outputs', models.TextField(blank=True)),
                ('tools_used', models.CharField(blank=True, max_length=200)),
                ('sla', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('process_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='process_mapper.processmap')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_steps', to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('assumptions', models.TextField(blank=True)),
                ('results_summary', models.TextField(blank=True)),
                ('throughput_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_cycle_time', models.CharField(blank=True, max_length=50)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('bottleneck_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='process_mapper.processstep')),
                ('process_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='process_mapper.processmap')),
                ('run_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('sequence', 'Sequence Flow'), ('yes', 'Yes Branch'), ('no', 'No Branch'), ('exception', 'Exception Path')], default='sequence', max_length=10)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('from_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_flows', to='process_mapper.processstep')),
                ('process_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='process_mapper.processmap')),
                ('to_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_flows', to='process_mapper.processstep')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(blank=True, null=True, upload_to='process_maps/docs/')),
                ('url', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('process_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='process_mapper.processmap')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
