# Generated by Django 4.2.28 on 2026-04-29 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0004_businessemployee_phone_alter_businessemployee_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CADProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('tool', models.CharField(choices=[('fusion360', 'Autodesk Fusion 360'), ('freecad', 'FreeCAD'), ('camotics', 'CAMotics (Simulation)'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('pending_integration', 'Pending Integration')], default='pending_integration', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadcam_projects', to='bredbound.businessinstance')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CADFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='cadcam/files/')),
                ('format', models.CharField(choices=[('step', 'STEP (.step/.stp)'), ('iges', 'IGES (.iges/.igs)'), ('stl', 'STL (.stl)'), ('dxf', 'DXF (.dxf)'), ('dwg', 'DWG (.dwg)'), ('f3d', 'Fusion 360 (.f3d)'), ('fcstd', 'FreeCAD (.FCStd)'), ('gcode', 'G-code (.nc/.gcode)'), ('other', 'Other')], default='other', max_length=10)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cadcam.cadproject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
