# Generated by Django 4.2.28 on 2026-04-28 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('target', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('period_date', models.DateField()),
                ('source_module', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_metrics', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-period_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('manual', 'Manual Upload'), ('crm', 'CRM'), ('hr', 'HR'), ('accounting', 'Accounting'), ('inventory', 'Inventory'), ('pos', 'POS'), ('ecommerce', 'eCommerce'), ('external', 'External API')], default='manual', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('row_count', models.IntegerField(default=0)),
                ('last_refreshed', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_datasets', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('trend', 'Trend Analysis'), ('anomaly', 'Anomaly Detection'), ('forecast', 'Forecast'), ('recommendation', 'Recommendation'), ('summary', 'Summary')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('chart_data', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('generated_by', models.CharField(blank=True, help_text='AI model used', max_length=100)),
                ('is_actionable', models.BooleanField(default=False)),
                ('action_taken', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='bredbound.businessinstance')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_analytics.analyticsdataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
