# Generated by Django 4.2.28 on 2026-04-30 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0009_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DripCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('target_audience', models.CharField(choices=[('buyers', 'Buyers'), ('sellers', 'Sellers'), ('renters', 'Renters'), ('investors', 'Investors'), ('past_clients', 'Past Clients'), ('all', 'All Contacts')], default='all', max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drip_campaigns', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('just_listed', 'Just Listed'), ('just_sold', 'Just Sold'), ('open_house', 'Open House'), ('price_drop', 'Price Reduction'), ('under_contract', 'Under Contract'), ('market_update', 'Market Update'), ('custom', 'Custom')], default='just_listed', max_length=20)),
                ('property_address', models.CharField(blank=True, max_length=300)),
                ('caption', models.TextField()),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('both', 'Facebook & Instagram'), ('linkedin', 'LinkedIn')], default='both', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('posted', 'Posted')], default='draft', max_length=10)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(max_length=300)),
                ('template', models.CharField(choices=[('standard', 'Standard'), ('luxury', 'Luxury'), ('minimal', 'Minimal'), ('open_house', 'Open House'), ('just_sold', 'Just Sold')], default='standard', max_length=15)),
                ('headline', models.CharField(blank=True, help_text='e.g. "Just Listed!", "Stunning Family Home"', max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='Short selling statement', max_length=300)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('open_house_date', models.CharField(blank=True, help_text='e.g. Sunday 2pm – 4pm', max_length=100)),
                ('agent_name', models.CharField(blank=True, max_length=150)),
                ('agent_phone', models.CharField(blank=True, max_length=30)),
                ('agent_email', models.EmailField(blank=True, max_length=254)),
                ('property_url', models.URLField(blank=True)),
                ('virtual_tour_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_flyers', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flyers', to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DripMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('delay_days', models.PositiveIntegerField(default=0, help_text='Days after enrolment to send')),
                ('message_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS / Text')], default='email', max_length=6)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='re_marketing.dripcampaign')),
            ],
            options={
                'ordering': ['delay_days'],
            },
        ),
    ]
