# Generated by Django 4.2.28 on 2026-05-28 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('product_launch', 'Product Launch'), ('team_building', 'Team Building'), ('webinar', 'Webinar'), ('gala', 'Gala')], max_length=15)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=500)),
                ('expected_headcount', models.IntegerField()),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spent_so_far', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('confirmed', 'Confirmed'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=10)),
                ('ai_plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_set', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=300)),
                ('rsvp_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('waitlist', 'Waitlist')], default='pending', max_length=10)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('attended', models.BooleanField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_set', to='bredbound.businessinstance')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='tempo.event')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
