# Generated by Django 4.2.28 on 2026-05-27 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('onboarding', 'Onboarding'), ('checkin', 'Check-In'), ('nps', 'NPS'), ('renewal', 'Renewal'), ('upsell', 'Upsell'), ('intervention', 'Intervention')], max_length=15)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mira_success_emails', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.IntegerField()),
                ('risk_level', models.CharField(choices=[('healthy', 'Healthy'), ('at_risk', 'At Risk'), ('critical', 'Critical'), ('churned', 'Churned')], max_length=10)),
                ('login_frequency', models.FloatField(default=0)),
                ('feature_usage', models.FloatField(default=0)),
                ('open_tickets', models.IntegerField(default=0)),
                ('churn_probability', models.FloatField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mira_client_healths', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
