# Generated by Django 4.2.28 on 2026-05-18 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0011_alter_businessinstance_business_type'),
        ('plm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_code', models.CharField(help_text='Design master code e.g. OX-001', max_length=50)),
                ('sku_code', models.CharField(blank=True, help_text='Full SKU per CC-SS-MM-CL-GG-NN convention', max_length=60)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('sneakers', 'Sneakers'), ('sandals', 'Sandals'), ('ladies_heels', 'Ladies Heels'), ('oxfords', 'Formal Oxfords'), ('loafers', 'Penny Loafers'), ('boots', 'Boots'), ('other', 'Other')], default='other', max_length=20)),
                ('construction', models.CharField(choices=[('cemented', 'Cemented'), ('strobel', 'Cup-sole / Strobel'), ('goodyear', 'Goodyear Welted'), ('moccasin', 'Moccasin / Hand-stitched'), ('blake', 'Blake Stitched'), ('slip_lasted', 'Slip Lasted'), ('other', 'Other')], default='cemented', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('U', 'Unisex'), ('K', 'Kids')], default='U', max_length=1)),
                ('tier', models.CharField(choices=[('hero', 'Hero'), ('core', 'Core'), ('entry', 'Entry'), ('promo', 'Promo'), ('private_label', 'Private Label')], default='core', max_length=15)),
                ('last_code', models.CharField(blank=True, max_length=50)),
                ('size_run', models.CharField(blank=True, help_text='e.g. 39–45 (EU)', max_length=30)),
                ('sample_size', models.CharField(blank=True, max_length=10)),
                ('lifecycle', models.CharField(choices=[('development', 'Development'), ('active', 'Active'), ('run_out', 'Run-out'), ('archived', 'Archived')], default='development', max_length=15)),
                ('ex_factory_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('moq', models.PositiveIntegerField(blank=True, help_text='MOQ per style', null=True)),
                ('moq_per_colour', models.PositiveIntegerField(blank=True, null=True)),
                ('pattern_ready', models.BooleanField(default=False)),
                ('grading_done', models.BooleanField(default=False)),
                ('sample_approved', models.BooleanField(default=False)),
                ('costed_bom_ref', models.CharField(blank=True, max_length=100)),
                ('image_ref', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_articles', to='bredbound.businessinstance')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoe_articles_owned', to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['category', 'article_code'],
                'unique_together': {('business', 'article_code')},
            },
        ),
        migrations.CreateModel(
            name='SampleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdo_number', models.CharField(max_length=30)),
                ('stage', models.CharField(choices=[('proto', 'Proto Sample'), ('fit', 'Fit Sample'), ('salesman', 'Salesman Sample'), ('pp', 'Pre-Production (PP)'), ('shipment', 'Shipment Sample')], max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('buyer', models.CharField(blank=True, max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size_set', models.CharField(blank=True, max_length=50)),
                ('material_colour_spec', models.CharField(blank=True, max_length=200)),
                ('tech_pack_ref', models.CharField(blank=True, max_length=100)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('is_charged', models.BooleanField(default=False)),
                ('sample_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sdos', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_orders', to='plm.shoearticle')),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_sdos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('article', 'sdo_number')},
            },
        ),
        migrations.CreateModel(
            name='SampleBuyerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(choices=[('last_fitting', 'Last Fitting'), ('upper_construction', 'Upper Construction'), ('stitch_density', 'Stitch Density'), ('sole_bonding', 'Sole Bonding'), ('finishing', 'Finishing & Polish'), ('branding', 'Branding'), ('packaging', 'Packaging'), ('overall_appearance', 'Overall Appearance')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('action_required', models.TextField(blank=True)),
                ('owner_status', models.CharField(blank=True, max_length=100)),
                ('sample_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_comments', to='plm.sampleorder')),
            ],
        ),
    ]
