# Generated by Django 5.0.14 on 2026-06-02 02:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Twilio number assigned to this queue', max_length=20)),
                ('strategy', models.CharField(choices=[('round_robin', 'Round Robin'), ('simultaneous', 'Simultaneous Ring'), ('priority', 'Priority Order')], default='round_robin', max_length=20)),
                ('max_wait_seconds', models.IntegerField(default=120, help_text='Before going to voicemail')),
                ('hold_music_url', models.URLField(blank=True, help_text='MP3 URL for hold music')),
                ('greeting_text', models.TextField(default='Thank you for calling. Please hold while we connect you.', help_text='Spoken to the caller when they enter the queue')),
                ('voicemail_enabled', models.BooleanField(default=True)),
                ('voicemail_text', models.TextField(blank=True, default='Sorry we missed you. Please leave a message after the tone.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agents', models.ManyToManyField(blank=True, related_name='call_queues', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_queues', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_call_sid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('caller_number', models.CharField(max_length=30)),
                ('called_number', models.CharField(max_length=30)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ringing', 'Ringing'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('no-answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('voicemail', 'Voicemail'), ('abandoned', 'Abandoned')], default='queued', max_length=20)),
                ('ivr_path', models.CharField(blank=True, help_text='Digits pressed through IVR e.g. 1>2', max_length=100)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('wait_seconds', models.IntegerField(default=0)),
                ('recording_url', models.URLField(blank=True)),
                ('recording_sid', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_calls', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='bredbound.businessinstance')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='crm.contact')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='call_center.callqueue')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IVRMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('welcome_message', models.TextField(default='Welcome. Press 1 for Sales, Press 2 for Support, Press 0 to speak with an operator.')),
                ('invalid_message', models.TextField(blank=True, default='Sorry, that option is not valid. Please try again.')),
                ('timeout_seconds', models.IntegerField(default=10)),
                ('max_retries', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivr_menus', to='bredbound.businessinstance')),
            ],
        ),
        migrations.AddField(
            model_name='callqueue',
            name='ivr_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='call_center.ivrmenu'),
        ),
        migrations.CreateModel(
            name='TwilioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(blank=True, max_length=64)),
                ('auth_token', models.CharField(blank=True, max_length=64)),
                ('default_from_number', models.CharField(blank=True, help_text='E.164 format e.g. +14155552671', max_length=20)),
                ('twiml_app_sid', models.CharField(blank=True, help_text='TwiML App SID for browser calls', max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twilio_config', to='bredbound.businessinstance')),
            ],
        ),
        migrations.CreateModel(
            name='AgentCallStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_call', 'On Call'), ('wrap_up', 'Wrap Up'), ('break', 'On Break'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('last_status_change', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_statuses', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_call_statuses', to='bredbound.businessinstance')),
                ('current_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_agent_status', to='call_center.calllog')),
            ],
            options={
                'unique_together': {('business', 'agent')},
            },
        ),
        migrations.CreateModel(
            name='IVROption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digit', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('*', '*'), ('#', '#')], max_length=2)),
                ('label', models.CharField(help_text='e.g. Sales, Support, Billing', max_length=100)),
                ('action', models.CharField(choices=[('queue', 'Route to Queue'), ('message', 'Play Message'), ('transfer', 'Transfer to Number'), ('voicemail', 'Go to Voicemail'), ('hangup', 'Hang Up'), ('submenu', 'Go to Sub-menu')], default='queue', max_length=20)),
                ('transfer_number', models.CharField(blank=True, help_text='E.164 for external transfer', max_length=20)),
                ('message_text', models.TextField(blank=True, help_text='Text to speak for message action')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='call_center.ivrmenu')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ivr_options', to='call_center.callqueue')),
                ('submenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_options', to='call_center.ivrmenu')),
            ],
            options={
                'ordering': ['digit'],
                'unique_together': {('menu', 'digit')},
            },
        ),
    ]
