# Generated by Django 5.0.14 on 2026-06-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilioconfig',
            name='api_key_secret',
            field=models.CharField(blank=True, help_text='API Key Secret — shown once when created', max_length=64),
        ),
        migrations.AddField(
            model_name='twilioconfig',
            name='api_key_sid',
            field=models.CharField(blank=True, help_text='API Key SID (SK...) — create in Twilio Console → API Keys', max_length=64),
        ),
        migrations.AlterField(
            model_name='twilioconfig',
            name='auth_token',
            field=models.CharField(blank=True, help_text='Master Auth Token — used only to validate Twilio webhook signatures', max_length=64),
        ),
    ]
