# Generated by Django 4.2.28 on 2026-03-05 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_admin', '0002_usernotification_order_affiliate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('console_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceproject',
            name='status',
            field=models.CharField(default='planning', max_length=50),
        ),
        migrations.CreateModel(
            name='WorkspaceEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AICredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('api_key_or_token', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace_admin.hiredaiemployee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='workspaceproject',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='console_admin.workspaceenvironment'),
        ),
    ]
