# Generated by Django 4.2.28 on 2026-03-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console_admin', '0002_workspaceproject_status_workspaceenvironment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceproject',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for data syncing between this project and BengalBound', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workspaceproject',
            name='domain',
            field=models.CharField(blank=True, help_text='Production domain for this project', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workspaceproject',
            name='project_type',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('software', 'Software'), ('api', 'API / Integration'), ('other', 'Other')], default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='workspaceproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workspaceproject',
            name='status',
            field=models.CharField(choices=[('design', 'Design'), ('development', 'Development'), ('testing', 'Testing'), ('live', 'Live'), ('paused', 'Paused')], default='design', max_length=20),
        ),
    ]
