# Generated by Django 4.2.28 on 2026-03-05 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_admin', '0003_phase3_schema_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('console_admin', '0003_phase3_schema_fixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITrainingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('instruction', 'Custom Instruction'), ('faq', 'FAQ Document'), ('product_info', 'Product/Service Info'), ('tone_guide', 'Tone & Voice Guide'), ('other', 'Other')], default='instruction', max_length=20)),
                ('content', models.TextField(help_text='Paste training content or instructions here')),
                ('is_active', models.BooleanField(default=True, help_text='Only active documents are passed to the AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_docs', to='workspace_admin.hiredaiemployee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AITaskLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_tasks_per_day', models.IntegerField(default=50, help_text='Max tasks Serea can process per day')),
                ('max_tokens_per_month', models.IntegerField(default=0, help_text='0 = use tier default')),
                ('is_paused', models.BooleanField(default=False, help_text='Temporarily pause this AI employee')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='workspace_admin.hiredaiemployee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client', 'ai_employee')},
            },
        ),
    ]
