# Generated by Django 4.2.28 on 2026-05-26 20:13

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('console_admin', '0005_consolemoduleactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicredential',
            name='api_key_or_token',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
