# Generated by Django 4.2.29 on 2026-03-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0004_phase4_cms_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(blank=True, help_text='Bootstrap icon class (e.g., bi-rocket)', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(blank=True, help_text='Bootstrap icon class (e.g., bi-laptop)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='platform_features/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=5, help_text='Rating out of 5')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('step_number', models.IntegerField(default=1)),
                ('icon_class', models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
