# Generated by Django 4.2.29 on 2026-03-15 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0005_corevalue_platformfeature_testimonial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Documentation Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown on the card.')),
                ('thumbnail', models.ImageField(blank=True, help_text='Card preview image (recommended: 600x400px)', null=True, upload_to='docs/thumbnails/')),
                ('author_name', models.CharField(default='BengalBound Team', max_length=150)),
                ('author_avatar', models.ImageField(blank=True, null=True, upload_to='docs/avatars/')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('external_url', models.URLField(blank=True, help_text='If set, the card links here instead of an internal page.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs', to='public_site.documentationcategory')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
