# Generated by Django 4.2.29 on 2026-03-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0006_documentationcategory_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (e.g. https://youtube.com/watch?v=...). Adds a play button to the card.'),
        ),
    ]
