# Generated by Django 4.2.29 on 2026-03-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0007_documentation_youtube_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='website_url',
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, help_text='Partner website URL (optional).'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(help_text='Upload the partner logo (SVG, PNG, or WebP recommended, transparent background).', upload_to='partners/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
