# Generated by Django 4.2.29 on 2026-05-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0008_alter_partner_options_remove_partner_website_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='123 AI Boulevard\nTech District, Innovation City 90210')),
                ('phone', models.CharField(default='+1 (555) 123-4567', max_length=50)),
                ('email', models.EmailField(default='hello@bengalbound.com', max_length=254)),
                ('working_hours', models.CharField(default='Mon - Fri, 9am - 6pm EST', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Company Details',
            },
        ),
    ]
