# Generated by Django 4.2.28 on 2026-04-28 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('total_points', models.IntegerField(default=0)),
                ('lifetime_points', models.IntegerField(default=0)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reward_type', models.CharField(choices=[('points', 'Points'), ('cashback', 'Cashback'), ('tiers', 'Tier-Based')], default='points', max_length=10)),
                ('points_per_currency', models.DecimalField(decimal_places=2, default=1, help_text='Points earned per currency unit spent', max_digits=8)),
                ('currency_per_point', models.DecimalField(decimal_places=4, default=0.01, help_text='Currency value per point when redeeming', max_digits=8)),
                ('min_redemption_points', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_days', models.IntegerField(default=0, help_text='0 = no expiry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_programs', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'Earned'), ('redeem', 'Redeemed'), ('expire', 'Expired'), ('adjust', 'Adjustment'), ('bonus', 'Bonus')], max_length=10)),
                ('points', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltymember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_points', models.IntegerField(default=0)),
                ('point_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('color', models.CharField(default='#f59e0b', max_length=7)),
                ('benefits', models.TextField(blank=True)),
                ('position', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='loyalty.loyaltyprogram')),
            ],
            options={
                'ordering': ['position', 'min_points'],
            },
        ),
        migrations.AddField(
            model_name='loyaltymember',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='loyalty.loyaltyprogram'),
        ),
        migrations.AddField(
            model_name='loyaltymember',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.loyaltytier'),
        ),
        migrations.AddField(
            model_name='loyaltymember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
