# Generated by Django 4.2.28 on 2026-03-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('workspace_admin', 'Workspace Admin'), ('console_user', 'Console User'), ('affiliate', 'Affiliate')], default='console_user', max_length=20),
        ),
    ]
