"""
Management command: python manage.py seed_modules

Seeds the ModuleCatalog with all planned business modules.
Safe to run multiple times — uses update_or_create.
"""
from django.core.management.base import BaseCommand
from hub.models import ModuleCatalog

ALL_MODULES = [
    # ── Operations ───────────────────────────────────────────────────────────
    {
        'module_id': 'pos',
        'name': 'Point of Sale (POS)',
        'tagline': 'Ring sales, accept payments, print receipts.',
        'description': 'Full-featured POS system for retail, restaurants, and service counters. Supports cash, card, and digital payments.',
        'category': 'operations',
        'icon': 'bi-cart-check',
        'is_free': False,
        'monthly_price_usd': '9.99',
        'applicable_to': ['shop', 'retail_chain', 'wholesale', 'restaurant', 'station', 'hotel', 'other'],
        'display_order': 10,
        'url_namespace': 'pos',
    },
    {
        'module_id': 'inventory',
        'name': 'Inventory & Stock',
        'tagline': 'Track every unit, everywhere.',
        'description': 'Real-time stock tracking, low-stock alerts, barcode scanning, multi-warehouse support, and vendor reorder management.',
        'category': 'operations',
        'icon': 'bi-boxes',
        'is_free': False,
        'monthly_price_usd': '9.99',
        'applicable_to': ['all'],
        'display_order': 11,
        'url_namespace': 'inventory',
    },
    {
        'module_id': 'order_mgmt',
        'name': 'Order Management',
        'tagline': 'From quote to fulfilment in one place.',
        'description': 'Manage purchase orders, sales orders, supplier quotes, and delivery tracking end-to-end.',
        'category': 'operations',
        'icon': 'bi-receipt',
        'is_free': False,
        'monthly_price_usd': '7.99',
        'applicable_to': ['all'],
        'display_order': 12,
        'url_namespace': 'order_mgmt',
    },
    {
        'module_id': 'table_mgmt',
        'name': 'Table Management',
        'tagline': 'Floor plans, reservations, and service flow.',
        'description': 'Visual floor plan editor, table reservations, split bills, and waiter assignment for restaurants and hotels.',
        'category': 'operations',
        'icon': 'bi-layout-wtf',
        'is_free': False,
        'monthly_price_usd': '7.99',
        'applicable_to': ['restaurant', 'hotel'],
        'display_order': 13,
        'url_namespace': 'table_mgmt',
    },
    {
        'module_id': 'delivery',
        'name': 'Delivery & Logistics',
        'tagline': 'Dispatch, track, and deliver.',
        'description': 'Manage delivery orders, assign drivers, track in real-time, and generate delivery manifests.',
        'category': 'operations',
        'icon': 'bi-truck',
        'is_free': False,
        'monthly_price_usd': '9.99',
        'applicable_to': ['shop', 'retail_chain', 'wholesale', 'restaurant', 'warehouse', 'factory', 'other'],
        'display_order': 14,
        'url_namespace': 'delivery',
    },

    # ── Finance & Accounting ─────────────────────────────────────────────────
    {
        'module_id': 'accounting',
        'name': 'Accounting & Bookkeeping',
        'tagline': 'Charts of accounts, journals, and balance sheets.',
        'description': 'Double-entry bookkeeping, profit & loss, balance sheet, general ledger, and tax reports. GST/VAT ready.',
        'category': 'finance',
        'icon': 'bi-calculator',
        'is_free': False,
        'monthly_price_usd': '12.99',
        'applicable_to': ['all'],
        'display_order': 20,
        'url_namespace': 'accounting',
    },
    {
        'module_id': 'invoicing',
        'name': 'Invoicing & Billing',
        'tagline': 'Professional invoices sent in seconds.',
        'description': 'Create, send, and track invoices and estimates. Supports recurring billing, payment reminders, and multi-currency.',
        'category': 'finance',
        'icon': 'bi-file-earmark-text',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 21,
        'url_namespace': 'invoicing',
    },
    {
        'module_id': 'payroll',
        'name': 'Payroll Processing',
        'tagline': 'Automate pay runs and statutory filings.',
        'description': 'Employee salaries, overtime, deductions, tax withholding, payslips, and compliance reports.',
        'category': 'finance',
        'icon': 'bi-cash-coin',
        'is_free': False,
        'monthly_price_usd': '9.99',
        'applicable_to': ['all'],
        'requires_modules': ['hr'],
        'display_order': 22,
        'url_namespace': 'payroll',
    },
    {
        'module_id': 'expense',
        'name': 'Expense Tracking',
        'tagline': 'Capture, categorise, and approve expenses.',
        'description': 'Employee expense claims, receipt uploads, approval workflows, and expense reports tied to your accounts.',
        'category': 'finance',
        'icon': 'bi-wallet2',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 23,
        'url_namespace': 'expense',
    },
    {
        'module_id': 'budgeting',
        'name': 'Budgeting & Forecasting',
        'tagline': 'Plan your finances with confidence.',
        'description': 'Create department budgets, track actuals vs. forecast, and get AI-powered financial projections.',
        'category': 'finance',
        'icon': 'bi-graph-up-arrow',
        'is_free': False,
        'monthly_price_usd': '7.99',
        'applicable_to': ['all'],
        'display_order': 24,
        'url_namespace': 'budgeting',
    },
    {
        'module_id': 'accounts_payable',
        'name': 'Accounts Payable & Vendors',
        'tagline': 'Track bills, vendor credits, and outgoing payments.',
        'description': 'Manage vendor details, track incoming bills, record payments made, and manage vendor credits. Integrates with inventory and accounting.',
        'category': 'finance',
        'icon': 'bi-receipt-cutoff',
        'is_free': False,
        'monthly_price_usd': '9.99',
        'applicable_to': ['all'],
        'display_order': 25,
        'url_namespace': 'accounts_payable',
    },
    {
        'module_id': 'bank_reconciliation',
        'name': 'Banking & Reconciliation',
        'tagline': 'Automated bank feeds and transaction matching.',
        'description': 'Connect your bank accounts securely, fetch feeds automatically, and reconcile transactions with your ledger in one click.',
        'category': 'finance',
        'icon': 'bi-bank',
        'is_free': False,
        'monthly_price_usd': '9.99',
        'applicable_to': ['all'],
        'display_order': 26,
        'url_namespace': 'bank_reconciliation',
    },
    {
        'module_id': 'tax_compliance',
        'name': 'Tax & Compliance',
        'tagline': 'Always be ready for tax season.',
        'description': 'Auto-calculate VAT/GST, generate tax return reports, and stay compliant with local statutory regulations.',
        'category': 'finance',
        'icon': 'bi-file-earmark-ruled',
        'is_free': False,
        'monthly_price_usd': '7.99',
        'applicable_to': ['all'],
        'display_order': 27,
        'url_namespace': 'tax_compliance',
    },

    # ── People & HR ──────────────────────────────────────────────────────────
    {
        'module_id': 'hr',
        'name': 'Human Resources',
        'tagline': 'Your people, organised.',
        'description': 'Employee profiles, org chart, leave management, performance reviews, and contract storage.',
        'category': 'people',
        'icon': 'bi-people',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 30,
        'url_namespace': 'hr',
    },
    {
        'module_id': 'attendance',
        'name': 'Attendance & Timekeeping',
        'tagline': 'Clock-ins, shifts, and overtime — automated.',
        'description': 'Digital clock-in (PIN, QR, or biometric), shift scheduling, overtime tracking, and timesheets.',
        'category': 'people',
        'icon': 'bi-clock-history',
        'is_free': False,
        'monthly_price_usd': '5.99',
        'applicable_to': ['all'],
        'requires_modules': ['hr'],
        'display_order': 31,
        'url_namespace': 'attendance',
    },
    {
        'module_id': 'recruitment',
        'name': 'Recruitment & Hiring',
        'tagline': 'From job post to first day.',
        'description': 'Post jobs, collect applications, schedule interviews, send offer letters, and onboard new hires.',
        'category': 'people',
        'icon': 'bi-person-plus',
        'is_free': False,
        'monthly_price_usd': '7.99',
        'applicable_to': ['all'],
        'display_order': 32,
        'url_namespace': 'recruitment',
    },
    {
        'module_id': 'training',
        'name': 'Employee Training',
        'tagline': 'Build skills, track progress.',
        'description': 'Create training courses, assign them to teams, track completion, and issue internal certificates.',
        'category': 'people',
        'icon': 'bi-mortarboard',
        'is_free': False,
        'monthly_price_usd': '5.99',
        'applicable_to': ['all'],
        'display_order': 33,
        'url_namespace': 'training',
    },

    # ── Sales & CRM ──────────────────────────────────────────────────────────
    {
        'module_id': 'crm',
        'name': 'CRM — Customer Relations',
        'tagline': 'Know every customer, close every deal.',
        'description': 'Contact management, deal pipelines, interaction history, customer segments, and loyalty tracking.',
        'category': 'sales',
        'icon': 'bi-postcard-heart',
        'is_free': False,
        'monthly_price_usd': '9.99',
        'applicable_to': ['all'],
        'display_order': 40,
        'url_namespace': 'crm',
    },
    {
        'module_id': 'leads',
        'name': 'Lead Management',
        'tagline': 'Capture, score, and convert leads.',
        'description': 'Lead capture forms, scoring, assignment rules, follow-up reminders, and conversion funnels.',
        'category': 'sales',
        'icon': 'bi-funnel',
        'is_free': False,
        'monthly_price_usd': '5.99',
        'applicable_to': ['all'],
        'requires_modules': ['crm'],
        'display_order': 41,
        'url_namespace': 'leads',
    },
    {
        'module_id': 'ecommerce',
        'name': 'E-Commerce Store',
        'tagline': 'Sell online, integrated with your backoffice.',
        'description': 'Product catalogue, shopping cart, checkout, online payments, and order management synced with inventory.',
        'category': 'sales',
        'icon': 'bi-shop-window',
        'is_free': False,
        'monthly_price_usd': '14.99',
        'applicable_to': ['shop', 'retail_chain', 'wholesale', 'factory', 'business', 'warehouse', 'agency', 'other'],
        'requires_modules': ['inventory'],
        'display_order': 42,
        'is_coming_soon': True,
    },
    {
        'module_id': 'loyalty',
        'name': 'Loyalty & Rewards',
        'tagline': 'Keep customers coming back.',
        'description': 'Points system, reward tiers, stamp cards, birthday perks, and bulk SMS/email campaigns.',
        'category': 'sales',
        'icon': 'bi-award',
        'is_free': False,
        'monthly_price_usd': '7.99',
        'applicable_to': ['shop', 'retail_chain', 'restaurant', 'hotel', 'station', 'other'],
        'requires_modules': ['crm'],
        'display_order': 43,
        'url_namespace': 'loyalty',
    },

    # ── Call Center ───────────────────────────────────────────────────────────
    {
        'module_id': 'call_center',
        'name': 'Call Center',
        'tagline': 'Inbound queues, IVR, agent console & live wallboard.',
        'description': 'Full call center suite — Twilio-powered inbound/outbound calls, IVR builder, call queues, real-time supervisor wallboard, agent softphone, call recording, and CRM screen-pop.',
        'category': 'communication',
        'icon': 'bi-telephone-fill',
        'is_free': False,
        'monthly_price_usd': '29.99',
        'applicable_to': ['business', 'agency', 'clinic', 'hotel', 'shop', 'retail_chain', 'consulting', 'other'],
        'display_order': 5,
        'url_namespace': 'call_center',
    },

    # ── Communication ─────────────────────────────────────────────────────────
    {
        'module_id': 'team_chat',
        'name': 'Internal Team Chat',
        'tagline': 'Channels, DMs, and file sharing — built in.',
        'description': 'Slack-style internal messaging with channels, direct messages, threads, and file attachments.',
        'category': 'communication',
        'icon': 'bi-chat-dots',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 50,
        'url_namespace': 'team_chat',
    },
    {
        'module_id': 'announcements',
        'name': 'Announcements Board',
        'tagline': 'Broadcast updates to your whole team instantly.',
        'description': 'Company-wide or team-specific announcements with read receipts and priority flags.',
        'category': 'communication',
        'icon': 'bi-megaphone',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 51,
        'url_namespace': 'announcements',
    },
    {
        'module_id': 'email_marketing',
        'name': 'Email Marketing',
        'tagline': 'Campaigns that convert, from your dashboard.',
        'description': 'Design email campaigns, manage subscriber lists, schedule sends, and track opens/clicks.',
        'category': 'communication',
        'icon': 'bi-envelope-paper',
        'is_free': False,
        'monthly_price_usd': '9.99',
        'applicable_to': ['all'],
        'display_order': 52,
        'url_namespace': 'email_marketing',
    },

    # ── Production & Manufacturing ────────────────────────────────────────────
    {
        'module_id': 'production',
        'name': 'Production Planning',
        'tagline': 'Schedule, track, and deliver production runs.',
        'description': 'Work orders, production schedules, machine assignment, capacity planning, and WIP tracking.',
        'category': 'production',
        'icon': 'bi-building-gear',
        'is_free': False,
        'monthly_price_usd': '14.99',
        'applicable_to': ['factory'],
        'display_order': 60,
        'url_namespace': 'production',
    },
    {
        'module_id': 'bom',
        'name': 'Bill of Materials (BOM)',
        'tagline': 'Every product, every component, accounted for.',
        'description': 'Multi-level BOM management, component costing, BOM versioning, and production material requirements.',
        'category': 'production',
        'icon': 'bi-list-nested',
        'is_free': False,
        'monthly_price_usd': '9.99',
        'applicable_to': ['factory'],
        'requires_modules': ['inventory'],
        'display_order': 61,
        'url_namespace': 'bom',
    },
    {
        'module_id': 'quality_control',
        'name': 'Quality Control',
        'tagline': 'Defect tracking and inspection workflows.',
        'description': 'QC checklists, inspection records, defect logging, rejection reports, and supplier quality scorecards.',
        'category': 'production',
        'icon': 'bi-patch-check',
        'is_free': False,
        'monthly_price_usd': '9.99',
        'applicable_to': ['factory', 'warehouse'],
        'display_order': 62,
        'url_namespace': 'quality_control',
    },
    {
        'module_id': 'maintenance',
        'name': 'Equipment Maintenance',
        'tagline': 'Prevent breakdowns before they happen.',
        'description': 'Preventive maintenance schedules, breakdown logs, spare parts inventory, and maintenance cost tracking.',
        'category': 'production',
        'icon': 'bi-tools',
        'is_free': False,
        'monthly_price_usd': '7.99',
        'applicable_to': ['factory', 'warehouse', 'station'],
        'display_order': 63,
        'url_namespace': 'maintenance',
    },
    {
        'module_id': 'shift_planning',
        'name': 'Shift Planning',
        'tagline': 'Build and publish shift rosters in minutes.',
        'description': 'Drag-and-drop shift builder, auto-schedule by skills, shift swap requests, and overtime alerts.',
        'category': 'production',
        'icon': 'bi-calendar-week',
        'is_free': False,
        'monthly_price_usd': '5.99',
        'applicable_to': ['factory', 'restaurant', 'hotel', 'warehouse', 'station'],
        'requires_modules': ['hr'],
        'display_order': 64,
        'url_namespace': 'shift_planning',
    },

    # ── Analytics & Reports ───────────────────────────────────────────────────
    {
        'module_id': 'reports',
        'name': 'Reports & Analytics',
        'tagline': 'Data-driven decisions for every department.',
        'description': 'Pre-built and custom reports for sales, finance, HR, and operations. Export to PDF and Excel.',
        'category': 'analytics',
        'icon': 'bi-bar-chart-line',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 70,
        'url_namespace': 'reports',
    },
    {
        'module_id': 'dashboard_pro',
        'name': 'Advanced Dashboard',
        'tagline': 'Live KPI widgets and drill-down analytics.',
        'description': 'Customisable KPI dashboard, live data feeds, trend analysis, and multi-branch comparisons.',
        'category': 'analytics',
        'icon': 'bi-speedometer2',
        'is_free': False,
        'monthly_price_usd': '7.99',
        'applicable_to': ['all'],
        'display_order': 71,
        'url_namespace': 'dashboard_pro',
    },

    # ── Documents & Storage ───────────────────────────────────────────────────
    {
        'module_id': 'documents',
        'name': 'Document Management',
        'tagline': 'Upload, organise, and find any file instantly.',
        'description': 'Central file library with folders, tags, version history, and role-based access control.',
        'category': 'documents',
        'icon': 'bi-folder2-open',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 80,
        'url_namespace': 'documents',
    },
    {
        'module_id': 'contracts',
        'name': 'Contract Management',
        'tagline': 'Sign, store, and never miss a renewal.',
        'description': 'Contract templates, e-signature support, renewal reminders, and clause library.',
        'category': 'documents',
        'icon': 'bi-file-earmark-check',
        'is_free': False,
        'monthly_price_usd': '7.99',
        'applicable_to': ['all'],
        'display_order': 81,
        'url_namespace': 'contracts',
    },

    # ── AI & Automation ───────────────────────────────────────────────────────
    {
        'module_id': 'ai_assistant',
        'name': 'AI Business Assistant',
        'tagline': 'Your 24/7 AI employee, built for your business.',
        'description': 'Powered by Serea AI — handles customer queries, generates reports, monitors social media, and automates workflows.',
        'category': 'ai',
        'icon': 'bi-robot',
        'is_free': False,
        'monthly_price_usd': '19.99',
        'applicable_to': ['all'],
        'display_order': 90,
        'url_namespace': 'ai_assistant',
    },
    {
        'module_id': 'ai_analytics',
        'name': 'AI Analytics & Insights',
        'tagline': 'Let AI find the patterns you miss.',
        'description': 'AI-powered anomaly detection, sales forecasting, churn prediction, and natural language report queries.',
        'category': 'ai',
        'icon': 'bi-stars',
        'is_free': False,
        'monthly_price_usd': '14.99',
        'applicable_to': ['all'],
        'display_order': 91,
        'url_namespace': 'ai_analytics',
    },

    # ── Website & Marketing ───────────────────────────────────────────────────
    {
        'module_id': 'website',
        'name': 'Custom Website Builder',
        'tagline': 'Your business website, managed from your dashboard.',
        'description': 'Drag-and-drop website builder integrated with your dashboard. Products, menus, services, and booking auto-synced.',
        'category': 'web',
        'icon': 'bi-globe2',
        'is_free': False,
        'monthly_price_usd': '12.99',
        'applicable_to': ['all'],
        'display_order': 100,
        'url_namespace': 'website',
    },
    {
        'module_id': 'booking',
        'name': 'Online Booking System',
        'tagline': 'Let customers book 24/7.',
        'description': 'Service booking, appointment scheduling, calendar sync, reminder emails/SMS, and capacity limits.',
        'category': 'web',
        'icon': 'bi-calendar-check',
        'is_free': False,
        'monthly_price_usd': '7.99',
        'applicable_to': ['clinic', 'hotel', 'agency', 'school', 'restaurant', 'other'],
        'display_order': 101,
        'url_namespace': 'booking',
    },

    # ── Project Management ────────────────────────────────────────────────────
    {
        'module_id': 'projects',
        'name': 'Project Management',
        'tagline': 'Milestones, deadlines, and deliverables — clear.',
        'description': 'Projects, milestones, task assignments, Gantt charts, time tracking, and client portals.',
        'category': 'projects',
        'icon': 'bi-diagram-3',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 110,
        'url_namespace': 'projects',
    },
    {
        'module_id': 'task_board',
        'name': 'Task Boards (Kanban)',
        'tagline': 'Visual workflow boards for every team.',
        'description': 'Kanban boards, swimlanes, card assignments, due dates, checklists, and priority flags.',
        'category': 'projects',
        'icon': 'bi-kanban',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 111,
        'url_namespace': 'task_board',
    },

    # ── Factory Operations Hub ────────────────────────────────────────────────
    {
        'module_id': 'factory_ops',
        'name': 'Factory Operations Hub',
        'tagline': 'Full-factory ERP for footwear & garment manufacturers.',
        'description': 'End-to-end factory management: production orders, IE/SMV, quality control, buyers, commercial, AR/AP, banking & LCs, HR roster, approval workflows, and a live MIS executive dashboard.',
        'category': 'production',
        'icon': 'bi-buildings-fill',
        'is_free': False,
        'monthly_price_usd': '49.99',
        'applicable_to': ['factory', 'manufacturer', 'warehouse', 'other'],
        'display_order': 65,
        'url_namespace': 'factory_ops',
        'is_coming_soon': False,
    },

    # ── Manufacturing & Industrial ────────────────────────────────────────────
    {
        'module_id': 'erp',
        'name': 'Enterprise Resource Planning (ERP)',
        'tagline': 'Full ERP — ledger, vendors, POs, cost centers, budgets.',
        'description': 'Chart of accounts, double-entry journal entries, vendor management, purchase orders, cost centers, and budget vs actuals. Comparable to SAP S/4HANA, Oracle NetSuite, and Microsoft Dynamics 365.',
        'category': 'production',
        'icon': 'bi-building-fill-check',
        'is_free': False,
        'monthly_price_usd': '49.99',
        'applicable_to': ['factory', 'warehouse', 'business'],
        'display_order': 200,
        'url_namespace': 'erp',
    },
    {
        'module_id': 'mes',
        'name': 'Manufacturing Execution System (MES)',
        'tagline': 'Real-time production floor management and OEE tracking.',
        'description': 'Work center management, production orders, live progress logging, quality checks, downtime recording, and OEE snapshots. Comparable to Siemens Opcenter, Plex Smart Manufacturing, and MDCPlus.',
        'category': 'production',
        'icon': 'bi-gear-wide-connected',
        'is_free': False,
        'monthly_price_usd': '39.99',
        'applicable_to': ['factory'],
        'requires_modules': ['production'],
        'display_order': 201,
        'url_namespace': 'mes',
    },
    {
        'module_id': 'plm',
        'name': 'Product Lifecycle Management (PLM)',
        'tagline': 'Manage products from concept to end-of-life.',
        'description': 'Product registry with stage tracking, bills of materials, engineering change orders (ECO), document vault, and stage history. Comparable to Aras Innovator, Odoo PLM, and OpenPLM.',
        'category': 'production',
        'icon': 'bi-box-seam',
        'is_free': False,
        'monthly_price_usd': '29.99',
        'applicable_to': ['factory', 'business'],
        'display_order': 202,
        'url_namespace': 'plm',
    },
    {
        'module_id': 'cadcam',
        'name': 'CAD/CAM',
        'tagline': 'CAD/CAM project management and file vault.',
        'description': 'Manage design projects, upload and version CAD/CAM files (STEP, IGES, STL, DXF, G-code), and track project status. Full integration with Fusion 360, FreeCAD, and CAMotics coming soon.',
        'category': 'production',
        'icon': 'bi-grid-1x2',
        'is_free': False,
        'monthly_price_usd': '19.99',
        'applicable_to': ['factory'],
        'display_order': 203,
        'is_coming_soon': False,
        'url_namespace': 'cadcam',
    },
    {
        'module_id': 'asset_management',
        'name': 'Asset Management',
        'tagline': 'Track, maintain, and optimise your physical assets.',
        'description': 'Asset register with tagging, category-based depreciation, maintenance schedules, work orders, warranty tracking, and document storage. Comparable to AssetLoom and UpKeep.',
        'category': 'operations',
        'icon': 'bi-clipboard-data-fill',
        'is_free': False,
        'monthly_price_usd': '24.99',
        'applicable_to': ['factory', 'warehouse', 'business', 'station'],
        'display_order': 204,
        'url_namespace': 'asset_management',
    },

    # ── Logistics & Supply Chain ──────────────────────────────────────────────
    {
        'module_id': 'tms',
        'name': 'Transportation Management System (TMS)',
        'tagline': 'Carriers, routes, shipments, and freight quotes — in one hub.',
        'description': 'Full TMS for managing carriers, defining routes, tracking shipments end-to-end, recording tracking events, and generating freight quotes. Comparable to Oracle TMS, SAP TM, and MercuryGate.',
        'category': 'logistics',
        'icon': 'bi-truck-front-fill',
        'is_free': False,
        'monthly_price_usd': '29.99',
        'applicable_to': ['logistics', 'freight_forwarder', 'courier', 'warehouse', 'wholesale', 'factory', 'supply_chain_consulting', 'other'],
        'display_order': 400,
        'url_namespace': 'tms',
    },
    {
        'module_id': 'wms',
        'name': 'Warehouse Management System (WMS)',
        'tagline': 'Zones, bins, inbound receipts, and pick lists — all tracked.',
        'description': 'Manage warehouse zones and bins, record goods receipts (GRN) with expected vs. received variance tracking, create pick lists and dispatch orders. Comparable to Fishbowl WMS, Deposco, and SnapFulfil.',
        'category': 'logistics',
        'icon': 'bi-building',
        'is_free': False,
        'monthly_price_usd': '24.99',
        'applicable_to': ['logistics', 'warehouse', 'wholesale', 'retail_chain', 'freight_forwarder', 'factory', 'supply_chain_consulting', 'shop', 'other'],
        'display_order': 401,
        'url_namespace': 'wms',
    },

    # ── Consulting & Analytics ─────────────────────────────────────────────────
    {
        'module_id': 'data_studio',
        'name': 'Data Studio',
        'tagline': 'Import, analyse, and visualise your business data.',
        'description': 'Upload CSVs, build datasets manually, create bar/line/pie/scatter/pivot charts, pin key visuals to a dashboard, and assemble shareable reports. Comparable to Excel + Tableau for business intelligence.',
        'category': 'consulting',
        'icon': 'bi-bar-chart-line',
        'is_free': False,
        'monthly_price_usd': '19.99',
        'applicable_to': ['all'],
        'display_order': 500,
        'url_namespace': 'data_studio',
    },
    {
        'module_id': 'process_mapper',
        'name': 'Process Mapper',
        'tagline': 'Map, simulate, and optimise business processes.',
        'description': 'Build process maps with typed steps (task, decision, approval, etc.), define flow connections, run cycle-time simulations to find bottlenecks, attach documents, and manage process versioning and approval. Comparable to Microsoft Visio + Arena Simulation.',
        'category': 'consulting',
        'icon': 'bi-diagram-3',
        'is_free': False,
        'monthly_price_usd': '14.99',
        'applicable_to': ['all'],
        'display_order': 501,
        'url_namespace': 'process_mapper',
    },

    # ── Real Estate ───────────────────────────────────────────────────────────
    {
        'module_id': 'property_listings',
        'name': 'Property Listings & Showings',
        'tagline': 'Manage your property database, IDX links, tours, and showings.',
        'description': 'Full property listing management: residential and commercial, for sale or rent. Track status (Active/Under Contract/Sold), attach MLS numbers, IDX/portal URLs, virtual tour links (Matterport etc.), and schedule showings with feedback tracking. Comparable to Propertybase, Follow Up Boss listings, Zillow Premier.',
        'category': 'real_estate',
        'icon': 'bi-house-door',
        'is_free': False,
        'monthly_price_usd': '24.99',
        'applicable_to': ['real_estate_agency', 'real_estate_agent', 'other'],
        'display_order': 800,
        'url_namespace': 'property_listings',
    },
    {
        'module_id': 'deal_flow',
        'name': 'Deal Flow & Transaction Management',
        'tagline': 'Pipeline every deal from prospect to close.',
        'description': 'Track every real estate transaction through a full pipeline: Prospect → Offer → Under Contract → Inspection → Appraisal → Financing → Closing → Closed. Includes a document checklist (purchase agreement, disclosures, title, mortgage pre-approval), broker review workflow, deal notes, and milestone tracking. Comparable to dotloop, SkySlope, Brokermint.',
        'category': 'real_estate',
        'icon': 'bi-kanban',
        'is_free': False,
        'monthly_price_usd': '29.99',
        'applicable_to': ['real_estate_agency', 'real_estate_agent', 'other'],
        'display_order': 801,
        'url_namespace': 'deal_flow',
    },
    {
        'module_id': 'commission',
        'name': 'Commission Tracker',
        'tagline': 'Calculate splits, caps, and referral fees automatically.',
        'description': 'Track Gross Commission Income (GCI) per deal, auto-calculate agent/broker splits and referral fees, set annual commission caps, and manage payment status. Produce per-agent and per-period summaries. Comparable to Brokermint commission module, brokerWOLF, and QuickBooks commission tracking.',
        'category': 'real_estate',
        'icon': 'bi-cash-coin',
        'is_free': False,
        'monthly_price_usd': '19.99',
        'applicable_to': ['real_estate_agency', 'other'],
        'display_order': 802,
        'url_namespace': 'commission',
    },
    {
        'module_id': 're_marketing',
        'name': 'Real Estate Marketing',
        'tagline': 'Flyers, drip campaigns, and social posts — all in one place.',
        'description': 'Generate listing flyers (Just Listed, Open House, Just Sold templates) with auto-populated property data. Build drip email/SMS campaigns for buyers, sellers, and investors. Queue "Just Listed" and "Just Sold" social posts for Facebook and Instagram. Comparable to Listings-to-Leads, BombBomb, kvCORE marketing.',
        'category': 'real_estate',
        'icon': 'bi-megaphone',
        'is_free': False,
        'monthly_price_usd': '14.99',
        'applicable_to': ['real_estate_agency', 'real_estate_agent', 'other'],
        'display_order': 803,
        'url_namespace': 're_marketing',
    },
    {
        'module_id': 're_client_portal',
        'name': 'Client Portal (Real Estate)',
        'tagline': 'Secure private area for buyers and sellers to upload docs and track progress.',
        'description': 'Invite buyers or sellers to a private, token-secured portal. Share contracts, disclosures, and inspection reports. Track document signing status and collect client-uploaded financial documents. Comparable to the secure client portals in Dotloop, Glide, and SkySlope.',
        'category': 'real_estate',
        'icon': 'bi-shield-lock',
        'is_free': False,
        'monthly_price_usd': '9.99',
        'applicable_to': ['real_estate_agency', 'real_estate_agent', 'other'],
        'display_order': 804,
        'url_namespace': 're_client_portal',
    },

    # ── Retail & Wholesale ─────────────────────────────────────────────────────
    {
        'module_id': 'omnichannel',
        'name': 'Omnichannel Sales Hub',
        'tagline': 'Unify your online and offline channels in one place.',
        'description': 'Connect your physical POS, website, Shopify, WooCommerce, Amazon, eBay, TikTok Shop, and other channels. Manage unified product listings, track per-channel stock, and log sync events. Comparable to Linnworks, Brightpearl, and Vend Omnichannel.',
        'category': 'retail',
        'icon': 'bi-diagram-2',
        'is_free': False,
        'monthly_price_usd': '19.99',
        'applicable_to': ['shop', 'retail_chain', 'wholesale', 'factory', 'other'],
        'display_order': 700,
        'url_namespace': 'omnichannel',
    },
    {
        'module_id': 'planogram',
        'name': 'Planogram & Space Planning',
        'tagline': 'Map your shelf layouts and automate reorder alerts.',
        'description': 'Define store layouts, assign products to shelf positions with facing counts, set minimum stock thresholds, and get automatic reorder alerts when stock drops below the min. Comparable to JDA Space Planning, DotActiv, and Leafio Shelf Efficiency.',
        'category': 'retail',
        'icon': 'bi-grid-3x2-gap',
        'is_free': False,
        'monthly_price_usd': '14.99',
        'applicable_to': ['shop', 'retail_chain', 'wholesale', 'other'],
        'display_order': 701,
        'url_namespace': 'planogram',
    },
    {
        'module_id': 'product_catalog',
        'name': 'Digital Product Catalog',
        'tagline': 'Create and share professional digital catalogs.',
        'description': 'Build shareable digital product catalogs organised by category. Include product name, SKU, description, price, unit, and featured status. Share publicly via a secure link — no login required for buyers. Comparable to Catalog Machine, BlueCart, and NuORDER.',
        'category': 'retail',
        'icon': 'bi-journal-richtext',
        'is_free': False,
        'monthly_price_usd': '9.99',
        'applicable_to': ['shop', 'retail_chain', 'wholesale', 'factory', 'agency', 'other'],
        'display_order': 702,
        'url_namespace': 'product_catalog',
    },
    {
        'module_id': 'b2b_portal',
        'name': 'B2B Wholesale Portal',
        'tagline': 'Manage wholesale accounts, price tiers, and bulk orders.',
        'description': 'Maintain a database of B2B customers with price tiers (Standard / Silver / Gold / Platinum), credit limits, and outstanding balances. Create and track wholesale orders with line-item detail and status flow from Draft through to Delivered. Comparable to Handshake (Shopify B2B), NuORDER, and OrderEase.',
        'category': 'wholesale',
        'icon': 'bi-buildings',
        'is_free': False,
        'monthly_price_usd': '24.99',
        'applicable_to': ['wholesale', 'shop', 'retail_chain', 'factory', 'other'],
        'display_order': 703,
        'url_namespace': 'b2b_portal',
    },
    {
        'module_id': 'store_ops',
        'name': 'Retail Store Operations',
        'tagline': 'Manage multiple locations from one central dashboard.',
        'description': 'Add and manage multiple retail store locations, submit and review daily sales reports per location, assign store tasks with priority levels and due dates, and get a consolidated view of all stores in one dashboard. Comparable to iVend Retail, STORIS, and Epicor Eagle.',
        'category': 'retail',
        'icon': 'bi-shop',
        'is_free': False,
        'monthly_price_usd': '19.99',
        'applicable_to': ['retail_chain', 'shop', 'wholesale', 'other'],
        'display_order': 704,
        'url_namespace': 'store_ops',
    },

    # ── Education ─────────────────────────────────────────────────────────────
    {
        'module_id': 'sis',
        'name': 'Student Information System (SIS)',
        'tagline': 'Enrol students, track grades, and manage records.',
        'description': 'Centralised student records: enrolment, class groups, grade tracking per subject and term, attendance logging (present/absent/late/excused), parent/guardian contacts, and status management. Comparable to Infinite Campus, OpenEduCat.',
        'category': 'education',
        'icon': 'bi-person-badge',
        'is_free': False,
        'monthly_price_usd': '19.99',
        'applicable_to': ['school', 'training_center', 'university', 'tutoring_center', 'other'],
        'display_order': 600,
        'url_namespace': 'sis',
    },
    {
        'module_id': 'lms',
        'name': 'Learning Management System (LMS)',
        'tagline': 'Create courses, deliver content, track progress.',
        'description': 'Build and publish courses with modules and lessons (text, video, file, link, quiz). Learner enrolment with progress tracking, completion certificates, and self-paced or instructor-led delivery. Comparable to Canvas, Blackboard, Moodle, iSpring LMS.',
        'category': 'education',
        'icon': 'bi-mortarboard',
        'is_free': False,
        'monthly_price_usd': '24.99',
        'applicable_to': ['school', 'training_center', 'university', 'tutoring_center', 'corporate_training', 'other'],
        'display_order': 601,
        'url_namespace': 'lms',
    },
    {
        'module_id': 'assessments',
        'name': 'Assessments & Quizzes',
        'tagline': 'Build quizzes, auto-grade, and review results.',
        'description': 'Create multiple-choice, true/false, short-answer, and essay quizzes with configurable time limits, retry rules, and pass thresholds. Auto-grades objective questions; shows per-question explanations after submission. Comparable to Quizlet, iSpring Suite.',
        'category': 'education',
        'icon': 'bi-patch-check',
        'is_free': False,
        'monthly_price_usd': '14.99',
        'applicable_to': ['school', 'training_center', 'university', 'tutoring_center', 'corporate_training', 'other'],
        'display_order': 602,
        'url_namespace': 'assessments',
    },
    {
        'module_id': 'timetable',
        'name': 'Timetable & Rooms',
        'tagline': 'Weekly schedules, time slots, and room allocation.',
        'description': 'Define time slots, allocate rooms and instructors, and build a weekly class timetable with exception management. Visual weekly grid view with class-group filtering. Comparable to Kinderpedia scheduling, FET, OpenEduCat.',
        'category': 'education',
        'icon': 'bi-calendar-week',
        'is_free': False,
        'monthly_price_usd': '12.99',
        'applicable_to': ['school', 'training_center', 'university', 'tutoring_center', 'other'],
        'display_order': 603,
        'url_namespace': 'timetable',
    },
    {
        'module_id': 'parent_portal',
        'name': 'Parent & Student Portal',
        'tagline': 'Share reports and communicate with families.',
        'description': 'Generate and share progress reports (with shareable public links — no login required for parents), log parent/guardian messages, and post school announcements with pinning and audience targeting. Comparable to Kinderpedia, Seesaw.',
        'category': 'education',
        'icon': 'bi-house-heart',
        'is_free': False,
        'monthly_price_usd': '9.99',
        'applicable_to': ['school', 'training_center', 'university', 'tutoring_center', 'other'],
        'display_order': 604,
        'url_namespace': 'parent_portal',
    },

    # ── Automotive ────────────────────────────────────────────────────────────
    {
        'module_id': 'workshop',
        'name': 'Workshop & Garage Management',
        'tagline': 'Job cards, mechanics, service history, and invoicing.',
        'description': 'Full workshop management system: job cards, mechanic assignments, service bays, parts/labour billing, vehicle history, and customer notifications. Comparable to ARI, Bdtask, and GCTLinfosys.',
        'category': 'automotive',
        'icon': 'bi-tools',
        'is_free': False,
        'monthly_price_usd': '19.99',
        'applicable_to': ['garage', 'dealership', 'auto_supplier', 'other'],
        'display_order': 300,
        'url_namespace': 'workshop',
    },
    {
        'module_id': 'dms',
        'name': 'Dealer Management System (DMS)',
        'tagline': 'Vehicle stock, sales pipeline, and customer CRM.',
        'description': 'Manage your vehicle inventory, handle the complete deal lifecycle from enquiry to delivery, track trade-ins, manage finance options, and log salesperson activity. Comparable to MySoftHeaven DMS.',
        'category': 'automotive',
        'icon': 'bi-car-front-fill',
        'is_free': False,
        'monthly_price_usd': '29.99',
        'applicable_to': ['dealership', 'auto_parts', 'other'],
        'display_order': 301,
        'url_namespace': 'dms',
    },
    {
        'module_id': 'dvi',
        'name': 'Digital Vehicle Inspection (DVI)',
        'tagline': 'Tablet-based vehicle condition recording with shareable reports.',
        'description': '39-point standard inspection checklist, custom templates, per-checkpoint pass/advisory/fail status, photo uploads, and a shareable public report link for customers. Fully digital — no paper forms.',
        'category': 'automotive',
        'icon': 'bi-clipboard2-check',
        'is_free': False,
        'monthly_price_usd': '12.99',
        'applicable_to': ['garage', 'dealership', 'auto_supplier', 'other'],
        'display_order': 302,
        'url_namespace': 'dvi',
    },

    # ── Travel & Accommodation ────────────────────────────────────────────────
    {
        'module_id': 'pms',
        'name': 'Property Management System (PMS)',
        'tagline': 'Front desk, reservations, rooms, and folios — all in one.',
        'description': 'Full hotel PMS: room type management, real-time room status (available/occupied/dirty/maintenance), guest profiles, reservations with automated folio charging, check-in/check-out workflow, and daily housekeeping task scheduling. Comparable to Cloudbeds, Little Hotelier, and Opera PMS.',
        'category': 'travel',
        'icon': 'bi-building-check',
        'is_free': False,
        'monthly_price_usd': '39.99',
        'applicable_to': ['hotel', 'resort', 'hostel', 'other'],
        'display_order': 800,
        'url_namespace': 'pms',
    },
    {
        'module_id': 'channel_manager',
        'name': 'Channel Manager & GDS',
        'tagline': 'Sync rates and availability across all your OTA and GDS channels.',
        'description': 'Connect and manage distribution channels (Booking.com, Expedia, Airbnb, GDS). Configure rate plans with meal plan options (RO/BB/HB/FB/AI), push live availability blocks per room type and date, and log all sync activity. Comparable to SiteMinder, RateGain, and TravelClick.',
        'category': 'travel',
        'icon': 'bi-diagram-2',
        'is_free': False,
        'monthly_price_usd': '29.99',
        'applicable_to': ['hotel', 'resort', 'hostel', 'ota', 'travel_agency', 'other'],
        'display_order': 801,
        'url_namespace': 'channel_manager',
    },
    {
        'module_id': 'rate_manager',
        'name': 'Revenue & Rate Management',
        'tagline': 'Dynamic pricing, yield rules, seasons, and special offers.',
        'description': 'Define seasonal pricing multipliers (peak/high/shoulder/low), set room base rates with validity windows, build yield automation rules (occupancy-based, advance-booking, day-of-week), create rate restrictions (min stay, closed-to-arrival), and manage promotional offers. Comparable to IDeaS, Duetto, and Atomize.',
        'category': 'travel',
        'icon': 'bi-graph-up-arrow',
        'is_free': False,
        'monthly_price_usd': '24.99',
        'applicable_to': ['hotel', 'resort', 'hostel', 'ota', 'other'],
        'display_order': 802,
        'url_namespace': 'rate_manager',
    },
    {
        'module_id': 'travel_crm',
        'name': 'Travel CRM & Itinerary Builder',
        'tagline': 'Client profiles, trip itineraries, and booking history for travel advisors.',
        'description': 'Manage a full database of travel clients (preferences, passport details, frequent flyer numbers), build day-by-day itineraries with flight/hotel/activity/transfer items, and track all booking references with commission tracking. Comparable to Travelport Locomote, TravelJoy, and Rezdy.',
        'category': 'travel',
        'icon': 'bi-map',
        'is_free': False,
        'monthly_price_usd': '19.99',
        'applicable_to': ['travel_agency', 'tour_operator', 'corporate_travel', 'other'],
        'display_order': 803,
        'url_namespace': 'travel_crm',
    },
    {
        'module_id': 'group_bookings',
        'name': 'Group Bookings Manager',
        'tagline': 'RFPs, block allocation, rooming lists, and group contracts.',
        'description': 'Handle the full group booking lifecycle: receive and manage RFPs (weddings, conferences, sports), allocate room blocks per type, build guest rooming lists with room assignment, and generate group contracts with deposit tracking, attrition clauses, and cancellation policy. Comparable to Delphi by Amadeus, Tripleseat, and Groups360.',
        'category': 'travel',
        'icon': 'bi-people-fill',
        'is_free': False,
        'monthly_price_usd': '24.99',
        'applicable_to': ['hotel', 'resort', 'travel_agency', 'tour_operator', 'corporate_travel', 'other'],
        'display_order': 804,
        'url_namespace': 'group_bookings',
    },
    {
        'module_id': 'travel_desk',
        'name': 'Corporate Travel Desk',
        'tagline': 'Business travel management, policies, approvals, and expense control.',
        'description': 'Manage corporate accounts with credit limits and travel policies, handle employee travel requests with multi-level approval workflows, enforce per-diems and booking-class restrictions, track actual vs estimated costs, and manage expense receipts per trip. Comparable to SAP Concur, TravelBank, and TripActions.',
        'category': 'travel',
        'icon': 'bi-briefcase',
        'is_free': False,
        'monthly_price_usd': '19.99',
        'applicable_to': ['corporate_travel', 'travel_agency', 'business', 'agency', 'other'],
        'display_order': 805,
        'url_namespace': 'travel_desk',
    },
    {
        'module_id': 'hospitality_ops',
        'name': 'Hospitality Operations',
        'tagline': 'Housekeeping, maintenance, service requests, and concierge.',
        'description': 'Day-to-day hotel operations in one place: schedule and track housekeeping tasks by room with priority and status, manage maintenance tickets from report to resolution with cost tracking, handle guest service requests (room service, laundry, transport), and log concierge notes including VIP alerts and preferences. Comparable to HotSOS, Alice by ALICE Technologies, and Quore.',
        'category': 'travel',
        'icon': 'bi-stars',
        'is_free': False,
        'monthly_price_usd': '19.99',
        'applicable_to': ['hotel', 'resort', 'hostel', 'other'],
        'display_order': 806,
        'url_namespace': 'hospitality_ops',
    },

    # ── Personal Care ─────────────────────────────────────────────────────────
    {
        'module_id': 'care_manager',
        'name': 'Care Management',
        'tagline': 'Client care plans, staff rota, sessions, and compliance records.',
        'description': 'Manage care clients with detailed profiles, care levels, medical notes, and dietary requirements. Create and track care plans by type (personal, medical, social, dietary) with assigned staff and review dates. Log care sessions with duration and outcomes. Schedule staff rotas with shift confirmation. Store compliance documents including policies, certificates, risk assessments, and incident reports — reducing paperwork and improving care quality. Comparable to Care Vision, Nourish, and Person Centred Software.',
        'category': 'personal_care',
        'icon': 'bi-heart-pulse',
        'is_free': False,
        'monthly_price_usd': '24.99',
        'applicable_to': ['care_home', 'salon', 'spa', 'personal_trainer', 'clinic', 'other'],
        'display_order': 850,
        'url_namespace': 'care_manager',
    },

    # ── Home & Garden ─────────────────────────────────────────────────────────
    {
        'module_id': 'garden_ops',
        'name': 'Garden Management',
        'tagline': 'Client sites, job scheduling, crew assignment, and plant/tool stock.',
        'description': 'Organise client sites by type and area with contact details and assigned crew. Schedule and track garden jobs from mowing and planting to landscaping design, assign employees, and compare estimated vs actual hours and costs. Manage plant, tool, chemical, and material inventory with low-stock alerts. Ideal for landscaping companies, garden maintenance contractors, nurseries, and horticultural businesses. Comparable to Jobber, LMN, and Aspire Software.',
        'category': 'home_garden',
        'icon': 'bi-tree',
        'is_free': False,
        'monthly_price_usd': '19.99',
        'applicable_to': ['landscaping', 'nursery', 'florist', 'other'],
        'display_order': 860,
        'url_namespace': 'garden_ops',
    },

    # ── Field Service Management ──────────────────────────────────────────────
    {
        'module_id': 'fsm',
        'name': 'Field Service Management',
        'tagline': 'Map-based dispatch, job quoting, and mobile signature capture.',
        'description': 'A dedicated module for plumbers, carpenters, electricians, and HVAC. Features map-based dispatch, job quoting, parts inventory van-sync, and customer signature capture on mobile.',
        'category': 'operations',
        'icon': 'bi-truck-flatbed',
        'is_free': False,
        'monthly_price_usd': '29.99',
        'applicable_to': ['plumber', 'carpenter', 'electrician', 'landscaping', 'other'],
        'display_order': 865,
        'url_namespace': 'fsm',
    },

    # ── Data Collection ───────────────────────────────────────────────────────
    {
        'module_id': 'data_collection',
        'name': 'Data Collection & Forms',
        'tagline': 'Build surveys, polls, and intake forms to capture customer insights.',
        'description': 'Create custom forms with multiple field types — text, dropdowns, ratings, checkboxes, and yes/no — for surveys, polls, client intake, inspections, or feedback. Share forms publicly and track all submissions in one place. Reduces administrative paperwork so professionals can focus on core services. Useful across every department and business type. Comparable to Data Craft, Google Forms, and Typeform.',
        'category': 'general',
        'icon': 'bi-clipboard-data',
        'is_free': False,
        'monthly_price_usd': '14.99',
        'applicable_to': ['all'],
        'display_order': 870,
        'url_namespace': 'data_collection',
    },

    # ── Creation Suite ────────────────────────────────────────────────────────
    {
        'module_id': 'docs',
        'name': 'Collaborative Documents',
        'tagline': 'Write, share, and collaborate on business documents.',
        'description': 'Rich-text business documents with version history, sharing, and team collaboration.',
        'category': 'documents',
        'icon': 'bi-file-earmark-richtext',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 82,
        'url_namespace': 'docs',
    },
    {
        'module_id': 'sheets',
        'name': 'Spreadsheets',
        'tagline': 'Business spreadsheets built into your hub.',
        'description': 'Create and manage spreadsheets for budgets, planning, and data tracking — shared with your team.',
        'category': 'documents',
        'icon': 'bi-table',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 83,
        'url_namespace': 'sheets',
    },
    {
        'module_id': 'slides',
        'name': 'Presentations',
        'tagline': 'Create and deliver presentations from your dashboard.',
        'description': 'Build slide decks for client presentations, training, and internal briefings.',
        'category': 'documents',
        'icon': 'bi-easel',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 84,
        'url_namespace': 'slides',
    },
    {
        'module_id': 'forms_builder',
        'name': 'Form Builder',
        'tagline': 'Build and publish forms with a public submission link.',
        'description': 'Drag-and-drop form builder for surveys, registrations, and intake forms. Public submissions at /f/<slug>/ — no login required.',
        'category': 'documents',
        'icon': 'bi-ui-checks',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 85,
        'url_namespace': 'forms_builder',
    },

    # ── Communication & Productivity ──────────────────────────────────────────
    {
        'module_id': 'business_mail',
        'name': 'Business Mail',
        'tagline': 'Unified mailbox for your whole team.',
        'description': 'Team email inbox, compose, send, and manage business correspondence within your hub.',
        'category': 'communication',
        'icon': 'bi-envelope-at',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 53,
        'url_namespace': 'business_mail',
    },
    {
        'module_id': 'video_meet',
        'name': 'Video Meetings',
        'tagline': 'Schedule and host video meetings from your dashboard.',
        'description': 'Create meeting rooms, schedule sessions, and collaborate with your team via video.',
        'category': 'communication',
        'icon': 'bi-camera-video',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 54,
        'url_namespace': 'video_meet',
    },
    {
        'module_id': 'cloud_drive',
        'name': 'Cloud Drive',
        'tagline': 'Secure file storage tied to your business quota.',
        'description': 'Upload, organise, and share files with your team. Storage usage tracks against your plan quota.',
        'category': 'documents',
        'icon': 'bi-cloud-arrow-up',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 81,
        'url_namespace': 'cloud_drive',
    },
    {
        'module_id': 'business_calendar',
        'name': 'Business Calendar',
        'tagline': 'Shared calendar for your team — events, deadlines, and meetings.',
        'description': 'Company-wide and team-specific calendars, event creation, and scheduling.',
        'category': 'communication',
        'icon': 'bi-calendar3',
        'is_free': True,
        'monthly_price_usd': '0.00',
        'applicable_to': ['all'],
        'display_order': 55,
        'url_namespace': 'business_calendar',
    },

    # ── Finance (supplementary) ───────────────────────────────────────────────
    {
        'module_id': 'financials',
        'name': 'Financial Statements',
        'tagline': 'P&L, balance sheet, and management accounts.',
        'description': 'Generate and export financial statements, submit expense reports, and get a consolidated financial dashboard.',
        'category': 'finance',
        'icon': 'bi-file-earmark-bar-graph',
        'is_free': False,
        'monthly_price_usd': '9.99',
        'applicable_to': ['all'],
        'display_order': 25,
        'url_namespace': 'financials',
    },

    # ── Enterprise IT & Infrastructure ─────────────────────────────────────────
    {
        'module_id': 'ai_ops',
        'name': 'AIOps & System Stability',
        'tagline': 'Automated issue remediation and uptime maximization.',
        'description': 'AIOps for immediate system stability in high-volume transaction environments. Includes anomaly detection, automated root-cause analysis, and predictive scaling alerts.',
        'category': 'it',
        'icon': 'bi-activity',
        'is_free': False,
        'monthly_price_usd': '149.99',
        'applicable_to': ['fintech', 'healthcare', 'ecommerce', 'factory', 'business'],
        'display_order': 1000,
        'url_namespace': 'ai_ops',
    },
    {
        'module_id': 'neural_security',
        'name': 'Neural Security Grid',
        'tagline': 'Advanced fraud detection and stringent regulatory compliance.',
        'description': 'Neural Security Grid for compliance and advanced fraud detection. Features real-time transaction scanning, biometric integration, and AI-driven threat mitigation.',
        'category': 'it',
        'icon': 'bi-shield-lock-fill',
        'is_free': False,
        'monthly_price_usd': '299.99',
        'applicable_to': ['fintech', 'healthcare', 'business'],
        'display_order': 1001,
        'url_namespace': 'neural_security',
    },
    {
        'module_id': 'data_ecosystem',
        'name': 'Data Ecosystem Integration',
        'tagline': 'Seamless data sharing across complex ecosystems.',
        'description': 'Data Ecosystem Integration for seamless record sharing (including EHR/EMR pipelines). Ensures HIPAA and GDPR compliance with encrypted API gateways.',
        'category': 'it',
        'icon': 'bi-diagram-3-fill',
        'is_free': False,
        'monthly_price_usd': '199.99',
        'applicable_to': ['healthcare', 'fintech', 'factory', 'business'],
        'display_order': 1002,
        'url_namespace': 'data_ecosystem',
    },
    {
        'module_id': 'automation_bots',
        'name': 'Automation Bots (RPA)',
        'tagline': 'Streamline administrative and billing processes.',
        'description': 'Robotic Process Automation (RPA) Bots for streamlining repetitive tasks such as appointment scheduling, high-volume billing reconciliation, and data entry.',
        'category': 'ai',
        'icon': 'bi-robot',
        'is_free': False,
        'monthly_price_usd': '129.99',
        'applicable_to': ['healthcare', 'business', 'fintech'],
        'display_order': 1003,
        'url_namespace': 'automation_bots',
    },
    {
        'module_id': 'autonomous_ops',
        'name': 'Autonomous Operations',
        'tagline': 'Predictive maintenance to prevent machine failure.',
        'description': 'Autonomous Ops for predicting and preventing machine failure. Integrates with existing MES to schedule maintenance before downtime occurs.',
        'category': 'production',
        'icon': 'bi-gear-wide-connected',
        'is_free': False,
        'monthly_price_usd': '199.99',
        'applicable_to': ['factory', 'logistics', 'wholesale'],
        'display_order': 1004,
        'url_namespace': 'autonomous_ops',
    },
    {
        'module_id': 'iot_network',
        'name': 'IoT Network Architecture',
        'tagline': 'Optimizing high-velocity IoT sensor data flow.',
        'description': 'Network Architecture for optimizing IoT sensor data flow. Ingests massive volumes of telemetry data from factory floors or vehicle fleets in real-time.',
        'category': 'it',
        'icon': 'bi-router',
        'is_free': False,
        'monthly_price_usd': '149.99',
        'applicable_to': ['factory', 'logistics', 'wholesale'],
        'display_order': 1005,
        'url_namespace': 'iot_network',
    },
    {
        'module_id': 'cloud_infra',
        'name': 'Cloud Infrastructure (CCI)',
        'tagline': 'Auto-scaling cluster management for peak demand.',
        'description': 'Cloud Infrastructure (CCI) for auto-scaling during sales events and peak demand. Guarantee 99.999% uptime with dynamic load balancing.',
        'category': 'it',
        'icon': 'bi-cloud-check-fill',
        'is_free': False,
        'monthly_price_usd': '249.99',
        'applicable_to': ['ecommerce', 'shop', 'retail_chain', 'fintech'],
        'display_order': 1006,
        'url_namespace': 'cloud_infra',
    },
]


class Command(BaseCommand):
    help = 'Seed the ModuleCatalog with all planned business modules.'

    def handle(self, *args, **kwargs):
        created_count = 0
        updated_count = 0

        for data in ALL_MODULES:
            requires = data.pop('requires_modules', [])
            is_coming_soon = data.pop('is_coming_soon', False)

            obj, created = ModuleCatalog.objects.update_or_create(
                module_id=data['module_id'],
                defaults={
                    **data,
                    'requires_modules': requires,
                    'is_coming_soon': is_coming_soon,
                    'is_available': True,
                },
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f"  + Created: {obj.name}"))
            else:
                updated_count += 1
                self.stdout.write(f"  ~ Updated: {obj.name}")

        self.stdout.write(self.style.SUCCESS(
            f"\nDone. {created_count} created, {updated_count} updated. "
            f"Total modules: {ModuleCatalog.objects.count()}"
        ))
