# Generated by Django 4.2.28 on 2026-05-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('custom_website', 'Custom Website Build'), ('custom_webapp', 'Custom Web Application'), ('bengalbound_demo', 'BengalBound Demo'), ('ai_employee', 'AI Employee Consultation')], default='custom_website', max_length=100),
        ),
    ]
