# Generated by Django 4.2.28 on 2026-05-28 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('plumber', 'Plumber / HVAC'), ('dentist', 'Dentist / Clinic'), ('salon', 'Salon / Spa'), ('general', 'General Service')], default='general', max_length=20)),
                ('phone', models.CharField(help_text="Business's own phone number", max_length=30)),
                ('forwarding_number', models.CharField(blank=True, help_text='Number to transfer calls to when escalating', max_length=30)),
                ('twilio_phone_number', models.CharField(blank=True, help_text='Assigned Twilio number for this business', max_length=30)),
                ('agent_name', models.CharField(default='Aria', help_text="AI agent's display name", max_length=100)),
                ('tts_voice', models.CharField(default='en-US-Neural2-F', help_text='Google Cloud TTS voice ID', max_length=60)),
                ('greeting_template', models.TextField(default='Thank you for calling {business_name}. My name is {agent_name}. How can I help you today?')),
                ('closing_template', models.TextField(default="You're all set! We'll see you on {appointment_date}. Have a great day!")),
                ('business_hours', models.JSONField(blank=True, default=dict)),
                ('min_lead_time_hours', models.PositiveIntegerField(default=2, help_text='Minimum hours before a booking is allowed')),
                ('buffer_minutes', models.PositiveIntegerField(default=15, help_text='Buffer time between appointments')),
                ('calendar_type', models.CharField(choices=[('google', 'Google Calendar'), ('outlook', 'Microsoft Outlook'), ('apple', 'Apple iCloud'), ('acuity', 'Acuity Scheduling'), ('calendly', 'Calendly'), ('ical', 'Generic iCal Feed'), ('none', 'None / Manual')], default='none', max_length=20)),
                ('calendar_token', models.TextField(blank=True, help_text='Encrypted OAuth2 token JSON')),
                ('calendar_id', models.CharField(blank=True, help_text='Google Calendar ID or equivalent', max_length=255)),
                ('staff_list', models.JSONField(blank=True, default=list)),
                ('services_offered', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Profile',
                'verbose_name_plural': 'Business Profiles',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='SpamBlocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('source', models.CharField(default='community', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Spam Blocklist Entry',
                'verbose_name_plural': 'Spam Blocklist',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff (Read-Only)')], default='staff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voice_receptionist.businessprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='SpamLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caller_phone', models.CharField(db_index=True, max_length=30)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('detection_reason', models.CharField(max_length=500)),
                ('action_taken', models.CharField(choices=[('disconnected', 'Disconnected'), ('flagged', 'Flagged for Review'), ('allowed', 'Allowed Through')], default='flagged', max_length=20)),
                ('transcript_snippet', models.TextField(blank=True)),
                ('is_whitelisted', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spam_logs', to='voice_receptionist.businessprofile')),
            ],
            options={
                'verbose_name': 'Spam Log Entry',
                'verbose_name_plural': 'Spam Log',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_sid', models.CharField(db_index=True, help_text='Twilio Call SID', max_length=64, unique=True)),
                ('caller_phone', models.CharField(max_length=30)),
                ('caller_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('spam', 'Spam / Blocked'), ('transferred', 'Transferred to Human'), ('missed', 'Missed / After-Hours'), ('voicemail', 'Voicemail Left')], default='ongoing', max_length=20)),
                ('transcript', models.TextField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_after_hours', models.BooleanField(default=False)),
                ('escalated_to_human', models.BooleanField(default=False)),
                ('raw_twilio_data', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='voice_receptionist.businessprofile')),
            ],
            options={
                'verbose_name': 'Call',
                'verbose_name_plural': 'Call Log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caller_name', models.CharField(max_length=200)),
                ('caller_phone', models.CharField(max_length=30)),
                ('caller_email', models.EmailField(blank=True, max_length=254)),
                ('service_type', models.CharField(max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('pending', 'Pending Approval'), ('completed', 'Completed')], default='confirmed', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Plumber: on-site service address')),
                ('insurance_type', models.CharField(blank=True, help_text='Dental: insurance carrier', max_length=100)),
                ('preferred_staff', models.CharField(blank=True, help_text='Salon: preferred stylist/staff', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('gcal_event_id', models.CharField(blank=True, help_text='Google Calendar event ID', max_length=255)),
                ('calendar_synced', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recur_interval_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='voice_receptionist.businessprofile')),
                ('call', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='voice_receptionist.call')),
                ('parent_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrences', to='voice_receptionist.appointment')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('booking_confirmed', 'New Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_rescheduled', 'Booking Rescheduled'), ('reminder_24h', '24-Hour Reminder'), ('reminder_2h', '2-Hour Reminder'), ('missed_call', 'Missed Call'), ('weekly_report', 'Weekly Analytics Report')], max_length=40)),
                ('sms_template', models.TextField(blank=True)),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('email_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='voice_receptionist.businessprofile')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'unique_together': {('business', 'trigger_type')},
            },
        ),
    ]
