# Generated by Django 4.2.28 on 2026-05-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_receptionist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='language_code',
            field=models.CharField(default='en-US', help_text='BCP-47 language code for Speech-to-Text (e.g., es-ES, fr-FR)', max_length=20),
        ),
        migrations.AddField(
            model_name='call',
            name='english_transcript',
            field=models.TextField(blank=True, help_text='Auto-translated to English after call completion'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='tts_voice',
            field=models.CharField(default='en-US-Neural2-F', help_text='Twilio/Google Cloud TTS voice ID (e.g. Polly.Lupe, Google.es-ES-Neural2-A)', max_length=60),
        ),
    ]
