# Generated by Django 4.2.28 on 2026-03-06 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community_forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Forum Categories'},
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='icon',
            field=models.CharField(default='bi-chat-dots', help_text='Bootstrap icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='ai_flag_reason',
            field=models.TextField(blank=True, help_text='Reason Serea flagged this post'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='is_escalated',
            field=models.BooleanField(default=False, help_text='Escalated to Workspace Admin'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Serea flagged this post'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hidden from public view pending moderation'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='is_solved',
            field=models.BooleanField(default=False, help_text='For Questions — mark when answered'),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='topic_type',
            field=models.CharField(choices=[('question', 'Question'), ('article', 'Article'), ('problem', 'Problem Report')], default='question', max_length=20),
        ),
        migrations.CreateModel(
            name='ForumModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(default='Serea AI', max_length=100)),
                ('action', models.CharField(choices=[('ai_flag', 'AI Flagged'), ('ai_escalate', 'AI Escalated to Admin'), ('admin_hide', 'Admin Hid Post'), ('admin_restore', 'Admin Restored Post'), ('admin_lock', 'Admin Locked Topic'), ('admin_pin', 'Admin Pinned Topic'), ('admin_mark_solved', 'Admin Marked Solved')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='community_forum.forumpost')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='community_forum.forumtopic')),
            ],
        ),
    ]
