# Generated by Django 4.2.29 on 2026-03-14 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community_forum', '0002_phase8_topictype_ai_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community_forum.forumpost'),
        ),
    ]
