# Generated by Django 4.2.28 on 2026-04-29 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0005_alter_businessinstance_business_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('vehicle_make', models.CharField(max_length=60)),
                ('vehicle_model', models.CharField(blank=True, max_length=60)),
                ('vehicle_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vehicle_reg', models.CharField(blank=True, max_length=30)),
                ('vin', models.CharField(blank=True, max_length=50, verbose_name='VIN')),
                ('colour', models.CharField(blank=True, max_length=40)),
                ('mileage_in', models.PositiveIntegerField(blank=True, null=True)),
                ('mileage_out', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_level', models.CharField(blank=True, max_length=10)),
                ('service_type', models.CharField(choices=[('oil_change', 'Oil & Filter Change'), ('service_a', 'Service A (Minor)'), ('service_b', 'Service B (Major)'), ('diagnostics', 'Diagnostics'), ('repair', 'Repair'), ('tyres', 'Tyre Replacement'), ('brakes', 'Brake Service'), ('electrical', 'Electrical Fault'), ('ac', 'Air Conditioning'), ('body_work', 'Body Work'), ('pre_purchase', 'Pre-Purchase Inspection'), ('warranty', 'Warranty Repair'), ('recall', 'Recall / Campaign'), ('other', 'Other')], default='repair', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('diagnosing', 'Diagnosing'), ('in_progress', 'In Progress'), ('waiting_parts', 'Waiting for Parts'), ('waiting_approval', 'Waiting Customer Approval'), ('ready', 'Ready for Collection'), ('collected', 'Collected'), ('invoiced', 'Invoiced & Closed'), ('cancelled', 'Cancelled')], default='received', max_length=25)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('customer_complaint', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('work_done', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('customer_notified', models.BooleanField(default=False)),
                ('notification_method', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('call', 'Phone Call'), ('none', 'None')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('labour', 'Labour'), ('part', 'Part'), ('fluid', 'Fluid'), ('subcontract', 'Subcontract'), ('other', 'Other')], default='labour', max_length=15)),
                ('description', models.CharField(max_length=200)),
                ('part_number', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='workshop.jobcard')),
            ],
            options={
                'ordering': ['item_type', 'description'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('bay_type', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bays', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='JobStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=25)),
                ('new_status', models.CharField(max_length=25)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='workshop.jobcard')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='jobcard',
            name='bay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='workshop.servicebay'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cards', to='bredbound.businessinstance'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VehicleServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_reg', models.CharField(max_length=30)),
                ('vin', models.CharField(blank=True, max_length=50)),
                ('vehicle_make', models.CharField(max_length=60)),
                ('vehicle_model', models.CharField(blank=True, max_length=60)),
                ('vehicle_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_service_history', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['vehicle_reg'],
                'unique_together': {('business', 'vehicle_reg')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='jobcard',
            unique_together={('business', 'job_number')},
        ),
    ]
