# Generated by Django 4.2.28 on 2026-05-28 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial'), ('land', 'Land'), ('office', 'Office')], max_length=15)),
                ('listing_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('area_sqft', models.IntegerField()),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('ai_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('viewing', 'Viewing'), ('under_offer', 'Under Offer'), ('sold', 'Sold'), ('rented', 'Rented')], default='available', max_length=12)),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_set', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-listed_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('intent', models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], max_length=5)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('preferred_areas', models.JSONField(default=list)),
                ('bedrooms_needed', models.IntegerField(blank=True, null=True)),
                ('ai_score', models.IntegerField(blank=True, null=True)),
                ('ai_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('viewing_booked', 'Viewing Booked'), ('offer_made', 'Offer Made'), ('converted', 'Converted'), ('rejected', 'Rejected')], default='new', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realt_lead_set', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
