# Generated by Django 4.2.28 on 2026-04-28 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website_type', models.CharField(choices=[('landing', 'Landing Page'), ('business', 'Business Site'), ('ecommerce', 'eCommerce'), ('blog', 'Blog'), ('portfolio', 'Portfolio'), ('other', 'Other')], default='business', max_length=20)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('staging_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('live', 'Live'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('template_used', models.CharField(blank=True, max_length=100)),
                ('color_scheme', models.JSONField(blank=True, default=dict)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='website/favicons/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='website/logos/')),
                ('description', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True, max_length=500)),
                ('google_analytics_id', models.CharField(blank=True, max_length=30)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_websites', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_projects', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('font', 'Font'), ('other', 'Other')], default='image', max_length=20)),
                ('file', models.FileField(upload_to='website/assets/')),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='website.websiteproject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('blocks', models.JSONField(blank=True, default=list, help_text='Page builder blocks')),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True, max_length=500)),
                ('is_homepage', models.BooleanField(default=False)),
                ('in_navigation', models.BooleanField(default=True)),
                ('nav_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='website.websiteproject')),
            ],
            options={
                'ordering': ['nav_order', 'title'],
                'unique_together': {('project', 'slug')},
            },
        ),
    ]
