# Generated by Django 4.2.28 on 2026-04-29 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0007_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('student_ref', models.CharField(blank=True, max_length=50, verbose_name='Enrollment / Student ID')),
                ('class_group', models.CharField(blank=True, max_length=50)),
                ('period', models.CharField(max_length=50)),
                ('report_date', models.DateField()),
                ('overall_grade', models.CharField(blank=True, max_length=10)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('attendance_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher_comments', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='bredbound.businessinstance')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportSubjectLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('score', models.CharField(blank=True, max_length=20)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('teacher', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_lines', to='parent_portal.progressreport')),
            ],
            options={
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='ParentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=150)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('student_name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_messages', to='bredbound.businessinstance')),
                ('from_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_parent_messages', to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'All Parents'), ('class', 'Specific Class'), ('individual', 'Individual Student')], default='all', max_length=12)),
                ('class_group', models.CharField(blank=True, max_length=50)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_announcements', to='bredbound.businessinstance')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['-is_pinned', '-posted_at'],
            },
        ),
    ]
