# Generated by Django 4.2.28 on 2026-04-29 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0004_businessemployee_phone_alter_businessemployee_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=150)),
                ('product_code', models.CharField(blank=True, max_length=50)),
                ('quantity_planned', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_produced', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('released', 'Released'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_production_orders', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('maintenance', 'Under Maintenance'), ('offline', 'Offline')], default='idle', max_length=20)),
                ('capacity_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('machine_id', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_work_centers', to='bredbound.businessinstance')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('business', 'code')},
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.CharField(max_length=100)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional Pass')], max_length=20)),
                ('measured_value', models.CharField(blank=True, max_length=50)),
                ('acceptable_range', models.CharField(blank=True, max_length=50)),
                ('defect_description', models.TextField(blank=True)),
                ('inspected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('inspected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='mes.productionorder')),
            ],
            options={
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='mes.workcenter'),
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start', 'Started'), ('pause', 'Paused'), ('resume', 'Resumed'), ('complete', 'Completed'), ('scrap', 'Scrap Recorded'), ('note', 'Note Added')], max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mes.productionorder')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='DowntimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mechanical', 'Mechanical Failure'), ('electrical', 'Electrical Failure'), ('maintenance', 'Planned Maintenance'), ('material', 'Material Shortage'), ('operator', 'Operator Absence'), ('changeover', 'Changeover/Setup'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_records', to='mes.workcenter')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='productionorder',
            unique_together={('business', 'order_number')},
        ),
        migrations.CreateModel(
            name='OEESnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('availability', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('performance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quality', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('oee', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('planned_production_time', models.PositiveIntegerField(default=0)),
                ('actual_production_time', models.PositiveIntegerField(default=0)),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oee_snapshots', to='mes.workcenter')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'unique_together': {('work_center', 'snapshot_date')},
            },
        ),
    ]
