# Generated by Django 4.2.28 on 2026-05-06 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bredbound', '0011_alter_businessinstance_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_routings', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoutingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=10)),
                ('name', models.CharField(blank=True, help_text='Override work center name for this specific routing step', max_length=100)),
                ('is_bottleneck', models.BooleanField(default=False)),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='mes.routing')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_stations', to='mes.workcenter')),
            ],
            options={
                'ordering': ['routing', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='StationTrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_logs', to='mes.productionorder')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mes.routingstation')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entered_at'],
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='current_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_orders', to='mes.routingstation'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='routing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='mes.routing'),
        ),
    ]
