# Generated by Django 4.2.28 on 2026-05-06 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0002_asset_is_tooling_asset_lifespan_capacity_and_more'),
        ('mes', '0002_routing_routingstation_stationtrackinglog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationtrackinglog',
            name='assigned_machine',
            field=models.ForeignKey(blank=True, help_text='Specific machine assigned during this station step', null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_management.asset'),
        ),
    ]
