# Generated by Django 4.2.28 on 2026-05-06 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productlot_alter_stocklevel_unique_together_and_more'),
        ('mes', '0003_stationtrackinglog_assigned_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='output_lot',
            field=models.ForeignKey(blank=True, help_text='The batch/lot number generated by this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_production_orders', to='inventory.productlot'),
        ),
    ]
