# Generated by Django 4.2.28 on 2026-05-06 22:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bredbound', '0011_alter_businessinstance_business_type'),
        ('mes', '0004_productionorder_output_lot'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('assigned_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanners', to='mes.routingstation')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_scanners', to='bredbound.businessinstance')),
            ],
        ),
        migrations.CreateModel(
            name='ScannerEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('check_in', 'Check-In'), ('check_out', 'Check-Out'), ('error', 'Error')], max_length=20)),
                ('scanned_barcode', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mes.productionorder')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mes.hardwarescanner')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
