# Generated by Django 4.2.28 on 2026-05-18 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0011_alter_businessinstance_business_type'),
        ('mes', '0005_hardwarescanner_scannereventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootwearProductionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_code', models.CharField(blank=True, max_length=50)),
                ('buyer', models.CharField(blank=True, max_length=150)),
                ('footwear_type', models.CharField(choices=[('sneakers', 'Sneakers'), ('sandals', 'Sandals'), ('ladies_heels', 'Ladies Heels'), ('oxfords', 'Formal Oxfords'), ('loafers', 'Penny Loafers'), ('boots', 'Boots'), ('other', 'Other')], default='other', max_length=20)),
                ('total_pairs_planned', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footwear_schedules', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footwear_schedules_created', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footwear_schedules', to='mes.productionorder')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionDayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_label', models.CharField(help_text='e.g. D-3, D-2, 1, 2 … 12', max_length=10)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('pre_d3', 'D-3 Pre-Production'), ('pre_d2', 'D-2 Pre-Production'), ('pre_d1', 'D-1 Pre-Production'), ('cutting', 'Cutting'), ('closing', 'Closing / Sewing'), ('lasting', 'Lasting'), ('bottoming', 'Bottoming'), ('finishing', 'Finishing'), ('qc', 'Final QC'), ('packout', 'Pack-out')], max_length=15)),
                ('key_activities', models.TextField(blank=True)),
                ('daily_target', models.PositiveIntegerField(default=0)),
                ('actual_output', models.PositiveIntegerField(default=0)),
                ('cumulative_target', models.PositiveIntegerField(default=0)),
                ('cumulative_actual', models.PositiveIntegerField(default=0)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('bottleneck', models.TextField(blank=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_entries', to='mes.footwearproductionschedule')),
            ],
            options={
                'ordering': ['day_label'],
            },
        ),
    ]
