# Generated by Django 4.2.28 on 2026-05-01 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0011_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('site_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('site_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('public', 'Public / Council'), ('estate', 'Estate / HOA'), ('other', 'Other')], default='residential', max_length=20)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden_sites', to='bredbound.businessemployee')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_sites', to='bredbound.businessinstance')),
            ],
        ),
        migrations.CreateModel(
            name='GardenJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('mowing', 'Mowing / Lawn Care'), ('planting', 'Planting'), ('pruning', 'Pruning / Trimming'), ('landscaping', 'Landscaping Design'), ('irrigation', 'Irrigation'), ('weeding', 'Weeding'), ('maintenance', 'General Maintenance'), ('seasonal', 'Seasonal Clearance'), ('other', 'Other')], default='maintenance', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden_jobs', to='bredbound.businessemployee')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_jobs', to='bredbound.businessinstance')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_jobs', to='garden_ops.clientsite')),
            ],
        ),
        migrations.CreateModel(
            name='GardenInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('plant', 'Plant / Seed'), ('tool', 'Tool / Equipment'), ('chemical', 'Chemical / Fertiliser'), ('material', 'Material / Aggregate'), ('pot', 'Pot / Container'), ('other', 'Other')], default='plant', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='each', max_length=20)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('low_stock_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_inventory_items', to='bredbound.businessinstance')),
            ],
        ),
    ]
