# Generated by Django 4.2.28 on 2026-05-01 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0011_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('care_level', models.CharField(choices=[('independent', 'Independent'), ('assisted', 'Assisted'), ('full_care', 'Full Care'), ('specialist', 'Specialist Care')], default='assisted', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('discharged', 'Discharged'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('dietary_requirements', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_clients', to='bredbound.businessemployee')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_clients', to='bredbound.businessinstance')),
            ],
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('care_type', models.CharField(choices=[('personal', 'Personal Care'), ('medical', 'Medical'), ('social', 'Social / Activity'), ('dietary', 'Dietary'), ('mobility', 'Mobility & Exercise'), ('other', 'Other')], default='personal', max_length=20)),
                ('description', models.TextField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('twice_daily', 'Twice Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('as_needed', 'As Needed')], default='daily', max_length=20)),
                ('start_date', models.DateField()),
                ('review_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_care_plans', to='bredbound.businessemployee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='care_manager.careclient')),
            ],
        ),
        migrations.CreateModel(
            name='StaffRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('role', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_rota_entries', to='bredbound.businessinstance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_rota_entries', to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['shift_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('policy', 'Policy'), ('procedure', 'Procedure'), ('certificate', 'Certificate'), ('training_record', 'Training Record'), ('risk_assessment', 'Risk Assessment'), ('incident_report', 'Incident Report'), ('other', 'Other')], default='policy', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_docs_created', to='bredbound.businessemployee')),
            ],
        ),
        migrations.CreateModel(
            name='CareSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='care_manager.careplan')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_sessions', to='care_manager.careclient')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_sessions_performed', to='bredbound.businessemployee')),
            ],
        ),
    ]
