# Generated by Django 4.2.28 on 2026-04-30 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0008_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('pos', 'Physical POS / Store'), ('website', 'Own Website / E-Commerce'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('amazon', 'Amazon'), ('ebay', 'eBay'), ('tiktok', 'TikTok Shop'), ('instagram', 'Instagram Shop'), ('facebook', 'Facebook Marketplace'), ('b2b', 'B2B Portal'), ('other', 'Other')], default='other', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_channels', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ChannelSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('items_synced', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='omnichannel.saleschannel')),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='Internal SKU')),
                ('channel_sku', models.CharField(blank=True, max_length=100, verbose_name='Channel SKU')),
                ('listed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_qty', models.IntegerField(default=0)),
                ('is_synced', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_listings', to='bredbound.businessinstance')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='omnichannel.saleschannel')),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
    ]
