# Generated by Django 4.2.28 on 2026-05-28 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPitch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('business_summary', models.TextField(help_text='Context for the AI to generate the script')),
                ('target_audience', models.CharField(blank=True, help_text='e.g. Angel Investors, Enterprise B2B', max_length=255)),
                ('ai_script', models.TextField(blank=True, help_text='The spoken script generated by Gemini')),
                ('video_url', models.URLField(blank=True, help_text='The rendered MP4 URL from HeyGen/D-ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating_script', 'Generating Script'), ('rendering_video', 'Rendering Video'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('avatar_id', models.CharField(default='default_avatar', help_text='HeyGen/D-ID Avatar ID', max_length=100)),
                ('voice_id', models.CharField(default='en-US-Neural2-F', help_text='TTS Voice ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_pitches', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresentationSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.PositiveIntegerField()),
                ('image_url', models.URLField(blank=True, help_text='Screenshot of the slide for video overlay')),
                ('talking_points', models.TextField(blank=True, help_text='Specific points the AI must mention on this slide')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='pitch_presenter.videopitch')),
            ],
            options={
                'ordering': ['slide_number'],
                'unique_together': {('pitch', 'slide_number')},
            },
        ),
    ]
