# Generated by Django 4.2.28 on 2026-05-23 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bredbound', '0011_alter_businessinstance_business_type'),
        ('factory_ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Upper', 'Upper'), ('Sole', 'Sole'), ('Assembly', 'Assembly'), ('Accessory', 'Accessory'), ('Packaging', 'Packaging'), ('Other', 'Other')], default='Other', max_length=30)),
                ('uom', models.CharField(default='pairs', max_length=20)),
                ('on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('last_in_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fo_product_skus', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
