# Generated by Django 4.2.28 on 2026-05-23 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bredbound', '0011_alter_businessinstance_business_type'),
        ('factory_ops', '0002_productsku'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductionreport',
            name='downtime_cause',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dailyproductionreport',
            name='smv_per_pair',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='aql_level',
            field=models.CharField(choices=[('1.0', 'AQL 1.0'), ('2.5', 'AQL 2.5'), ('4.0', 'AQL 4.0'), ('6.5', 'AQL 6.5')], default='2.5', max_length=5),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='defect_severity',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], max_length=15),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='is_first_inspection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='lot_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reworkrecord',
            name='defect_severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], default='major', max_length=15),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='stage',
            field=models.CharField(choices=[('incoming', 'Incoming Material'), ('cutting', 'Cutting'), ('stitching', 'Stitching'), ('lasting', 'Lasting'), ('sole', 'Sole Bonding'), ('final', 'Final QC'), ('pack', 'Pre-Pack')], default='final', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkerAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_id', models.CharField(max_length=30)),
                ('employee_name', models.CharField(max_length=100)),
                ('emp_id_ref', models.CharField(blank=True, max_length=30)),
                ('date_issued', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purpose', models.CharField(max_length=200)),
                ('recovery_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_recovered', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('outstanding', 'Outstanding'), ('recovering', 'Recovering'), ('recovered', 'Fully Recovered')], default='outstanding', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fo_worker_advances', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_id', models.CharField(max_length=30)),
                ('txn_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('supplies', 'Office/Factory Supplies'), ('transport', 'Transport/Conveyance'), ('utilities', 'Utilities & Bills'), ('meals', 'Staff Meals'), ('maintenance', 'Repairs & Maintenance'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_to', models.CharField(blank=True, max_length=100)),
                ('receipt_ref', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fo_petty_cash', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-txn_date'],
            },
        ),
        migrations.CreateModel(
            name='HourlyProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('line', models.CharField(max_length=50)),
                ('hour_slot', models.CharField(max_length=10)),
                ('target', models.PositiveSmallIntegerField(default=0)),
                ('actual', models.PositiveSmallIntegerField(default=0)),
                ('root_cause', models.CharField(blank=True, max_length=200)),
                ('corrective_action', models.CharField(blank=True, max_length=200)),
                ('action_owner', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fo_hourly_entries', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['entry_date', 'line', 'hour_slot'],
                'unique_together': {('business', 'entry_date', 'line', 'hour_slot')},
            },
        ),
    ]
