# Generated by Django 4.2.28 on 2026-05-24 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bredbound', '0011_alter_businessinstance_business_type'),
        ('factory_ops', '0003_dailyproductionreport_downtime_cause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryinvoice',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='factory_ops/invoices/'),
        ),
        migrations.AddField(
            model_name='factorysop',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='factory_ops/sops/'),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='factory_ops/qc_reports/'),
        ),
        migrations.AddField(
            model_name='vendorpo',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='factory_ops/pos/'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('raw', 'Raw Material'), ('sku', 'Product SKU')], default='raw', max_length=5)),
                ('item_ref', models.CharField(help_text='item_id or sku_id of the related item', max_length=30)),
                ('item_name', models.CharField(max_length=200)),
                ('move_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out / Issue'), ('adjust', 'Manual Adjustment'), ('rework', 'Rework Write-off'), ('transfer', 'Transfer')], default='adjust', max_length=10)),
                ('qty_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty_change', models.DecimalField(decimal_places=2, default=0, help_text='Positive = increase, negative = decrease', max_digits=12)),
                ('qty_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='PO ref, issue ID, reason', max_length=100)),
                ('performed_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fo_stock_movements', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_assets', models.DecimalField(decimal_places=2, default=25000000, help_text='Plant, machinery & equipment value (BDT)', max_digits=16)),
                ('long_term_debt', models.DecimalField(decimal_places=2, default=15000000, help_text='Outstanding term loans (BDT)', max_digits=16)),
                ('interest_rate_pct', models.DecimalField(decimal_places=2, default=9.0, help_text='Annual interest rate on long-term debt (%)', max_digits=5)),
                ('tax_rate_pct', models.DecimalField(decimal_places=2, default=27.5, help_text='Effective corporate tax rate (%)', max_digits=5)),
                ('cogs_estimate_pct', models.DecimalField(decimal_places=2, default=68.0, help_text='COGS as % of revenue when FG cost data is unavailable', max_digits=5)),
                ('currency', models.CharField(default='BDT', max_length=5)),
                ('factory_address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='BIN / TIN / Tax ID')),
                ('bank_details', models.TextField(blank=True, help_text='Bank name, account, routing — shown on invoices')),
                ('working_hours_per_day', models.PositiveSmallIntegerField(default=8)),
                ('petty_cash_limit', models.DecimalField(decimal_places=2, default=5000, help_text='Auto-approve threshold (BDT)', max_digits=10)),
                ('manager_approval_limit', models.DecimalField(decimal_places=2, default=25000, help_text='Manager approval ceiling; above this → CEO approval', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fo_settings', to='bredbound.businessinstance')),
            ],
        ),
    ]
