# Generated by Django 4.2.28 on 2026-05-25 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bredbound', '0011_alter_businessinstance_business_type'),
        ('factory_ops', '0004_factoryinvoice_document_factorysop_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(max_length=30)),
                ('requested_by', models.CharField(blank=True, max_length=100, verbose_name='Merchandiser / Requester')),
                ('buyer_name', models.CharField(blank=True, max_length=100)),
                ('style_name', models.CharField(max_length=200)),
                ('style_ref', models.CharField(blank=True, max_length=50)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('sample_type', models.CharField(choices=[('proto', 'Proto Sample'), ('fit', 'Fit Sample'), ('pre_production', 'Pre-Production Sample'), ('production', 'Production Sample'), ('marketing', 'Marketing Sample')], default='proto', max_length=20)),
                ('priority', models.CharField(choices=[('standard', 'Standard'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='standard', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready_for_approval', 'Ready for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('shipped', 'Shipped')], default='pending', max_length=25)),
                ('last_number', models.CharField(blank=True, max_length=50)),
                ('last_type', models.CharField(blank=True, choices=[('flat', 'Flat'), ('heeled', 'Heeled'), ('platform', 'Platform'), ('custom', 'Custom')], max_length=15)),
                ('heel_height_mm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('toe_allowance_mm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heel_allowance_mm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ball_allowance_mm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('materials', models.JSONField(default=list)),
                ('thread_color', models.CharField(blank=True, max_length=100)),
                ('thread_count', models.CharField(blank=True, max_length=50)),
                ('adhesive_type', models.CharField(blank=True, max_length=100)),
                ('primer_required', models.BooleanField(default=False)),
                ('construction_type', models.CharField(choices=[('cement', 'Cement / Stuck-on'), ('goodyear', 'Goodyear Welt'), ('blake', 'Blake Stitch'), ('injection', 'Direct Injection'), ('vulcanize', 'Vulcanize'), ('string', 'String Lasting')], default='cement', max_length=20)),
                ('process_steps', models.JSONField(default=list, help_text='[{step_no, operation, machine, notes}]')),
                ('problems', models.JSONField(default=list, help_text='[{area, description}]')),
                ('special_instructions', models.JSONField(default=list)),
                ('assigned_to', models.CharField(blank=True, max_length=100, verbose_name='Designer / Sampleman')),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='factory_ops/sample_orders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fo_sample_orders', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveSmallIntegerField()),
                ('pairs_sold', models.PositiveIntegerField(default=0)),
                ('rate_per_pair', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('new_accounts', models.PositiveSmallIntegerField(default=0)),
                ('bonus_per_account', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('collection_achieved', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('collection_target', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('collection_bonus_rate', models.DecimalField(decimal_places=2, default=0, help_text='% of achieved collection paid as bonus (only if target met)', max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fo_sales_incentives', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-period_year', '-period_month', 'employee_name'],
            },
        ),
        migrations.CreateModel(
            name='KPITemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Production', 'Production'), ('Cutting', 'Cutting'), ('Stitching', 'Stitching'), ('Lasting', 'Lasting'), ('Finishing', 'Finishing'), ('Quality', 'Quality'), ('Commercial', 'Commercial'), ('Design', 'Design'), ('IE', 'Industrial Engineering'), ('Store', 'Store'), ('Admin', 'Admin'), ('Finance', 'Finance'), ('Sales', 'Sales')], default='Production', max_length=30)),
                ('criteria', models.JSONField(default=list, help_text='[{name, weight, description}]')),
                ('bonus_pct_of_salary', models.DecimalField(decimal_places=2, default=10.0, help_text='Max bonus as % of monthly salary when score = 100', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fo_kpi_templates', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['department', 'role'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveSmallIntegerField()),
                ('scores', models.JSONField(default=list, help_text='[{name, weight, score, remarks}]')),
                ('salary_ref', models.DecimalField(decimal_places=2, default=0, help_text='Monthly salary used for bonus calculation', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=15)),
                ('evaluated_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fo_evaluations', to='bredbound.businessinstance')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='factory_ops.factoryemployee')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='factory_ops.kpitemplate')),
            ],
            options={
                'ordering': ['-period_year', '-period_month', 'employee_name'],
            },
        ),
    ]
