# Generated by Django 4.2.28 on 2026-04-30 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0008_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_stores', to='bredbound.businessinstance')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stores', to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=8)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_tasks', to='bredbound.businessemployee')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='store_ops.retailstore')),
            ],
            options={
                'ordering': ['is_done', '-priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='StoreReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('sales_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('transaction_count', models.IntegerField(blank=True, null=True)),
                ('top_selling_product', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='store_ops.retailstore')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_store_reports', to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('store', 'report_date')},
            },
        ),
    ]
