from django.db import models
from django.utils import timezone


class WorkCenter(models.Model):
    STATUS = [('active', 'Active'), ('idle', 'Idle'), ('maintenance', 'Under Maintenance'), ('offline', 'Offline')]
    business = models.ForeignKey('bredbound.BusinessInstance', on_delete=models.CASCADE, related_name='mes_work_centers')
    code = models.CharField(max_length=20)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    status = models.CharField(max_length=20, choices=STATUS, default='idle')
    capacity_per_hour = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    operator = models.ForeignKey('bredbound.BusinessEmployee', on_delete=models.SET_NULL, null=True, blank=True)
    machine_id = models.CharField(max_length=50, blank=True)
    location = models.CharField(max_length=100, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [('business', 'code')]
        ordering = ['code']

    def __str__(self):
        return f"{self.code} — {self.name}"

class Routing(models.Model):
    business = models.ForeignKey('bredbound.BusinessInstance', on_delete=models.CASCADE, related_name='mes_routings')
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class RoutingStation(models.Model):
    routing = models.ForeignKey(Routing, on_delete=models.CASCADE, related_name='stations')
    work_center = models.ForeignKey(WorkCenter, on_delete=models.CASCADE, related_name='routing_stations')
    sequence = models.IntegerField(default=10)
    name = models.CharField(max_length=100, blank=True, help_text="Override work center name for this specific routing step")
    is_bottleneck = models.BooleanField(default=False)

    class Meta:
        ordering = ['routing', 'sequence']

    def __str__(self):
        return f"{self.routing.name} - Step {self.sequence}: {self.work_center.name}"


class ProductionOrder(models.Model):
    STATUS = [
        ('planned', 'Planned'), ('released', 'Released'), ('in_progress', 'In Progress'),
        ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'),
    ]
    PRIORITY = [('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')]

    business = models.ForeignKey('bredbound.BusinessInstance', on_delete=models.CASCADE, related_name='mes_production_orders')
    order_number = models.CharField(max_length=30)
    product_name = models.CharField(max_length=150)
    product_code = models.CharField(max_length=50, blank=True)
    output_lot = models.ForeignKey('inventory.ProductLot', on_delete=models.SET_NULL, null=True, blank=True, related_name='mes_production_orders', help_text="The batch/lot number generated by this order")
    work_center = models.ForeignKey(WorkCenter, on_delete=models.SET_NULL, null=True, blank=True, related_name='production_orders')
    routing = models.ForeignKey(Routing, on_delete=models.SET_NULL, null=True, blank=True, related_name='production_orders')
    current_station = models.ForeignKey(RoutingStation, on_delete=models.SET_NULL, null=True, blank=True, related_name='active_orders')
    quantity_planned = models.DecimalField(max_digits=12, decimal_places=3)
    quantity_produced = models.DecimalField(max_digits=12, decimal_places=3, default=0)
    unit = models.CharField(max_length=20, default='pcs')
    status = models.CharField(max_length=20, choices=STATUS, default='planned')
    priority = models.CharField(max_length=10, choices=PRIORITY, default='normal')
    scheduled_start = models.DateTimeField(null=True, blank=True)
    scheduled_end = models.DateTimeField(null=True, blank=True)
    actual_start = models.DateTimeField(null=True, blank=True)
    actual_end = models.DateTimeField(null=True, blank=True)
    created_by = models.ForeignKey('accounts.User', on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    notes = models.TextField(blank=True)

    class Meta:
        unique_together = [('business', 'order_number')]
        ordering = ['-created_at']

    def __str__(self):
        return f"WO-{self.order_number}: {self.product_name}"

    @property
    def progress_percent(self):
        if self.quantity_planned > 0:
            return min(100, int((self.quantity_produced / self.quantity_planned) * 100))
        return 0


class ProductionLog(models.Model):
    ACTIONS = [
        ('start', 'Started'), ('pause', 'Paused'), ('resume', 'Resumed'),
        ('complete', 'Completed'), ('scrap', 'Scrap Recorded'), ('note', 'Note Added'),
    ]
    production_order = models.ForeignKey(ProductionOrder, on_delete=models.CASCADE, related_name='logs')
    action = models.CharField(max_length=20, choices=ACTIONS)
    quantity = models.DecimalField(max_digits=12, decimal_places=3, null=True, blank=True)
    note = models.TextField(blank=True)
    recorded_by = models.ForeignKey('accounts.User', on_delete=models.SET_NULL, null=True)
    recorded_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-recorded_at']

    def __str__(self):
        return f"{self.production_order} — {self.action}"


class StationTrackingLog(models.Model):
    production_order = models.ForeignKey(ProductionOrder, on_delete=models.CASCADE, related_name='station_logs')
    station = models.ForeignKey(RoutingStation, on_delete=models.CASCADE)
    assigned_machine = models.ForeignKey('asset_management.Asset', on_delete=models.SET_NULL, null=True, blank=True, help_text="Specific machine assigned during this station step")
    worker = models.ForeignKey('accounts.User', on_delete=models.SET_NULL, null=True)
    entered_at = models.DateTimeField(default=timezone.now)
    exited_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-entered_at']

    def __str__(self):
        return f"{self.production_order} at {self.station}"

    @property
    def cycle_time_minutes(self):
        if self.exited_at:
            return int((self.exited_at - self.entered_at).total_seconds() / 60)
        return None


class QualityCheck(models.Model):
    RESULT = [('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional Pass')]
    production_order = models.ForeignKey(ProductionOrder, on_delete=models.CASCADE, related_name='quality_checks')
    checkpoint = models.CharField(max_length=100)
    result = models.CharField(max_length=20, choices=RESULT)
    measured_value = models.CharField(max_length=50, blank=True)
    acceptable_range = models.CharField(max_length=50, blank=True)
    defect_description = models.TextField(blank=True)
    inspected_by = models.ForeignKey('accounts.User', on_delete=models.SET_NULL, null=True)
    inspected_at = models.DateTimeField(default=timezone.now)
    notes = models.TextField(blank=True)

    class Meta:
        ordering = ['-inspected_at']

    def __str__(self):
        return f"{self.production_order} — {self.checkpoint} [{self.result}]"


class DowntimeRecord(models.Model):
    CATEGORIES = [
        ('mechanical', 'Mechanical Failure'), ('electrical', 'Electrical Failure'),
        ('maintenance', 'Planned Maintenance'), ('material', 'Material Shortage'),
        ('operator', 'Operator Absence'), ('changeover', 'Changeover/Setup'),
        ('other', 'Other'),
    ]
    work_center = models.ForeignKey(WorkCenter, on_delete=models.CASCADE, related_name='downtime_records')
    category = models.CharField(max_length=20, choices=CATEGORIES)
    description = models.TextField(blank=True)
    started_at = models.DateTimeField()
    ended_at = models.DateTimeField(null=True, blank=True)
    recorded_by = models.ForeignKey('accounts.User', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['-started_at']

    @property
    def duration_minutes(self):
        if self.ended_at:
            return int((self.ended_at - self.started_at).total_seconds() / 60)
        return None


class OEESnapshot(models.Model):
    work_center = models.ForeignKey(WorkCenter, on_delete=models.CASCADE, related_name='oee_snapshots')
    snapshot_date = models.DateField()
    availability = models.DecimalField(max_digits=5, decimal_places=2, default=0)  # %
    performance = models.DecimalField(max_digits=5, decimal_places=2, default=0)   # %
    quality = models.DecimalField(max_digits=5, decimal_places=2, default=0)       # %
    oee = models.DecimalField(max_digits=5, decimal_places=2, default=0)           # %
    planned_production_time = models.PositiveIntegerField(default=0)  # minutes
    actual_production_time = models.PositiveIntegerField(default=0)

    class Meta:
        unique_together = [('work_center', 'snapshot_date')]
        ordering = ['-snapshot_date']

    def save(self, *args, **kwargs):
        self.oee = (self.availability * self.performance * self.quality) / 10000
        super().save(*args, **kwargs)


class HardwareScanner(models.Model):
    business = models.ForeignKey('bredbound.BusinessInstance', on_delete=models.CASCADE, related_name='mes_scanners')
    name = models.CharField(max_length=100)
    mac_address = models.CharField(max_length=50, blank=True)
    ip_address = models.CharField(max_length=50, blank=True)
    assigned_station = models.ForeignKey(RoutingStation, on_delete=models.SET_NULL, null=True, blank=True, related_name='scanners')
    is_active = models.BooleanField(default=True)
    last_ping = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.name} ({self.assigned_station})"


class ScannerEventLog(models.Model):
    EVENT_TYPE = [('check_in', 'Check-In'), ('check_out', 'Check-Out'), ('error', 'Error')]
    scanner = models.ForeignKey(HardwareScanner, on_delete=models.CASCADE, related_name='events')
    event_type = models.CharField(max_length=20, choices=EVENT_TYPE)
    scanned_barcode = models.CharField(max_length=100)
    production_order = models.ForeignKey(ProductionOrder, on_delete=models.SET_NULL, null=True, blank=True)
    timestamp = models.DateTimeField(default=timezone.now)
    processed = models.BooleanField(default=False)
    error_message = models.TextField(blank=True)

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f"{self.scanner.name} - {self.event_type} - {self.scanned_barcode}"


# ── Footwear Production Schedule Extensions ───────────────────────────────────

class FootwearProductionSchedule(models.Model):
    """12-day production plan for a footwear batch, mapping to the Master Production Sheet."""
    FOOTWEAR_TYPE = [
        ('sneakers', 'Sneakers'),
        ('sandals', 'Sandals'),
        ('ladies_heels', 'Ladies Heels'),
        ('oxfords', 'Formal Oxfords'),
        ('loafers', 'Penny Loafers'),
        ('boots', 'Boots'),
        ('other', 'Other'),
    ]

    business = models.ForeignKey('bredbound.BusinessInstance', on_delete=models.CASCADE, related_name='footwear_schedules')
    production_order = models.ForeignKey(
        ProductionOrder, on_delete=models.SET_NULL, null=True, blank=True, related_name='footwear_schedules'
    )
    article_code = models.CharField(max_length=50, blank=True)
    buyer = models.CharField(max_length=150, blank=True)
    footwear_type = models.CharField(max_length=20, choices=FOOTWEAR_TYPE, default='other')
    total_pairs_planned = models.PositiveIntegerField(default=0)
    start_date = models.DateField()
    created_by = models.ForeignKey('accounts.User', on_delete=models.SET_NULL, null=True, related_name='footwear_schedules_created')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-start_date']

    def __str__(self):
        return f"{self.article_code or 'FW Schedule'} — {self.start_date} ({self.get_footwear_type_display()})"

    @property
    def overall_progress_pct(self):
        total_actual = sum(e.actual_output for e in self.day_entries.all())
        if self.total_pairs_planned:
            return min(100, int(total_actual / self.total_pairs_planned * 100))
        return 0


class ProductionDayEntry(models.Model):
    """Daily output log for one day within a FootwearProductionSchedule."""
    STAGE = [
        ('pre_d3', 'D-3 Pre-Production'),
        ('pre_d2', 'D-2 Pre-Production'),
        ('pre_d1', 'D-1 Pre-Production'),
        ('cutting', 'Cutting'),
        ('closing', 'Closing / Sewing'),
        ('lasting', 'Lasting'),
        ('bottoming', 'Bottoming'),
        ('finishing', 'Finishing'),
        ('qc', 'Final QC'),
        ('packout', 'Pack-out'),
    ]

    schedule = models.ForeignKey(FootwearProductionSchedule, on_delete=models.CASCADE, related_name='day_entries')
    day_label = models.CharField(max_length=10, help_text="e.g. D-3, D-2, 1, 2 … 12")
    production_date = models.DateField(null=True, blank=True)
    stage = models.CharField(max_length=15, choices=STAGE)
    key_activities = models.TextField(blank=True)
    daily_target = models.PositiveIntegerField(default=0)
    actual_output = models.PositiveIntegerField(default=0)
    cumulative_target = models.PositiveIntegerField(default=0)
    cumulative_actual = models.PositiveIntegerField(default=0)
    owner = models.CharField(max_length=100, blank=True)
    bottleneck = models.TextField(blank=True)

    class Meta:
        ordering = ['day_label']

    def __str__(self):
        return f"Day {self.day_label} — {self.get_stage_display()}"

    @property
    def variance(self):
        return self.actual_output - self.daily_target

    @property
    def on_target(self):
        return self.actual_output >= self.daily_target
