# Generated by Django 4.2.28 on 2026-04-30 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0009_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('house', 'House / Villa'), ('apartment', 'Apartment / Flat'), ('condo', 'Condo / Townhouse'), ('commercial', 'Commercial'), ('office', 'Office Space'), ('land', 'Land / Plot'), ('industrial', 'Industrial'), ('other', 'Other')], default='house', max_length=20)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('both', 'Sale or Rent')], default='sale', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active Listing'), ('under_contract', 'Under Contract'), ('sold', 'Sold'), ('rented', 'Rented'), ('off_market', 'Off Market'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='State / Province / Region')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Area (sqft)')),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('rent_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mls_number', models.CharField(blank=True, max_length=50, verbose_name='MLS / Listing Number')),
                ('listing_url', models.URLField(blank=True, verbose_name='IDX / MLS / Portal URL')),
                ('virtual_tour_url', models.URLField(blank=True, verbose_name='Virtual Tour / 3D Tour URL')),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='Key features, comma-separated (e.g. Pool, Garage, Garden)')),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='bredbound.businessinstance')),
                ('listed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listed_properties', to='bredbound.businessemployee')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyShowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_showings', to='bredbound.businessemployee')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='property_listings.property')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
