# Generated by Django 4.2.28 on 2026-04-29 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0006_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20)),
                ('supplier_name', models.CharField(max_length=150)),
                ('purchase_order_ref', models.CharField(blank=True, max_length=100)),
                ('carrier_name', models.CharField(blank=True, max_length=100)),
                ('tracking_ref', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('expected', 'Expected'), ('partial', 'Partially Received'), ('complete', 'Complete'), ('over', 'Over-received'), ('cancelled', 'Cancelled')], default='expected', max_length=15)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_receipts', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('business', 'receipt_number')},
            },
        ),
        migrations.CreateModel(
            name='PickList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_number', models.CharField(max_length=20)),
                ('order_reference', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picking', 'Picking in Progress'), ('picked', 'Fully Picked'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bredbound.businessemployee')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_lists', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('business', 'pick_number')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('zone_type', models.CharField(choices=[('receiving', 'Receiving'), ('storage', 'Storage'), ('picking', 'Picking Area'), ('packing', 'Packing / Dispatch'), ('shipping', 'Shipping Dock'), ('returns', 'Returns Processing'), ('hazmat', 'Hazmat / Controlled'), ('cold', 'Cold Storage'), ('overflow', 'Overflow')], default='storage', max_length=15)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('capacity_bins', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_zones', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['zone_type', 'name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StorageBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_code', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('is_occupied', models.BooleanField(default=False)),
                ('current_sku', models.CharField(blank=True, max_length=80)),
                ('current_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='wms.warehousezone')),
            ],
            options={
                'ordering': ['bin_code'],
                'unique_together': {('zone', 'bin_code')},
            },
        ),
        migrations.CreateModel(
            name='PickListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('picked_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_picked', models.BooleanField(default=False)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_items', to='wms.storagebin')),
                ('pick_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms.picklist')),
            ],
            options={
                'ordering': ['bin__bin_code', 'item_description'],
            },
        ),
        migrations.CreateModel(
            name='InboundReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('expected_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='wms.storagebin')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms.inboundreceipt')),
            ],
        ),
    ]
