# Generated by Django 4.2.28 on 2026-05-28 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('document_type', models.CharField(choices=[('nda', 'NDA'), ('contract', 'Contract'), ('employment', 'Employment'), ('vendor', 'Vendor'), ('compliance', 'Compliance'), ('other', 'Other')], max_length=15)),
                ('raw_text', models.TextField(blank=True)),
                ('overall_risk', models.IntegerField(blank=True, null=True)),
                ('risk_label', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('executive_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('reviewing', 'Reviewing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legaldocument_set', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_number', models.CharField(blank=True, max_length=50)),
                ('clause_title', models.CharField(blank=True, max_length=500)),
                ('original_text', models.TextField()),
                ('plain_english', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('safe', 'Safe'), ('caution', 'Caution'), ('risky', 'Risky'), ('critical', 'Critical')], default='safe', max_length=10)),
                ('risk_score', models.IntegerField(default=0)),
                ('negotiation_suggestion', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clause_set', to='bredbound.businessinstance')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='sage.legaldocument')),
            ],
            options={
                'ordering': ['clause_number'],
            },
        ),
    ]
