# Generated by Django 4.2.28 on 2026-04-30 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0010_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('travel_policy_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_accounts', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=20)),
                ('trip_purpose', models.CharField(blank=True, max_length=300)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('travel_type', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('flight_hotel', 'Flight + Hotel'), ('other', 'Other')], default='flight_hotel', max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('booking_reference', models.CharField(blank=True, max_length=100)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='bredbound.businessemployee')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_requests', to='bredbound.businessinstance')),
                ('corporate_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_requests', to='travel_desk.corporateaccount')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_requests', to='bredbound.businessemployee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('applies_to', models.CharField(choices=[('all', 'All'), ('specific', 'Specific')], default='all', max_length=20)),
                ('max_hotel_rate_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_flight_economy', models.BooleanField(default=True)),
                ('require_advance_booking_days', models.IntegerField(default=7)),
                ('require_approval', models.BooleanField(default=True)),
                ('approval_threshold', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_policies', to='bredbound.businessinstance')),
            ],
            options={
                'verbose_name_plural': 'Travel Policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TravelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('meals', 'Meals'), ('transport', 'Transport'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('receipt_url', models.URLField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='travel_desk.travelrequest')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
