# Generated by Django 4.2.28 on 2026-04-29 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0005_alter_businessinstance_business_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('checkpoints', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvi_templates', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_number', models.CharField(max_length=20)),
                ('vehicle_reg', models.CharField(max_length=30)),
                ('vehicle_make', models.CharField(max_length=60)),
                ('vehicle_model', models.CharField(blank=True, max_length=60)),
                ('vehicle_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=50)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, max_length=40)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('job_card_number', models.CharField(blank=True, max_length=20)),
                ('overall_result', models.CharField(choices=[('pass', 'Pass'), ('advisory', 'Pass with Advisories'), ('fail', 'Fail'), ('incomplete', 'Incomplete')], default='incomplete', max_length=15)),
                ('inspected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('share_token', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('report_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_inspections', to='bredbound.businessinstance')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bredbound.businessemployee')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dvi.inspectiontemplate')),
            ],
            options={
                'ordering': ['-inspected_at'],
                'unique_together': {('business', 'inspection_number')},
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ok', 'OK / Pass'), ('attention', 'Needs Attention (Advisory)'), ('critical', 'Critical / Fail'), ('na', 'Not Applicable')], default='ok', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dvi/photos/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dvi.vehicleinspection')),
            ],
            options={
                'ordering': ['order', 'checkpoint'],
            },
        ),
    ]
