# Generated by Django 4.2.28 on 2026-05-28 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=300)),
                ('theme_type', models.CharField(choices=[('pain_point', 'Pain Point'), ('feature_request', 'Feature Request'), ('praise', 'Praise'), ('confusion', 'Confusion')], max_length=20)),
                ('mention_count', models.IntegerField(default=1)),
                ('priority_score', models.IntegerField(blank=True, null=True)),
                ('example_quotes', models.JSONField(default=list)),
                ('ai_analysis', models.TextField(blank=True)),
                ('first_seen', models.DateField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insighttheme_set', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-mention_count'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('survey_type', models.CharField(choices=[('in_app', 'In-App'), ('post_session', 'Post Session'), ('nps', 'NPS'), ('feature', 'Feature'), ('exit', 'Exit')], max_length=20)),
                ('questions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('responses_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacksurvey_set', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
