# Generated by Django 4.2.28 on 2026-05-06 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bredbound', '0011_alter_businessinstance_business_type'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='category',
            field=models.CharField(choices=[('length', 'Length'), ('weight', 'Weight'), ('volume', 'Volume'), ('area', 'Area'), ('unit', 'Unit'), ('time', 'Time'), ('custom', 'Custom')], default='unit', max_length=20),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='is_reference',
            field=models.BooleanField(default=False, help_text='Is this the reference unit for this category?'),
        ),
        migrations.CreateModel(
            name='UoMConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=6, help_text='Multiplier to convert from_uom to to_uom', max_digits=12)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_uom_conversions', to='bredbound.businessinstance')),
                ('from_uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='inventory.unitofmeasure')),
                ('to_uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='inventory.unitofmeasure')),
            ],
            options={
                'unique_together': {('from_uom', 'to_uom')},
            },
        ),
    ]
