# Generated by Django 4.2.28 on 2026-05-06 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_unitofmeasure_options_unitofmeasure_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('product', 'lot_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_levels', to='inventory.productlot'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.productlot'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together={('product', 'warehouse', 'lot')},
        ),
    ]
