# Generated by Django 4.2.28 on 2026-05-06 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0011_alter_businessinstance_business_type'),
        ('inventory', '0003_productlot_alter_stocklevel_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('layout_data', models.TextField(help_text='Template structure (e.g. ZPL code or HTML layout for printing)')),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_label_templates', to='bredbound.businessinstance')),
            ],
        ),
        migrations.AddField(
            model_name='productlot',
            name='qms_status',
            field=models.CharField(choices=[('pending', 'Pending QMS'), ('passed', 'Passed QMS'), ('failed', 'Failed QMS'), ('bypass', 'Bypass QMS')], default='pending', help_text='Current quality control status of this batch', max_length=20),
        ),
        migrations.CreateModel(
            name='PackagingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_data', models.CharField(help_text='The scannable string generated for this specific label', max_length=150)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_labels', to='bredbound.businessinstance')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='inventory.productlot')),
                ('printed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.labeltemplate')),
            ],
            options={
                'ordering': ['-printed_at'],
            },
        ),
    ]
