# Generated by Django 4.2.28 on 2026-04-29 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0005_alter_businessinstance_business_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('variant', models.CharField(blank=True, max_length=80)),
                ('year', models.PositiveSmallIntegerField()),
                ('colour', models.CharField(blank=True, max_length=40)),
                ('interior_colour', models.CharField(blank=True, max_length=40)),
                ('vin', models.CharField(blank=True, max_length=50)),
                ('reg_number', models.CharField(blank=True, max_length=30)),
                ('engine_size', models.CharField(blank=True, max_length=20)),
                ('transmission', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual'), ('semi_auto', 'Semi-Automatic'), ('ev', 'Electric')], default='auto', max_length=10)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('lpg', 'LPG'), ('other', 'Other')], default='petrol', max_length=10)),
                ('body_type', models.CharField(blank=True, max_length=30)),
                ('doors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_type', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('certified', 'Certified Pre-Owned'), ('demo', 'Demo')], default='used', max_length=15)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('salvage', 'Salvage')], default='good', max_length=15)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('trade_in', 'Trade-In'), ('service', 'In Service'), ('transit', 'In Transit')], default='available', max_length=15)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='dms/vehicles/')),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_stock', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('business', 'stock_number')},
            },
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='dms/vehicle_photos/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dms.vehiclestock')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_number', models.CharField(max_length=20)),
                ('stage', models.CharField(choices=[('enquiry', 'Enquiry'), ('test_drive', 'Test Drive Booked'), ('negotiation', 'Negotiation'), ('agreed', 'Price Agreed'), ('finance', 'Finance Processing'), ('documentation', 'Documentation'), ('delivered', 'Delivered'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='enquiry', max_length=20)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_address', models.TextField(blank=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('finance_type', models.CharField(choices=[('cash', 'Cash'), ('finance', 'Dealer Finance'), ('bank', 'Bank Finance'), ('lease', 'Lease'), ('balloon', 'Balloon Finance'), ('other', 'Other')], default='cash', max_length=10)),
                ('finance_provider', models.CharField(blank=True, max_length=100)),
                ('finance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_repayment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_term_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('test_drive_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_deals', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bredbound.businessemployee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='dms.vehiclestock')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('business', 'deal_number')},
            },
        ),
        migrations.CreateModel(
            name='TradeIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=30)),
                ('vin', models.CharField(blank=True, max_length=50)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('salvage', 'Salvage')], default='good', max_length=15)),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('accepted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_in', to='dms.vehicledeal')),
            ],
        ),
        migrations.CreateModel(
            name='DealNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_notes', to='dms.vehicledeal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
