# Generated by Django 4.2.28 on 2026-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialconsumption',
            name='actual_scrap_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of material scrapped during production', max_digits=10),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='actual_yield_pct',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Actual material yield percentage achieved', max_digits=5),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='is_tooling_consumption',
            field=models.BooleanField(default=False, help_text='Indicates if this consumption record is for a tooling asset (e.g. Mold shots)'),
        ),
    ]
