# Generated by Django 4.2.28 on 2026-05-06 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productlot_alter_stocklevel_unique_together_and_more'),
        ('production', '0002_materialconsumption_actual_scrap_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='output_lot',
            field=models.ForeignKey(blank=True, help_text='The batch/lot number generated by this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_by_mos', to='inventory.productlot'),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='consumed_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_in_productions', to='inventory.productlot'),
        ),
    ]
