# Generated by Django 4.2.28 on 2026-05-18 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0011_alter_businessinstance_business_type'),
        ('production', '0003_manufacturingorder_output_lot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionKPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('orders_due', models.PositiveIntegerField(default=0)),
                ('orders_on_time', models.PositiveIntegerField(default=0)),
                ('pairs_to_final_qc', models.PositiveIntegerField(default=0)),
                ('pairs_passed_first', models.PositiveIntegerField(default=0)),
                ('pairs_produced', models.PositiveIntegerField(default=0)),
                ('pairs_rejected_reworked', models.PositiveIntegerField(default=0)),
                ('total_labour_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('wip_pairs_at_lasting', models.PositiveIntegerField(default=0)),
                ('total_production_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_kpi_snapshots', to='bredbound.businessinstance')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_snapshots_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'unique_together': {('business', 'snapshot_date', 'period')},
            },
        ),
    ]
