# Generated by Django 4.2.28 on 2026-05-27 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_id', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=300)),
                ('intent_score', models.IntegerField(blank=True, null=True)),
                ('pipeline_stage', models.CharField(blank=True, max_length=100)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('is_cold', models.BooleanField(default=False)),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crux_contacts', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('meeting', 'Meeting'), ('whatsapp', 'WhatsApp'), ('note', 'Note')], max_length=20)),
                ('summary', models.TextField()),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crux_interactions', to='bredbound.businessinstance')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crux.contact')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
