# Generated by Django 4.2.28 on 2026-04-30 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0009_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('agent_split_pct', models.DecimalField(decimal_places=2, default=70, max_digits=5, verbose_name='Agent Split %')),
                ('broker_split_pct', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='Broker Split %')),
                ('referral_fee_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Referral Fee %')),
                ('annual_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Annual Cap (agent stops splitting after this amount)')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, help_text='Leave blank for a default/global rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_rules', to='bredbound.businessemployee')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommissionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_reference', models.CharField(max_length=200, verbose_name='Deal / Property Reference')),
                ('client_name', models.CharField(blank=True, max_length=150)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('gross_commission', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Gross Commission Income (GCI)')),
                ('agent_split_pct', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('agent_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('broker_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('referral_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_entries', to='bredbound.businessemployee')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entries', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-close_date', '-created_at'],
            },
        ),
    ]
