# Generated by Django 4.2.28 on 2026-04-28 00:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_type', models.CharField(choices=[('manufacture', 'Manufacture'), ('phantom', 'Phantom'), ('kit', 'Kit')], default='manufacture', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('obsolete', 'Obsolete')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bill of Materials',
                'verbose_name_plural': 'Bills of Materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('capacity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('capacity_uom', models.CharField(default='units/hour', max_length=20)),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_centers', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BOMOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.IntegerField(default=10)),
                ('duration_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='bom.billofmaterials')),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bom.workcenter')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('scrap_pct', models.DecimalField(decimal_places=2, default=0, help_text='Scrap/waste percentage', max_digits=5)),
                ('position', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='bom.billofmaterials')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
