# Generated by Django 4.2.28 on 2026-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomcomponent',
            name='expected_yield_pct',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Expected material yield percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='is_tooling',
            field=models.BooleanField(default=False, help_text='Is this a consumable tooling asset (e.g. Mold/Die)?'),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='tooling_consumed_per_unit',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Tooling lifespan shots/uses consumed per unit produced', max_digits=10),
        ),
    ]
