# Generated by Django 4.2.28 on 2026-05-18 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0011_alter_businessinstance_business_type'),
        ('bom', '0003_bomcomponent_expected_yield_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeArticleBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_code', models.CharField(help_text='Links to PLM ShoeArticle.article_code', max_length=50)),
                ('article_name', models.CharField(blank=True, max_length=150)),
                ('last_code', models.CharField(blank=True, max_length=50)),
                ('size_run', models.CharField(blank=True, max_length=30)),
                ('sample_size', models.CharField(blank=True, max_length=10)),
                ('buyer', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_article_boms', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoe_boms_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoeColorwayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leather_code', models.CharField(help_text='Colour name or leather code', max_length=50)),
                ('size_data', models.JSONField(default=dict, help_text="Dict of size→qty e.g. {'35':2,'36':3,'37':3,'38':2,'39':2}")),
                ('pairs_per_carton', models.PositiveIntegerField(default=12)),
                ('sets', models.PositiveIntegerField(default=1)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colorways', to='bom.shoearticlebom')),
            ],
            options={
                'ordering': ['leather_code'],
            },
        ),
        migrations.CreateModel(
            name='ShoeBOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('upper', 'Upper'), ('lining', 'Lining'), ('footbed', 'Footbed'), ('adhesive', 'Adhesive & Chemical'), ('lasting', 'Lasting & Bottom'), ('finishing', 'Finishing'), ('other', 'Others')], default='upper', max_length=15)),
                ('material_name', models.CharField(max_length=150)),
                ('uom', models.CharField(default='S/ft', max_length=20)),
                ('cons_per_pair', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('order_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cons', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('conversion_note', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_pair', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('position', models.IntegerField(default=0)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='bom.shoearticlebom')),
                ('colorway', models.ForeignKey(blank=True, help_text='Blank = shared across all colours', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_lines', to='bom.shoecolorwayentry')),
            ],
            options={
                'ordering': ['category', 'position', 'material_name'],
            },
        ),
    ]
