# Generated by Django 4.2.28 on 2026-05-28 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyQuery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('ai_answer', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('onboarding', 'Onboarding'), ('leave', 'Leave'), ('benefits', 'Benefits'), ('conduct', 'Conduct'), ('payroll', 'Payroll'), ('other', 'Other')], default='other', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_queries', to='bredbound.businessinstance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_email', models.EmailField(max_length=254)),
                ('task', models.CharField(max_length=500)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tasks', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['due_date', 'is_completed'],
            },
        ),
    ]
