# Generated by Django 4.2.28 on 2026-05-28 02:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('attendees', models.JSONField(default=list, help_text='List of attendee email addresses')),
                ('preferred_times', models.JSONField(default=list, help_text='List of ISO-8601 datetime strings')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('calendar_event_id', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTriage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('body_preview', models.TextField(help_text='First ~500 characters of the email body')),
                ('category', models.CharField(choices=[('inquiry', 'General Inquiry'), ('sales', 'Sales / Commercial'), ('support', 'Support Request'), ('complaint', 'Complaint'), ('newsletter', 'Newsletter / Marketing'), ('internal', 'Internal'), ('spam', 'Spam'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_processed', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_triages', to='bredbound.businessinstance')),
            ],
            options={
                'verbose_name': 'Email Triage',
                'verbose_name_plural': 'Email Triages',
                'ordering': ['-created_at'],
            },
        ),
    ]
