# Generated by Django 6.0.3 on 2026-04-17 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('operations', 'Operations'), ('finance', 'Finance & Accounting'), ('people', 'People & HR'), ('sales', 'Sales & CRM'), ('communication', 'Communication'), ('production', 'Production & Manufacturing'), ('analytics', 'Analytics & Reports'), ('documents', 'Documents & Storage'), ('ai', 'AI & Automation'), ('web', 'Website & Marketing'), ('projects', 'Project Management')], max_length=30)),
                ('icon', models.CharField(default='bi-puzzle', max_length=50)),
                ('is_free', models.BooleanField(default=True)),
                ('monthly_price_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('applicable_to', models.JSONField(default=list)),
                ('requires_modules', models.JSONField(blank=True, default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('url_namespace', models.CharField(blank=True, max_length=50)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="Auto-generated URL key, e.g. 'acme-corp' → /hub/acme-corp/", max_length=100, unique=True)),
                ('business_type', models.CharField(choices=[('shop', 'Retail Shop'), ('factory', 'Factory / Manufacturing'), ('business', 'General Business'), ('station', 'Service Station'), ('restaurant', 'Restaurant / Café'), ('hotel', 'Hotel / Hospitality'), ('clinic', 'Clinic / Healthcare'), ('school', 'School / Education'), ('warehouse', 'Warehouse / Distribution'), ('agency', 'Agency / Professional Services'), ('other', 'Other')], default='business', max_length=20)),
                ('installation_type', models.CharField(choices=[('cloud', 'Cloud Hosted'), ('ip_locked', 'IP-Locked Cloud'), ('self_hosted', 'Self Hosted')], default='cloud', max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_phone', models.CharField(blank=True, max_length=30)),
                ('business_address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('storage_used_mb', models.FloatField(default=0.0)),
                ('storage_limit_mb', models.FloatField(default=512.0)),
                ('allowed_ips', models.JSONField(blank=True, default=list)),
                ('sync_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('self_hosted_url', models.URLField(blank=True, help_text='Their server URL, used to push sync requests')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('accountant', 'Accountant'), ('hr', 'HR'), ('sales', 'Sales'), ('support', 'Support'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', max_length=20)),
                ('pin_code', models.CharField(blank=True, max_length=6)),
                ('accessible_modules', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_memberships', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, help_text="Friendly name, e.g. 'John's Laptop'", max_length=100)),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_sessions', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('push', 'Push to Cloud'), ('pull', 'Pull from Cloud'), ('full', 'Full Sync')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20)),
                ('records_synced', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='bredbound.businessinstance')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_activations', to='bredbound.modulecatalog')),
            ],
            options={
                'ordering': ['-activated_at'],
                'unique_together': {('business', 'module')},
            },
        ),
    ]
