# Generated by Django 4.2.28 on 2026-04-28 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessemployee',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='businessemployee',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO / Director'), ('audit_manager', 'Audit Manager'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('accountant', 'Accountant'), ('hr', 'HR Officer'), ('sales', 'Sales'), ('support', 'Support'), ('staff', 'Staff / Employee'), ('viewer', 'Viewer (Read Only)')], default='staff', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='businessemployee',
            unique_together={('business', 'user')},
        ),
    ]
