# Generated by Django 4.2.28 on 2026-04-28 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0002_businessemployee_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubPlanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('freemium', 'Freemium'), ('standard', 'Standard'), ('premium', 'Premium'), ('advance', 'Advance')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('monthly_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('storage_gb', models.FloatField(default=5.0)),
                ('allows_cloud', models.BooleanField(default=True)),
                ('allows_ip_locked', models.BooleanField(default=False)),
                ('allows_self_hosted', models.BooleanField(default=False)),
                ('includes_basic_modules', models.BooleanField(default=True)),
                ('includes_full_industry_set', models.BooleanField(default=False)),
                ('is_fully_customizable', models.BooleanField(default=False)),
                ('ip_locked_addon_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('self_hosted_addon_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_storage_price_per_gb', models.DecimalField(decimal_places=2, default=0.5, max_digits=8)),
                ('advance_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['monthly_price_usd'],
            },
        ),
        migrations.CreateModel(
            name='StorageIncreaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_gb', models.FloatField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_gb', models.FloatField(blank=True, null=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_requests', to='bredbound.businessinstance')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('freemium', 'Freemium'), ('standard', 'Standard'), ('premium', 'Premium'), ('advance', 'Advance')], default='freemium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending Payment')], default='active', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('extra_storage_gb', models.FloatField(default=0)),
                ('paid_ip_locked', models.BooleanField(default=False)),
                ('paid_self_hosted', models.BooleanField(default=False)),
                ('premium_industry', models.CharField(blank=True, max_length=20)),
                ('advance_selected_modules', models.JSONField(blank=True, default=list)),
                ('advance_storage_gb', models.FloatField(default=100)),
                ('advance_installation_types', models.JSONField(blank=True, default=list)),
                ('advance_discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('advance_monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
