# Generated by Django 4.2.28 on 2026-04-29 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0003_hubplanconfig_storageincreaserequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessemployee',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='businessemployee',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO / Chief Executive Officer'), ('president', 'President'), ('managing_director', 'Managing Director'), ('cfo', 'CFO / Chief Financial Officer'), ('cto', 'CTO / Chief Technology Officer'), ('cio', 'CIO / Chief Information Officer'), ('coo', 'COO / Chief Operations Officer'), ('cmo', 'CMO / Chief Marketing Officer'), ('chro', 'CHRO / Chief HR Officer'), ('cso', 'CSO / Chief Sales Officer'), ('director', 'Director'), ('technical_director', 'Technical Director'), ('creative_director', 'Creative Director'), ('finance_director', 'Finance Director'), ('operations_director', 'Operations Director'), ('sales_director', 'Sales Director'), ('hr_director', 'HR Director'), ('marketing_director', 'Marketing Director'), ('vp', 'Vice President (VP)'), ('vp_sales', 'VP of Sales'), ('vp_marketing', 'VP of Marketing'), ('vp_engineering', 'VP of Engineering'), ('vp_operations', 'VP of Operations'), ('vp_finance', 'VP of Finance'), ('audit_manager', 'Audit Manager'), ('compliance_officer', 'Compliance Officer'), ('manager', 'Manager'), ('department_manager', 'Department Manager'), ('project_manager', 'Project Manager'), ('marketing_manager', 'Marketing Manager'), ('hr_manager', 'HR Manager'), ('finance_manager', 'Finance Manager'), ('operations_manager', 'Operations Manager'), ('production_manager', 'Production Manager'), ('sales_manager', 'Sales Manager'), ('warehouse_manager', 'Warehouse Manager'), ('quality_manager', 'Quality Manager'), ('maintenance_manager', 'Maintenance Manager'), ('it_manager', 'IT Manager'), ('logistics_manager', 'Logistics Manager'), ('procurement_manager', 'Procurement Manager'), ('assistant_manager', 'Assistant Manager'), ('team_leader', 'Team Leader'), ('supervisor', 'Supervisor'), ('accountant', 'Accountant'), ('senior_accountant', 'Senior Accountant'), ('hr', 'HR Officer'), ('hr_officer', 'HR Specialist'), ('engineer', 'Engineer'), ('senior_engineer', 'Senior Engineer'), ('designer', 'Designer'), ('senior_designer', 'Senior Designer'), ('analyst', 'Analyst'), ('business_analyst', 'Business Analyst'), ('data_analyst', 'Data Analyst'), ('it_officer', 'IT Officer'), ('it_specialist', 'IT Specialist'), ('legal_officer', 'Legal Officer'), ('procurement_officer', 'Procurement Officer'), ('production_supervisor', 'Production Supervisor'), ('quality_inspector', 'Quality Inspector'), ('maintenance_engineer', 'Maintenance Engineer'), ('coordinator', 'Coordinator'), ('associate', 'Associate'), ('marketing_staff', 'Marketing Staff'), ('marketing_officer', 'Marketing Officer'), ('sales', 'Sales Representative'), ('sales_officer', 'Sales Officer'), ('sales_rep', 'Sales Rep / Executive'), ('support', 'Customer Support'), ('customer_support', 'Customer Support Specialist'), ('logistics_officer', 'Logistics Officer'), ('warehouse_officer', 'Warehouse Officer'), ('purchasing_officer', 'Purchasing Officer'), ('junior', 'Junior Staff'), ('junior_engineer', 'Junior Engineer'), ('junior_designer', 'Junior Designer'), ('junior_accountant', 'Junior Accountant'), ('junior_analyst', 'Junior Analyst'), ('assistant', 'Assistant'), ('executive_assistant', 'Executive Assistant'), ('administrative_assistant', 'Administrative Assistant'), ('staff', 'Staff / Employee'), ('operator', 'Machine Operator'), ('technician', 'Technician'), ('driver', 'Driver'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('intern', 'Intern'), ('trainee', 'Trainee'), ('apprentice', 'Apprentice'), ('viewer', 'Viewer (Read Only)'), ('custom', 'Custom Position')], default='staff', max_length=30),
        ),
        migrations.CreateModel(
            name='CustomPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('access_level', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=3, help_text='1=viewer, 2=staff, 3=junior, 4=associate, 5=specialist, 6=manager, 7=director, 8=c-suite, 9=executive')),
                ('perm_view_financials', models.BooleanField(default=False)),
                ('perm_approve_expenses', models.BooleanField(default=False)),
                ('perm_manage_employees', models.BooleanField(default=False)),
                ('perm_manage_modules', models.BooleanField(default=False)),
                ('perm_access_reports', models.BooleanField(default=True)),
                ('perm_manage_inventory', models.BooleanField(default=False)),
                ('perm_manage_production', models.BooleanField(default=False)),
                ('perm_manage_quality', models.BooleanField(default=False)),
                ('perm_manage_assets', models.BooleanField(default=False)),
                ('perm_manage_plm', models.BooleanField(default=False)),
                ('perm_manage_erp', models.BooleanField(default=False)),
                ('perm_manage_mes', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_positions', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-access_level', 'name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.AddField(
            model_name='businessemployee',
            name='custom_position',
            field=models.ForeignKey(blank=True, help_text="Set when role='custom'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='bredbound.customposition'),
        ),
    ]
