# Generated by Django 4.2.28 on 2026-04-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bredbound', '0004_businessemployee_phone_alter_businessemployee_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinstance',
            name='business_type',
            field=models.CharField(choices=[('shop', 'Retail Shop'), ('factory', 'Factory / Manufacturing'), ('business', 'General Business'), ('station', 'Service Station'), ('restaurant', 'Restaurant / Café'), ('hotel', 'Hotel / Hospitality'), ('clinic', 'Clinic / Healthcare'), ('school', 'School / Education'), ('warehouse', 'Warehouse / Distribution'), ('agency', 'Agency / Professional Services'), ('garage', 'Garage / Auto Repair Shop'), ('dealership', 'Vehicle Dealership'), ('auto_parts', 'Auto Parts Store'), ('auto_supplier', 'Automotive Supplier'), ('other', 'Other')], default='business', max_length=20),
        ),
        migrations.AlterField(
            model_name='modulecatalog',
            name='category',
            field=models.CharField(choices=[('operations', 'Operations'), ('finance', 'Finance & Accounting'), ('people', 'People & HR'), ('sales', 'Sales & CRM'), ('communication', 'Communication'), ('production', 'Production & Manufacturing'), ('automotive', 'Automotive'), ('analytics', 'Analytics & Reports'), ('documents', 'Documents & Storage'), ('ai', 'AI & Automation'), ('web', 'Website & Marketing'), ('projects', 'Project Management')], max_length=30),
        ),
    ]
