# Generated by Django 4.2.28 on 2026-04-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bredbound', '0005_alter_businessinstance_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinstance',
            name='business_type',
            field=models.CharField(choices=[('shop', 'Retail Shop'), ('factory', 'Factory / Manufacturing'), ('business', 'General Business'), ('station', 'Service Station'), ('restaurant', 'Restaurant / Café'), ('hotel', 'Hotel / Hospitality'), ('clinic', 'Clinic / Healthcare'), ('school', 'School / Education'), ('warehouse', 'Warehouse / Distribution'), ('agency', 'Agency / Professional Services'), ('garage', 'Garage / Auto Repair Shop'), ('dealership', 'Vehicle Dealership'), ('auto_parts', 'Auto Parts Store'), ('auto_supplier', 'Automotive Supplier'), ('logistics', 'Logistics & Freight Company'), ('freight_forwarder', 'Freight Forwarder / Customs Broker'), ('courier', 'Courier & Last-Mile Delivery'), ('consulting', 'Business Consulting Firm'), ('supply_chain_consulting', 'Supply Chain Consulting'), ('it_consulting', 'IT / Technology Consulting'), ('legal', 'Legal / Law Firm'), ('accounting_firm', 'Accounting / Audit Firm'), ('other', 'Other')], default='business', max_length=30),
        ),
    ]
