# Generated by Django 4.2.28 on 2026-05-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bredbound', '0010_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinstance',
            name='business_type',
            field=models.CharField(choices=[('shop', 'Retail Shop'), ('factory', 'Factory / Manufacturing'), ('business', 'General Business'), ('station', 'Service Station'), ('restaurant', 'Restaurant / Café'), ('hotel', 'Hotel / Hospitality'), ('resort', 'Resort / Boutique Hotel'), ('hostel', 'Hostel / Guest House'), ('clinic', 'Clinic / Healthcare'), ('school', 'School / Education'), ('training_center', 'Training Center / Academy'), ('university', 'University / College'), ('tutoring_center', 'Tutoring Center'), ('corporate_training', 'Corporate Training Provider'), ('real_estate_agency', 'Real Estate Agency'), ('real_estate_agent', 'Independent Real Estate Agent'), ('wholesale', 'Wholesaler / Distributor'), ('retail_chain', 'Retail Chain / Multi-Location Store'), ('warehouse', 'Warehouse / Distribution'), ('agency', 'Agency / Professional Services'), ('garage', 'Garage / Auto Repair Shop'), ('dealership', 'Vehicle Dealership'), ('auto_parts', 'Auto Parts Store'), ('auto_supplier', 'Automotive Supplier'), ('logistics', 'Logistics & Freight Company'), ('freight_forwarder', 'Freight Forwarder / Customs Broker'), ('courier', 'Courier & Last-Mile Delivery'), ('travel_agency', 'Travel Agency / Tour Operator'), ('tour_operator', 'Tour Operator'), ('corporate_travel', 'Corporate Travel Management'), ('ota', 'Online Travel Agency (OTA)'), ('salon', 'Hair & Beauty Salon'), ('spa', 'Spa & Wellness Centre'), ('care_home', 'Care Home / Assisted Living'), ('personal_trainer', 'Personal Trainer / Fitness'), ('landscaping', 'Landscaping & Garden Services'), ('nursery', 'Garden Nursery / Plant Shop'), ('florist', 'Florist'), ('consulting', 'Business Consulting Firm'), ('supply_chain_consulting', 'Supply Chain Consulting'), ('it_consulting', 'IT / Technology Consulting'), ('legal', 'Legal / Law Firm'), ('accounting_firm', 'Accounting / Audit Firm'), ('other', 'Other')], default='business', max_length=30),
        ),
    ]
