# Generated by Django 4.2.28 on 2026-05-26 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0011_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBusinessInstance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="Auto-generated URL key, e.g. 'acme-corp' → /hub/acme-corp/", max_length=100)),
                ('business_type', models.CharField(choices=[('shop', 'Retail Shop'), ('factory', 'Factory / Manufacturing'), ('business', 'General Business'), ('station', 'Service Station'), ('restaurant', 'Restaurant / Café'), ('hotel', 'Hotel / Hospitality'), ('resort', 'Resort / Boutique Hotel'), ('hostel', 'Hostel / Guest House'), ('clinic', 'Clinic / Healthcare'), ('school', 'School / Education'), ('training_center', 'Training Center / Academy'), ('university', 'University / College'), ('tutoring_center', 'Tutoring Center'), ('corporate_training', 'Corporate Training Provider'), ('real_estate_agency', 'Real Estate Agency'), ('real_estate_agent', 'Independent Real Estate Agent'), ('wholesale', 'Wholesaler / Distributor'), ('retail_chain', 'Retail Chain / Multi-Location Store'), ('warehouse', 'Warehouse / Distribution'), ('agency', 'Agency / Professional Services'), ('garage', 'Garage / Auto Repair Shop'), ('dealership', 'Vehicle Dealership'), ('auto_parts', 'Auto Parts Store'), ('auto_supplier', 'Automotive Supplier'), ('logistics', 'Logistics & Freight Company'), ('freight_forwarder', 'Freight Forwarder / Customs Broker'), ('courier', 'Courier & Last-Mile Delivery'), ('travel_agency', 'Travel Agency / Tour Operator'), ('tour_operator', 'Tour Operator'), ('corporate_travel', 'Corporate Travel Management'), ('ota', 'Online Travel Agency (OTA)'), ('salon', 'Hair & Beauty Salon'), ('spa', 'Spa & Wellness Centre'), ('care_home', 'Care Home / Assisted Living'), ('personal_trainer', 'Personal Trainer / Fitness'), ('landscaping', 'Landscaping & Garden Services'), ('nursery', 'Garden Nursery / Plant Shop'), ('florist', 'Florist'), ('consulting', 'Business Consulting Firm'), ('supply_chain_consulting', 'Supply Chain Consulting'), ('it_consulting', 'IT / Technology Consulting'), ('legal', 'Legal / Law Firm'), ('accounting_firm', 'Accounting / Audit Firm'), ('other', 'Other')], default='business', max_length=30)),
                ('installation_type', models.CharField(choices=[('cloud', 'Cloud Hosted'), ('ip_locked', 'IP-Locked Cloud'), ('self_hosted', 'Self Hosted')], default='cloud', max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_phone', models.CharField(blank=True, max_length=30)),
                ('business_address', models.TextField(blank=True)),
                ('logo', models.TextField(blank=True, max_length=100, null=True)),
                ('storage_used_mb', models.FloatField(default=0.0)),
                ('storage_limit_mb', models.FloatField(default=512.0)),
                ('allowed_ips', models.JSONField(blank=True, default=list)),
                ('sync_token', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('self_hosted_url', models.URLField(blank=True, help_text='Their server URL, used to push sync requests')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical business instance',
                'verbose_name_plural': 'historical business instances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBusinessEmployee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('ceo', 'CEO / Chief Executive Officer'), ('president', 'President'), ('managing_director', 'Managing Director'), ('cfo', 'CFO / Chief Financial Officer'), ('cto', 'CTO / Chief Technology Officer'), ('cio', 'CIO / Chief Information Officer'), ('coo', 'COO / Chief Operations Officer'), ('cmo', 'CMO / Chief Marketing Officer'), ('chro', 'CHRO / Chief HR Officer'), ('cso', 'CSO / Chief Sales Officer'), ('director', 'Director'), ('technical_director', 'Technical Director'), ('creative_director', 'Creative Director'), ('finance_director', 'Finance Director'), ('operations_director', 'Operations Director'), ('sales_director', 'Sales Director'), ('hr_director', 'HR Director'), ('marketing_director', 'Marketing Director'), ('vp', 'Vice President (VP)'), ('vp_sales', 'VP of Sales'), ('vp_marketing', 'VP of Marketing'), ('vp_engineering', 'VP of Engineering'), ('vp_operations', 'VP of Operations'), ('vp_finance', 'VP of Finance'), ('audit_manager', 'Audit Manager'), ('compliance_officer', 'Compliance Officer'), ('manager', 'Manager'), ('department_manager', 'Department Manager'), ('project_manager', 'Project Manager'), ('marketing_manager', 'Marketing Manager'), ('hr_manager', 'HR Manager'), ('finance_manager', 'Finance Manager'), ('operations_manager', 'Operations Manager'), ('production_manager', 'Production Manager'), ('sales_manager', 'Sales Manager'), ('warehouse_manager', 'Warehouse Manager'), ('quality_manager', 'Quality Manager'), ('maintenance_manager', 'Maintenance Manager'), ('it_manager', 'IT Manager'), ('logistics_manager', 'Logistics Manager'), ('procurement_manager', 'Procurement Manager'), ('assistant_manager', 'Assistant Manager'), ('team_leader', 'Team Leader'), ('supervisor', 'Supervisor'), ('accountant', 'Accountant'), ('senior_accountant', 'Senior Accountant'), ('hr', 'HR Officer'), ('hr_officer', 'HR Specialist'), ('engineer', 'Engineer'), ('senior_engineer', 'Senior Engineer'), ('designer', 'Designer'), ('senior_designer', 'Senior Designer'), ('analyst', 'Analyst'), ('business_analyst', 'Business Analyst'), ('data_analyst', 'Data Analyst'), ('it_officer', 'IT Officer'), ('it_specialist', 'IT Specialist'), ('legal_officer', 'Legal Officer'), ('procurement_officer', 'Procurement Officer'), ('production_supervisor', 'Production Supervisor'), ('quality_inspector', 'Quality Inspector'), ('maintenance_engineer', 'Maintenance Engineer'), ('coordinator', 'Coordinator'), ('associate', 'Associate'), ('marketing_staff', 'Marketing Staff'), ('marketing_officer', 'Marketing Officer'), ('sales', 'Sales Representative'), ('sales_officer', 'Sales Officer'), ('sales_rep', 'Sales Rep / Executive'), ('support', 'Customer Support'), ('customer_support', 'Customer Support Specialist'), ('logistics_officer', 'Logistics Officer'), ('warehouse_officer', 'Warehouse Officer'), ('purchasing_officer', 'Purchasing Officer'), ('junior', 'Junior Staff'), ('junior_engineer', 'Junior Engineer'), ('junior_designer', 'Junior Designer'), ('junior_accountant', 'Junior Accountant'), ('junior_analyst', 'Junior Analyst'), ('assistant', 'Assistant'), ('executive_assistant', 'Executive Assistant'), ('administrative_assistant', 'Administrative Assistant'), ('staff', 'Staff / Employee'), ('operator', 'Machine Operator'), ('technician', 'Technician'), ('driver', 'Driver'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('intern', 'Intern'), ('trainee', 'Trainee'), ('apprentice', 'Apprentice'), ('viewer', 'Viewer (Read Only)'), ('custom', 'Custom Position')], default='staff', max_length=30)),
                ('pin_code', models.CharField(blank=True, max_length=6)),
                ('accessible_modules', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('business', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bredbound.businessinstance')),
                ('custom_position', models.ForeignKey(blank=True, db_constraint=False, help_text="Set when role='custom'", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bredbound.customposition')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical business employee',
                'verbose_name_plural': 'historical business employees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
