# Generated by Django 5.0.14 on 2026-06-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssubscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID', max_length=255, null=True),
        ),
    ]
