# Generated by Django 5.0.14 on 2026-06-04 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bredbound', '0015_alter_businessinstance_business_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_agents', models.JSONField(blank=True, default=list)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(default='English', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_method', models.CharField(default='Stripe', max_length=50)),
                ('dashboard_theme', models.CharField(default='default', max_length=50)),
                ('primary_color', models.CharField(default='#63DCB8', max_length=50)),
                ('is_configured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
