# Generated by Django 4.2.28 on 2026-05-28 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bredbound', '0013_userbusinessmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('daraz', 'Daraz'), ('facebook', 'Facebook'), ('custom', 'Custom')], max_length=15)),
                ('store_name', models.CharField(max_length=300)),
                ('store_url', models.URLField(blank=True)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_set', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['store_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('reorder_threshold', models.IntegerField(default=10)),
                ('is_low_stock', models.BooleanField(default=False)),
                ('ai_description', models.TextField(blank=True)),
                ('ai_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('units_sold_30d', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='bredbound.businessinstance')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='merch.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
