# Generated by Django 4.2.28 on 2026-04-29 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0006_alter_businessinstance_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('carrier_type', models.CharField(choices=[('road', 'Road / Truck'), ('air', 'Air Freight'), ('sea', 'Sea / Ocean'), ('rail', 'Rail'), ('courier', 'Courier / Express'), ('intermodal', 'Intermodal')], default='road', max_length=15)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriers', to='bredbound.businessinstance')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('base_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='bredbound.businessinstance')),
                ('preferred_carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tms.carrier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=30)),
                ('shipment_type', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('transfer', 'Internal Transfer'), ('return', 'Return')], default='outbound', max_length=15)),
                ('priority', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('urgent', 'Urgent')], default='standard', max_length=10)),
                ('origin_name', models.CharField(blank=True, max_length=150)),
                ('origin_address', models.TextField(blank=True)),
                ('destination_name', models.CharField(blank=True, max_length=150)),
                ('destination_address', models.TextField()),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_reference', models.CharField(blank=True, max_length=100)),
                ('purchase_order_ref', models.CharField(blank=True, max_length=100)),
                ('cargo_description', models.TextField(blank=True)),
                ('pieces', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('is_hazmat', models.BooleanField(default=False)),
                ('requires_refrigeration', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('booked', 'Booked'), ('pickup_ready', 'Ready for Pickup'), ('in_transit', 'In Transit'), ('at_hub', 'At Hub / Depot'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('exception', 'Exception / Issue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('scheduled_pickup', models.DateTimeField(blank=True, null=True)),
                ('scheduled_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_pickup', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('freight_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('insurance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='bredbound.businessinstance')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='tms.carrier')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='tms.route')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('business', 'shipment_number')},
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('booked', 'Booked'), ('pickup', 'Picked Up'), ('departed', 'Departed'), ('arrived_hub', 'Arrived at Hub'), ('customs', 'Customs Clearance'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('attempt_failed', 'Delivery Attempt Failed'), ('delayed', 'Delayed'), ('exception', 'Exception'), ('note', 'Note')], default='note', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tms.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FreightQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('cargo_description', models.TextField(blank=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transit_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Client'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_quotes', to='bredbound.businessinstance')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tms.carrier')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('business', 'quote_number')},
            },
        ),
    ]
