# Generated by Django 4.2.28 on 2026-05-06 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bredbound', '0011_alter_businessinstance_business_type'),
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='failed_sample_count',
            field=models.IntegerField(blank=True, help_text='Number of failed units found in the sample', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='sample_size_tested',
            field=models.IntegerField(blank=True, help_text='Number of units actually tested (from AQL)', null=True),
        ),
        migrations.CreateModel(
            name='AQLStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_aql_standards', to='bredbound.businessinstance')),
            ],
        ),
        migrations.CreateModel(
            name='AQLRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_size_min', models.IntegerField()),
                ('batch_size_max', models.IntegerField()),
                ('sample_size', models.IntegerField()),
                ('accept_threshold', models.IntegerField(help_text='Maximum failed units allowed to still pass the batch')),
                ('reject_threshold', models.IntegerField(help_text='Minimum failed units required to reject the batch')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='quality_control.aqlstandard')),
            ],
            options={
                'ordering': ['batch_size_min'],
            },
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='aql_standard',
            field=models.ForeignKey(blank=True, help_text='AQL standard applied for sample sizing', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality_control.aqlstandard'),
        ),
    ]
