# Generated by Django 4.2.28 on 2026-05-18 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0011_alter_businessinstance_business_type'),
        ('quality_control', '0002_inspection_failed_sample_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeDefectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_stage', models.CharField(choices=[('incoming', 'Incoming Raw Material'), ('inline_cutting', 'In-line — Cutting & Closing'), ('inline_lasting', 'In-line — Lasting & Bottom'), ('final_prepack', 'Final Pre-Pack')], max_length=20)),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('article_code', models.CharField(blank=True, max_length=50)),
                ('lot_reference', models.CharField(blank=True, max_length=100)),
                ('pairs_inspected', models.PositiveIntegerField(default=0)),
                ('pairs_affected', models.PositiveIntegerField(default=0)),
                ('defect_description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical (Zero Tolerance)'), ('major', 'Major'), ('minor', 'Minor')], default='minor', max_length=10)),
                ('aql_level', models.CharField(blank=True, choices=[('1.5', 'AQL 1.5'), ('2.5', 'AQL 2.5'), ('4.0', 'AQL 4.0')], max_length=5)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('peel_test_result', models.DecimalField(blank=True, decimal_places=2, help_text='N/mm result — applies to Lasting & Bottom stage (pass ≥ 3.5 N/mm)', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_defect_records', to='bredbound.businessinstance')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoe_defects_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
