# Generated by Django 4.2.29 on 2026-03-11 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace_admin', '0003_phase3_schema_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(help_text="'serea' or client email", max_length=150)),
                ('message_text', models.TextField()),
                ('is_permission_request', models.BooleanField(default=False, help_text="True when Serea's confidence < 0.7 and she needs the client to approve an action.")),
                ('permission_granted', models.BooleanField(blank=True, help_text='Null = pending, True = approved, False = denied.', null=True)),
                ('pending_action_context', models.JSONField(blank=True, help_text='JSON payload describing the action awaiting human approval.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conversation Message',
                'verbose_name_plural': 'Conversation Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SereaAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('intern', 'Intern (Entry Level)'), ('entry', 'Junior (1-3 yrs experience)'), ('mid', 'Mid-Level (3-5 yrs experience)'), ('senior', 'Senior (5+ yrs experience)')], default='intern', max_length=20)),
                ('groq_api_key', models.CharField(blank=True, help_text='Optional per-client Groq API key. Falls back to the platform GROQ_API_KEY env var.', max_length=255, null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('working', 'Working'), ('waiting', 'Waiting for Permission'), ('offline', 'Offline')], default='idle', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hired_employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serea_agent', to='workspace_admin.hiredaiemployee')),
                ('tenant', models.ForeignKey(help_text='The Client owning this agent.', on_delete=django.db.models.deletion.CASCADE, related_name='serea_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serea Agent',
                'verbose_name_plural': 'Serea Agents',
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='e.g. Facebook, Instagram, X (Twitter)', max_length=50)),
                ('comment_text', models.TextField()),
                ('action_taken', models.CharField(choices=[('delete', 'Delete'), ('reply', 'Reply'), ('flag', 'Flag'), ('ignore', 'Ignore'), ('pending_approval', 'Pending Approval')], max_length=20)),
                ('sentiment_score', models.FloatField(blank=True, help_text='0.0 (negative) → 1.0 (positive)', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text="Serea's confidence in this decision (0.0 → 1.0)", null=True)),
                ('requires_human', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='serea.sereaagent')),
                ('permission_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_log', to='serea.conversationmessage')),
            ],
            options={
                'verbose_name': 'Moderation Log',
                'verbose_name_plural': 'Moderation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='serea.sereaagent'),
        ),
        migrations.CreateModel(
            name='ContentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sheet_link', models.URLField(blank=True, help_text='Google Sheet URL containing post metadata (caption, hashtags, target platform, etc.)', max_length=500, null=True)),
                ('drive_link', models.URLField(blank=True, help_text='Google Drive URL for the image or video asset to post.', max_length=500, null=True)),
                ('post_date', models.DateTimeField(help_text='Scheduled UTC post time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_detail', models.TextField(blank=True, help_text="Populated if status='failed'; contains the error message for debugging.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_queue', to='serea.sereaagent')),
            ],
            options={
                'verbose_name': 'Content Queue Item',
                'verbose_name_plural': 'Content Queue',
                'ordering': ['post_date'],
            },
        ),
        migrations.CreateModel(
            name='AgentInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_text', models.TextField(help_text='Short directive, e.g. "Always use emojis and sign off with \'Best, Serea\'"')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='serea.sereaagent')),
            ],
            options={
                'verbose_name': 'Agent Instruction',
                'verbose_name_plural': 'Agent Instructions',
            },
        ),
    ]
