# Generated by Django 4.2.29 on 2026-03-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sereaagent',
            name='ai_model',
            field=models.CharField(choices=[('llama3-70b-8192', 'Llama 3 70B (Groq)'), ('llama3-8b-8192', 'Llama 3 8B (Groq)'), ('llama-3.1-70b-versatile', 'Llama 3.1 70B Versatile (Groq)'), ('llama-3.1-8b-instant', 'Llama 3.1 8B Instant (Groq)'), ('mixtral-8x7b-32768', 'Mixtral 8×7B (Groq)'), ('gemma2-9b-it', 'Gemma 2 9B (Groq)'), ('gpt-4o', 'GPT-4o (OpenAI)'), ('gpt-4o-mini', 'GPT-4o Mini (OpenAI)'), ('gpt-4-turbo', 'GPT-4 Turbo (OpenAI)'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo (OpenAI)')], default='llama3-70b-8192', help_text='The LLM model Serea will use for this agent.', max_length=60),
        ),
        migrations.AddField(
            model_name='sereaagent',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='Optional per-client OpenAI API key. Required when using an OpenAI model.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sereaagent',
            name='token_limit_override',
            field=models.IntegerField(blank=True, help_text='Monthly token cap for this agent. Leave blank to inherit the cap from the hired AI tier. Set to 0 for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='sereaagent',
            name='tokens_used_this_month',
            field=models.IntegerField(default=0, help_text='Running total of tokens consumed this calendar month.'),
        ),
    ]
