# Generated by Django 4.2.29 on 2026-03-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serea', '0004_alter_sereaagent_ai_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sereaagent',
            name='ai_model',
            field=models.CharField(choices=[('llama3-70b-8192', 'Llama 3 70B (Groq)'), ('llama3-8b-8192', 'Llama 3 8B (Groq)'), ('llama-3.3-70b-versatile', 'Llama 3.3 70B Versatile (Groq)'), ('llama-3.1-8b-instant', 'Llama 3.1 8B Instant (Groq)'), ('mixtral-8x7b-32768', 'Mixtral 8×7B (Groq)'), ('gemma2-9b-it', 'Gemma 2 9B (Groq)'), ('meta-llama/llama-3.3-70b-instruct:free', 'Llama 3.3 70B (OpenRouter FREE)'), ('meta-llama/llama-3.1-8b-instruct:free', 'Llama 3.1 8B (OpenRouter FREE)'), ('google/gemma-3-27b-it:free', 'Gemma 3 27B (OpenRouter FREE)'), ('google/gemma-3-12b-it:free', 'Gemma 3 12B (OpenRouter FREE)'), ('mistralai/mistral-7b-instruct:free', 'Mistral 7B (OpenRouter FREE)'), ('deepseek/deepseek-r1:free', 'DeepSeek R1 (OpenRouter FREE)'), ('deepseek/deepseek-v3-0324:free', 'DeepSeek V3 (OpenRouter FREE)'), ('microsoft/phi-4:free', 'Phi-4 (OpenRouter FREE)'), ('qwen/qwen3-8b:free', 'Qwen3 8B (OpenRouter FREE)'), ('meta-llama/llama-3.3-70b-instruct', 'Llama 3.3 70B (OpenRouter)'), ('anthropic/claude-3.5-haiku', 'Claude 3.5 Haiku (OpenRouter)'), ('google/gemini-flash-1.5', 'Gemini Flash 1.5 (OpenRouter)'), ('gpt-4o', 'GPT-4o (OpenAI)'), ('gpt-4o-mini', 'GPT-4o Mini (OpenAI)'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo (OpenAI)')], default='llama-3.3-70b-versatile', help_text='The LLM model Serea will use for this agent.', max_length=60),
        ),
    ]
