# Generated by Django 4.2.29 on 2026-03-14 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serea', '0005_alter_sereaagent_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sereaagent',
            name='onboarding_complete',
            field=models.BooleanField(default=False, help_text='True once the client has connected at least one platform and provided content.'),
        ),
        migrations.CreateModel(
            name='ClientContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='What is this content for?')),
                ('source_type', models.CharField(choices=[('csv_upload', 'CSV File Upload'), ('manual_text', 'Manual Text Entry'), ('google_drive', 'Google Drive Link')], default='manual_text', max_length=20)),
                ('content_type', models.CharField(choices=[('product_info', 'Product / Service Info'), ('faq', 'FAQ (Frequently Asked Questions)'), ('tone_guide', 'Tone & Voice Guide'), ('brand_guidelines', 'Brand Guidelines'), ('response_templates', 'Response Templates for Comments/DMs'), ('competitor_info', 'Competitor Research'), ('post_content', 'Posts / Content for Publishing'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(blank=True, help_text='Upload a .csv or .txt file', null=True, upload_to='serea/content/')),
                ('drive_url', models.URLField(blank=True, help_text='Google Drive folder or file URL', max_length=500, null=True)),
                ('manual_text', models.TextField(blank=True, default='', help_text='Paste your content directly here (Markdown supported)')),
                ('parsed_content', models.TextField(blank=True, default='', help_text="Extracted/cleaned text content injected into Serea's context")),
                ('is_active', models.BooleanField(default=True, help_text='Only active files are used by Serea')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_files', to='serea.sereaagent')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content File',
                'verbose_name_plural': 'Content Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp Business'), ('twitter_x', 'X (Twitter)'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20)),
                ('account_id', models.CharField(help_text='Page ID / Account ID / Channel ID on the platform', max_length=255)),
                ('account_name', models.CharField(help_text='Your page name or @handle as it appears on the platform', max_length=255)),
                ('access_token', models.TextField(help_text='Primary access token. IMPORTANT: keep this secret — do not share it.')),
                ('extra_credentials', models.JSONField(blank=True, default=dict, help_text='Platform-specific extra credentials as JSON. Examples:\nTwitter: {"api_key": "...", "api_secret": "...", "access_token_secret": "..."}\nInstagram: {"instagram_business_account_id": "..."}\nWhatsApp: {"phone_number_id": "...", "waba_id": "..."}\nYouTube: {"refresh_token": "...", "channel_id": "..."}')),
                ('page_bio', models.TextField(blank=True, default='', help_text='Bio / description fetched from the platform')),
                ('page_data', models.JSONField(blank=True, default=dict, help_text='Cached metadata fetched from the platform API (followers, category, etc.)')),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('error', 'Connection Error'), ('expired', 'Token Expired')], default='connected', max_length=20)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='serea.sereaagent')),
            ],
            options={
                'verbose_name': 'Social Media Account',
                'verbose_name_plural': 'Social Media Accounts',
                'ordering': ['platform'],
                'unique_together': {('agent', 'platform')},
            },
        ),
    ]
