# Generated by Django 4.2.29 on 2026-03-14 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serea', '0006_social_accounts_content_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='SereaTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent — drop everything')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('waiting_approval', 'Waiting for Your Approval'), ('waiting_info', 'Waiting for More Info'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('progress_notes', models.TextField(blank=True, default='', help_text="Serea's working notes — updated as she makes progress")),
                ('result', models.TextField(blank=True, default='', help_text="Serea's final output or summary when the task is done")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serea_tasks', to='serea.sereaagent')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serea Task',
                'verbose_name_plural': 'Serea Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
