# Generated by Django 4.2.29 on 2026-04-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serea', '0008_daily_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='sereaagent',
            name='persona',
            field=models.CharField(choices=[('serea', 'Serea (Default Virtual Assistant)'), ('aelin', 'Aelin (Female AI Employee)'), ('kael', 'Kael (Male AI Employee)')], default='serea', help_text='The visual and communication persona the AI will adopt.', max_length=20),
        ),
    ]
