# Generated by Django 4.2.28 on 2026-05-18 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serea', '0009_sereaagent_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('platforms', models.JSONField(default=list, help_text='Platforms this campaign runs on. E.g. ["facebook", "instagram", "linkedin"]')),
                ('goal', models.TextField(blank=True, default='', help_text="Campaign objective — e.g. 'Increase followers by 20%', 'Drive 500 link clicks'")),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('progress_notes', models.TextField(blank=True, default='', help_text="Serea's running notes on campaign progress")),
                ('results_summary', models.TextField(blank=True, default='', help_text='Final results when campaign ends')),
                ('hashtags', models.CharField(blank=True, default='', help_text='Campaign-specific hashtags', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sereaagent',
            name='managed_platforms',
            field=models.JSONField(blank=True, default=list, help_text='Platforms this agent actively monitors and moderates. Options: facebook, instagram, linkedin. Empty = manage all connected platforms. Example: ["facebook", "instagram"]'),
        ),
        migrations.AddField(
            model_name='sereaagent',
            name='neurolinkit_api_key',
            field=models.CharField(blank=True, help_text='API key for NeuroLinkIt (own AI server). Falls back to NEUROLINKIT_API_KEY env var.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sereaagent',
            name='ai_model',
            field=models.CharField(choices=[('neurolinkit/default', 'Default Model (NeuroLinkIt)'), ('neurolinkit/llama3-70b', 'Llama 3 70B (NeuroLinkIt)'), ('neurolinkit/llama3-8b', 'Llama 3 8B (NeuroLinkIt)'), ('neurolinkit/mistral-7b', 'Mistral 7B (NeuroLinkIt)'), ('neurolinkit/mixtral-8x7b', 'Mixtral 8×7B (NeuroLinkIt)'), ('neurolinkit/gemma2-9b', 'Gemma 2 9B (NeuroLinkIt)'), ('llama3-70b-8192', 'Llama 3 70B (Groq)'), ('llama3-8b-8192', 'Llama 3 8B (Groq)'), ('llama-3.3-70b-versatile', 'Llama 3.3 70B Versatile (Groq)'), ('llama-3.1-8b-instant', 'Llama 3.1 8B Instant (Groq)'), ('mixtral-8x7b-32768', 'Mixtral 8×7B (Groq)'), ('gemma2-9b-it', 'Gemma 2 9B (Groq)'), ('meta-llama/llama-3.3-70b-instruct:free', 'Llama 3.3 70B (OpenRouter FREE)'), ('meta-llama/llama-3.1-8b-instruct:free', 'Llama 3.1 8B (OpenRouter FREE)'), ('google/gemma-3-27b-it:free', 'Gemma 3 27B (OpenRouter FREE)'), ('google/gemma-3-12b-it:free', 'Gemma 3 12B (OpenRouter FREE)'), ('mistralai/mistral-7b-instruct:free', 'Mistral 7B (OpenRouter FREE)'), ('deepseek/deepseek-r1:free', 'DeepSeek R1 (OpenRouter FREE)'), ('deepseek/deepseek-v3-0324:free', 'DeepSeek V3 (OpenRouter FREE)'), ('microsoft/phi-4:free', 'Phi-4 (OpenRouter FREE)'), ('qwen/qwen3-8b:free', 'Qwen3 8B (OpenRouter FREE)'), ('meta-llama/llama-3.3-70b-instruct', 'Llama 3.3 70B (OpenRouter)'), ('anthropic/claude-3.5-haiku', 'Claude 3.5 Haiku (OpenRouter)'), ('google/gemini-flash-1.5', 'Gemini Flash 1.5 (OpenRouter)'), ('gpt-4o', 'GPT-4o (OpenAI)'), ('gpt-4o-mini', 'GPT-4o Mini (OpenAI)'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo (OpenAI)')], default='neurolinkit/default', help_text='The LLM model Serea will use for this agent.', max_length=60),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp Business'), ('twitter_x', 'X (Twitter)'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20),
        ),
        migrations.CreateModel(
            name='EngagementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('like', 'Liked a Post'), ('comment', 'Commented on a Post'), ('follow', 'Followed an Account'), ('unfollow', 'Unfollowed an Account'), ('share', 'Shared / Reposted'), ('dm_sent', 'Sent a DM'), ('mention_reply', 'Replied to Mention'), ('story_react', 'Reacted to Story'), ('poll_vote', 'Voted in Poll'), ('other', 'Other')], max_length=20)),
                ('target_account', models.CharField(blank=True, default='', help_text='The account or post targeted by this action', max_length=255)),
                ('target_url', models.URLField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Why Serea took this action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_logs', to='serea.sereaagent')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_logs', to='serea.campaigntracker')),
            ],
            options={
                'verbose_name': 'Engagement Log',
                'verbose_name_plural': 'Engagement Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaigntracker',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='serea.sereaagent'),
        ),
    ]
