# Generated by Django 4.2.28 on 2026-05-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serea', '0013_ollama_model_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='sereaagent',
            name='manager_name',
            field=models.CharField(blank=True, default='', help_text="Who Serea reports to. She'll address this person when escalating or asking for approval.", max_length=100),
        ),
        migrations.AddField(
            model_name='sereaagent',
            name='working_hours_end',
            field=models.TimeField(blank=True, help_text="End of Serea's working day (your local time). Leave blank for 24/7.", null=True),
        ),
        migrations.AddField(
            model_name='sereaagent',
            name='working_hours_start',
            field=models.TimeField(blank=True, help_text="Start of Serea's working day (your local time). Leave blank for 24/7.", null=True),
        ),
        migrations.AlterField(
            model_name='communitymemberprofile',
            name='engagement_score',
            field=models.FloatField(default=0.5, help_text='0.0 = bad actor / troll, 0.5 = neutral, 1.0 = brand advocate / loyal member.'),
        ),
        migrations.AlterField(
            model_name='communitymemberprofile',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='True when this user has been blocked / reported.'),
        ),
        migrations.AlterField(
            model_name='communitymemberprofile',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='True when this user is on watch — their activity gets extra scrutiny.'),
        ),
        migrations.AlterField(
            model_name='communitymemberprofile',
            name='notes',
            field=models.TextField(blank=True, default='', help_text="Serea's running notes about this user — context for future interactions."),
        ),
        migrations.AlterField(
            model_name='communitymemberprofile',
            name='platform_user_id',
            field=models.CharField(help_text="The user's ID on the platform.", max_length=255),
        ),
        migrations.AlterField(
            model_name='communitymemberprofile',
            name='violation_count',
            field=models.IntegerField(default=0, help_text='Number of rule violations Serea has recorded for this user.'),
        ),
        migrations.AlterField(
            model_name='communitymemberprofile',
            name='welcomed_at',
            field=models.DateTimeField(blank=True, help_text='When Serea first welcomed this member.', null=True),
        ),
        migrations.AlterField(
            model_name='customerservicethread',
            name='escalated_to',
            field=models.CharField(blank=True, default='', help_text='Team or person this was escalated to.', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerservicethread',
            name='platform_thread_id',
            field=models.CharField(blank=True, default='', help_text='DM thread / conversation ID on the platform, if available.', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerservicethread',
            name='resolution',
            field=models.TextField(blank=True, default='', help_text='How this was resolved.'),
        ),
        migrations.AlterField(
            model_name='customerservicethread',
            name='serea_notes',
            field=models.TextField(blank=True, default='', help_text="Serea's running notes on this thread — context, actions taken, next steps."),
        ),
        migrations.AlterField(
            model_name='customerservicethread',
            name='subject',
            field=models.CharField(help_text='One-line description of the issue.', max_length=255),
        ),
        migrations.AlterField(
            model_name='escalationrecord',
            name='description',
            field=models.TextField(help_text='What happened and why this needs escalating.'),
        ),
        migrations.AlterField(
            model_name='escalationrecord',
            name='escalated_to',
            field=models.CharField(blank=True, default='', help_text='Team, department, or person this was escalated to.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sereamemory',
            name='content',
            field=models.TextField(help_text='The actual memory — what Serea should remember.'),
        ),
        migrations.AlterField(
            model_name='sereamemory',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Leave blank for a permanent memory. Set a date for time-limited context.', null=True),
        ),
        migrations.AlterField(
            model_name='sereamemory',
            name='platform',
            field=models.CharField(blank=True, default='', help_text='Platform this memory relates to (blank = all platforms).', max_length=20),
        ),
        migrations.AlterField(
            model_name='sereamemory',
            name='subject',
            field=models.CharField(help_text="Who or what this memory is about. e.g. 'user:fb_12345', 'brand tone', 'PR situation May 2026'.", max_length=255),
        ),
    ]
