# Generated by Django 4.2.28 on 2026-05-26 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_admin', '0006_modulepricingconfig_advanceplanquote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serea', '0014_sereaagent_employee_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sereaagent',
            name='groq_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Optional per-client Groq API key. Falls back to the platform GROQ_API_KEY env var.', null=True),
        ),
        migrations.AlterField(
            model_name='sereaagent',
            name='neurolinkit_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='API key for NeuroLinkIt (own AI server). Falls back to NEUROLINKIT_API_KEY env var.', null=True),
        ),
        migrations.AlterField(
            model_name='sereaagent',
            name='openai_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Optional per-client OpenAI API key. Required when using an OpenAI model.', null=True),
        ),
        migrations.AlterField(
            model_name='sereaagent',
            name='openrouter_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Optional per-client OpenRouter API key. Falls back to OPENROUTER_API_KEY env var.', null=True),
        ),
        migrations.CreateModel(
            name='HistoricalSereaAgent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tier', models.CharField(choices=[('intern', 'Intern (Entry Level)'), ('entry', 'Junior (1-3 yrs experience)'), ('mid', 'Mid-Level (3-5 yrs experience)'), ('senior', 'Senior (5+ yrs experience)')], default='intern', max_length=20)),
                ('persona', models.CharField(choices=[('serea', 'Serea (Default Virtual Assistant)'), ('aelin', 'Aelin (Female AI Employee)'), ('kael', 'Kael (Male AI Employee)')], default='serea', help_text='The visual and communication persona the AI will adopt.', max_length=20)),
                ('neurolinkit_api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='API key for NeuroLinkIt (own AI server). Falls back to NEUROLINKIT_API_KEY env var.', null=True)),
                ('groq_api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Optional per-client Groq API key. Falls back to the platform GROQ_API_KEY env var.', null=True)),
                ('openai_api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Optional per-client OpenAI API key. Required when using an OpenAI model.', null=True)),
                ('openrouter_api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Optional per-client OpenRouter API key. Falls back to OPENROUTER_API_KEY env var.', null=True)),
                ('ai_model', models.CharField(choices=[('neurolinkit/neural-chat:latest', 'Neural Chat (NeuroLinkIt) — best for chat'), ('neurolinkit/unbound-neural-chat:latest', 'Neural Chat Unbound (NeuroLinkIt)'), ('neurolinkit/dolphin-mistral:7b', 'Dolphin Mistral 7B (NeuroLinkIt) — best for persona'), ('neurolinkit/unbound-dolphin-mistral:7b', 'Dolphin Mistral 7B Unbound (NeuroLinkIt)'), ('neurolinkit/glm4:9b', 'GLM4 9B (NeuroLinkIt) — strong general'), ('neurolinkit/unbound-glm4:latest', 'GLM4 Unbound (NeuroLinkIt)'), ('neurolinkit/qwen2.5-coder:14b', 'Qwen 2.5 14B (NeuroLinkIt) — strong reasoning'), ('neurolinkit/qwen2.5-coder:7b', 'Qwen 2.5 7B (NeuroLinkIt)'), ('neurolinkit/unbound-qwen-coder:latest', 'Qwen Coder Unbound (NeuroLinkIt)'), ('neurolinkit/deepseek-coder-v2:16b', 'DeepSeek V2 16B (NeuroLinkIt) — most capable'), ('neurolinkit/unbound-deepseek-coder:latest', 'DeepSeek Coder Unbound (NeuroLinkIt)'), ('neurolinkit/phi4-mini:latest', 'Phi-4 Mini (NeuroLinkIt)'), ('neurolinkit/unbound-phi4-mini:latest', 'Phi-4 Mini Unbound (NeuroLinkIt)'), ('neurolinkit/phi3.5:latest', 'Phi 3.5 (NeuroLinkIt)'), ('neurolinkit/unbound-phi3.5:latest', 'Phi 3.5 Unbound (NeuroLinkIt)'), ('neurolinkit/llama3.2:3b', 'Llama 3.2 3B (NeuroLinkIt)'), ('neurolinkit/unbound-llama3.2:3b', 'Llama 3.2 3B Unbound (NeuroLinkIt)'), ('neurolinkit/gemma3:1b', 'Gemma 3 1B (NeuroLinkIt)'), ('neurolinkit/unbound-gemma3:1b', 'Gemma 3 1B Unbound (NeuroLinkIt)'), ('neurolinkit/gemma2:2b', 'Gemma 2 2B (NeuroLinkIt)'), ('neurolinkit/unbound-gemma2:2b', 'Gemma 2 2B Unbound (NeuroLinkIt)'), ('neurolinkit/qwen3.5:0.8b', 'Qwen 3.5 0.8B (NeuroLinkIt) — fastest'), ('neurolinkit/unbound-qwen3.5:0.8b', 'Qwen 3.5 0.8B Unbound (NeuroLinkIt)'), ('neurolinkit/deepseek-coder-v2:16b-lite-instruct-q4_K_M', 'DeepSeek V2 16B Lite Q4 (NeuroLinkIt)'), ('neurolinkit/codellama:7b-python', 'Code Llama 7B Python (NeuroLinkIt)'), ('neurolinkit/unbound-codellama-python:latest', 'Code Llama Python Unbound (NeuroLinkIt)'), ('llama3-70b-8192', 'Llama 3 70B (Groq)'), ('llama3-8b-8192', 'Llama 3 8B (Groq)'), ('llama-3.3-70b-versatile', 'Llama 3.3 70B Versatile (Groq)'), ('llama-3.1-8b-instant', 'Llama 3.1 8B Instant (Groq)'), ('mixtral-8x7b-32768', 'Mixtral 8×7B (Groq)'), ('gemma2-9b-it', 'Gemma 2 9B (Groq)'), ('meta-llama/llama-3.3-70b-instruct:free', 'Llama 3.3 70B (OpenRouter FREE)'), ('meta-llama/llama-3.1-8b-instruct:free', 'Llama 3.1 8B (OpenRouter FREE)'), ('google/gemma-3-27b-it:free', 'Gemma 3 27B (OpenRouter FREE)'), ('mistralai/mistral-7b-instruct:free', 'Mistral 7B (OpenRouter FREE)'), ('deepseek/deepseek-r1:free', 'DeepSeek R1 (OpenRouter FREE)'), ('microsoft/phi-4:free', 'Phi-4 (OpenRouter FREE)'), ('meta-llama/llama-3.3-70b-instruct', 'Llama 3.3 70B (OpenRouter)'), ('anthropic/claude-3.5-haiku', 'Claude 3.5 Haiku (OpenRouter)'), ('google/gemini-flash-1.5', 'Gemini Flash 1.5 (OpenRouter)'), ('gpt-4o', 'GPT-4o (OpenAI)'), ('gpt-4o-mini', 'GPT-4o Mini (OpenAI)'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo (OpenAI)')], default='neurolinkit/neural-chat:latest', help_text='The LLM model Serea will use. NeuroLinkIt models run on your home server (configure NEUROLINKIT_BASE_URL). Recommended for social media: Neural Chat, Dolphin Mistral, or GLM4.', max_length=80)),
                ('managed_platforms', models.JSONField(blank=True, default=list, help_text='Platforms this agent actively monitors and moderates. Options: facebook, instagram, linkedin. Empty = manage all connected platforms. Example: ["facebook", "instagram"]')),
                ('token_limit_override', models.IntegerField(blank=True, help_text='Monthly token cap for this agent. Leave blank to inherit the cap from the hired AI tier. Set to 0 for unlimited.', null=True)),
                ('tokens_used_this_month', models.IntegerField(default=0, help_text='Running total of tokens consumed this calendar month.')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('working', 'Working'), ('waiting', 'Waiting for Permission'), ('offline', 'Offline')], default='idle', max_length=20)),
                ('onboarding_complete', models.BooleanField(default=False, help_text='True once the client has connected at least one platform and provided content.')),
                ('manager_name', models.CharField(blank=True, default='', help_text="Who Serea reports to. She'll address this person when escalating or asking for approval.", max_length=100)),
                ('working_hours_start', models.TimeField(blank=True, help_text="Start of Serea's working day (your local time). Leave blank for 24/7.", null=True)),
                ('working_hours_end', models.TimeField(blank=True, help_text="End of Serea's working day (your local time). Leave blank for 24/7.", null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('hired_employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workspace_admin.hiredaiemployee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, help_text='The Client owning this agent.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Serea Agent',
                'verbose_name_plural': 'historical Serea Agents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
