# Generated by Django 4.2.28 on 2026-05-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serea', '0015_alter_sereaagent_groq_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp Business'), ('twitter_x', 'X (Twitter)'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn (view-only)')], max_length=20),
        ),
    ]
