# Generated by Django 5.0.14 on 2026-06-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serea', '0016_alter_socialmediaaccount_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentqueue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
