# Generated by Django 4.2.28 on 2026-04-28 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bredbound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-grid', max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('is_default', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('layout', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_dashboards', to='bredbound.businessinstance')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('stat_card', 'Stat Card'), ('bar_chart', 'Bar Chart'), ('line_chart', 'Line Chart'), ('pie_chart', 'Pie/Donut Chart'), ('table', 'Data Table'), ('list', 'List'), ('calendar', 'Calendar'), ('map', 'Map'), ('gauge', 'Gauge'), ('text', 'Text/HTML'), ('recent_activity', 'Recent Activity'), ('quick_links', 'Quick Links')], default='stat_card', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Data source, filters, display options')),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=4, help_text='Grid columns (1-12)')),
                ('height', models.IntegerField(default=2, help_text='Grid rows')),
                ('refresh_interval', models.IntegerField(default=0, help_text='Seconds, 0=no auto-refresh')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard_pro.customdashboard')),
            ],
            options={
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='DashboardSharedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('view', 'View'), ('edit', 'Edit')], default='view', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_users', to='dashboard_pro.customdashboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dashboard', 'user')},
            },
        ),
    ]
