import uuid
from django.db import models

class VideoPitch(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    organization = models.ForeignKey("bredbound.BusinessInstance", on_delete=models.CASCADE, related_name="video_pitches", null=True, blank=True)
    title = models.CharField(max_length=255)

    # Inputs
    business_summary = models.TextField(help_text="Context for the AI to generate the script")
    target_audience = models.CharField(max_length=255, blank=True, help_text="e.g. Angel Investors, Enterprise B2B")

    # Generated Assets
    ai_script = models.TextField(blank=True, help_text="The spoken script generated by Gemini")
    video_url = models.URLField(blank=True, help_text="The rendered MP4 URL from HeyGen/D-ID")

    # State
    status = models.CharField(
        max_length=20,
        choices=[
            ("draft", "Draft"),
            ("generating_script", "Generating Script"),
            ("rendering_video", "Rendering Video"),
            ("completed", "Completed"),
            ("failed", "Failed")
        ],
        default="draft"
    )

    # Video Configuration
    avatar_id = models.CharField(max_length=100, default="default_avatar", help_text="HeyGen/D-ID Avatar ID")
    voice_id = models.CharField(max_length=100, default="en-US-Neural2-F", help_text="TTS Voice ID")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.title} [{self.status}]"


class PresentationSlide(models.Model):
    pitch = models.ForeignKey(VideoPitch, on_delete=models.CASCADE, related_name="slides")
    slide_number = models.PositiveIntegerField()
    image_url = models.URLField(blank=True, help_text="Screenshot of the slide for video overlay")
    talking_points = models.TextField(blank=True, help_text="Specific points the AI must mention on this slide")

    class Meta:
        ordering = ["slide_number"]
        unique_together = [("pitch", "slide_number")]

    def __str__(self):
        return f"Slide {self.slide_number} for {self.pitch.title}"
